### ISSUE TITLE
The floating sidebar does not display properly on mobile screen sizes

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#1]
When the horizontal buttons are present on the same page as the vertical ones, the plugin uses the left edge of the horizontal buttons to determine whether or not there exists enough space to display the floating sidebar buttons. On pages where the horizontal buttons are not present, the plugin displays the sidebar no matter the size of the screen because it does not know where the left side of the content area ends or how much space is available in the left margin. This causes it to show up on all screen sizes, covering up the left edge of the content area on smaller screens.

**Note: If you have any additional information or insight on this issue or any questions, please share in the comments below!**

**Comment by Nicholas-Cardot** [comment]
**Solutions:** There is now an option on the bottom of the "Floating Buttons" tab of the Social Warfare options page. This option allows you to set a number (in pixels) for the minimum screen width at which to show the left floating buttons. This number defaults to 1100. With this number in place, the plugin will now do 1 of 2 things.

1. If the horizontal buttons are present, it will know exactly where the edge of the content is and use that to determine whether or not there is enough room to display the left floating share buttons.

2. If the horizontal buttons are not present, it will hide them any time the screen size is below the number set in the options panel.

**Comment by nwilson99** [comment]
Thanks, that works as described. IE: at default setting left float shows on desktop but not on tablet or mobile, which suits me fine as it was too big and intrusive for those.
