### ISSUE TITLE
Click-to-tweet doesn't adjust with a placed HTTPS link

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#102]
From the user (iref.2704):

When I'm customizing my tweet, I know that adding a URL will make SW think I'm replacing the URL that will be shared. Thus, it doesn't attach the post URL and it adjusts the character count.

But if the manually added URL is https, SW does not replace the post URL and it also does not adjust the character count.

**Comment by Nicholas-Cardot** [comment]
I think both http and https are recognized properly by the Custom Tweet function.

I think that no links whatsoever (neither http or https) are recognized or replaced by the Click to Tweet function.
