### ISSUE TITLE
Panel don't adapt to the width

### ISSUE THREAD

**Issue by Donwar** [warfare-plugins/social-warfare#112]
Sometimes when we scroll to the page or resize him, button don't align correctly! Possible to fix this? Bug only on top.

![f0cd858d-5135-49f2-897e-69edf4faea8f](https://cloud.githubusercontent.com/assets/3985836/13599578/09b2ca2e-e524-11e5-8979-bb4ee6e4c82e.png)

**Comment by Nicholas-Cardot** [comment]
Can you confirm what version of the plugin you are on?

**Comment by Publithings** [comment]
I have the 1.4.2
