### ISSUE TITLE
Vertically Stacked shortcode/PHP snippet

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#116]
Would be great to have the ability to place a vertically stacked set of buttons (like the floating side buttons style) via shortcode or PHP snippet.

**Comment by Nicholas-Cardot** [comment]
This seems redundant. Let me explain. No matter where you place the floating buttons on the page, whether in the header, the footer, or anywhere in between, they are going to get glued to the side of the screen and float with the user. Additionally, we only allow the display of the floating buttons on single posts or pages. On all single posts and pages there already exists an option to turn the floating buttons on or off for specific pages. This on/off toggle would then have the exact same effect as placing a shortcode for them.

Or am I misinterpreting this request?
