### ISSUE TITLE
floating buttons not working left hand side 

### ISSUE THREAD

**Issue by squaredlight** [warfare-plugins/social-warfare#133]
Hello

Our floating buttons will not display on the left hand side of the screen on Posts - they will all over the rest of the site - the issue only seems to be effecting blog post pages?

any ideas?

**Comment by Nicholas-Cardot** [comment]
Please submit a support request to https://warfareplugins.com/contact-us/

You can get in touch with us directly there and that will allow us to investigate your specific issue. As this isn't happening on most sites, it's likely that we just need to adjust a setting on your specific use case.
