### ISSUE TITLE
Make the cache rebuild only run on pages with buttons present

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#136]

**Comment by cmunns** [comment]
Is this going to be in the next update. I just realized not only are the plugin scripts/styles loaded on pages where the buttons aren't present but the cache rebuild is causing significant slowing issues as well on a page where not present.

https://www.dropbox.com/s/nsr8v5bl667wgd2/Screenshot%202016-04-15%2010.24.48.jpg?dl=0

**Comment by cmunns** [comment]
@Nicholas-Cardot if you prefer I can open a support thread or new issue, just let me know.

**Comment by Nicholas-Cardot** [comment]
@cmunns Yes. I closed this issue, because our current development version now has this fixed. The next update should be released on Monday or Tuesday as I'll be out on business tomorrow and Sunday and I don't want to release it today and not be around to support it over the weekend if necessary. But, yes, this has now been fixed and will be released very soon.

Also, thanks so much for checking out the github here and for being a part of the development conversation.

**Comment by Nicholas-Cardot** [comment]
@cmunns However, I don't have a way to detect if the buttons appear on the page in a way that would allow me to turn off the styles and scripts. So, unfortunately, those have to be output everywhere. Additionally, too many users are using caching plugins that combine and minify css and then use the same cached css and js files sitewide. These two conundrums make it impossible, as far as I can tell, to eliminate the css and js files. But, those get browser cached anyways so users won't have to redownload it on every page as they browse the site.

**Comment by cmunns** [comment]
Perfect thanks. The cache rebuild was the primary problem, I could manually dequeue the scripts/styles if I get desparate ;)
Thanks
