### ISSUE TITLE
WhatsApp button showing on iPad

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#143]
(iref.3203)

**Comment by Nicholas-Cardot** [comment]
It looks as though WhatsApp may now be available on more than just mobile devices. I need to research this, but this may no longer be an issue.

**Comment by Nicholas-Cardot** [comment]
I need some feedback to know if this is supposed to appear on more than just mobile now that they've got apps out for pretty much every platform. Dustin?
