### ISSUE TITLE
Pocket icon is broken

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#148]
The Pocket icon doesn't appear after the latest update. I get an error where the plugin is looking for a URL like this:

`http://domain.com/function%20URL()%20%7B%20[native%20code]%20%7D`

**Comment by DustinWStout** [comment]
I'm sure you know this, but just gotta make sure: did you clear all caches? Works fine on our test environments.

**Comment by nutsandbolts** [comment]
Yep, cleared server caches and caching plugin. I've got it happening on two different sites; both show a 404 error for that same URL I mentioned above, and the Pocket icon is missing.

**Comment by nutsandbolts** [comment]
Confirmed on a client site as well (different host).

**Comment by Nicholas-Cardot** [comment]
I'm already out of the office for today, but I'm going to track this issue to completion tomorrow. @nutsandbolts Are you going to be around at all tomorrow? Perhaps you could give me a link to the issue tomorrow when we're both online so that I can see the issue live and get this solved right away.

**Comment by Nicholas-Cardot** [comment]
Can you test this in a secondary browser as well? It could possibly be a conflict with one of your browsers plugins.

**Comment by Nicholas-Cardot** [comment]
@nutsandbolts I believe that I now have this fixed. I'm working on another issue right now, as soon as I get the other issue fixed, I'll release an update that will include this fix. Thanks for your patience!

**Comment by nutsandbolts** [comment]
No worries! I got the notification that the issue was closed, so I'll check once the update is released. Thanks!

**Comment by Nicholas-Cardot** [comment]
@nutsandbolts Before I push this update, would you be willing to install this new version and let me know that it's fixed. I prefer not to push a high quantity of updates, so it would be great to have confirmation before rolling it out to everyone. Thanks!

[social-warfare.zip](https://github.com/warfare-plugins/social-warfare/files/232389/social-warfare.zip)

**Comment by nutsandbolts** [comment]
Still no Pocket icon even after clearing all caches but it did get rid of the error. I'm going to give up on Pocket for now and just be glad everything else seems back to normal. :)

**Comment by nutsandbolts** [comment]
In looking at the icon font, I'm not seeing a Pocket icon in there unless I'm totally blind and missing it (very possible).

**Comment by Nicholas-Cardot** [comment]
@nutsandbolts This version should have all the new icons in the font file now. I fixed the javascript error and forgot to update the font file as well. So sorry for that. Does this one have the pocket icon working for you?

[social-warfare.zip](https://github.com/warfare-plugins/social-warfare/files/232416/social-warfare.zip)

**Comment by nutsandbolts** [comment]
Nope, still no Pocket icon in the font set: https://cloudup.com/ccS6QK9wKpE

**Comment by Nicholas-Cardot** [comment]
It's the second one from the left on that screenshot. It's just a small down arrow. You can see it here on our development server as well:

https://beta.warfareplugins.com/ultimate-social-warfare-test-post/

**Comment by nutsandbolts** [comment]
Interesting. Possibly a conflict with FontAwesome but I'll check into it further on my end.
