### ISSUE TITLE
404 Javascript Error

### ISSUE THREAD

**Issue by brianleejackson** [warfare-plugins/social-warfare#149]
I am getting a 404 Javascript error in my console from Social Warfare plugin. It is even happening on your blog posts. Using [https://warfareplugins.com/culture-social-media-content-marketing-strategy/](https://warfareplugins.com/culture-social-media-content-marketing-strategy/) as an example. Happening across all my sites.

Network panel:

![image](https://cloud.githubusercontent.com/assets/186682/14733130/762155e0-0815-11e6-9100-4119bae1cdec.png)

Shot from Pingdom on your blog post:

![image](https://cloud.githubusercontent.com/assets/186682/14733499/3568938a-0818-11e6-93ff-f6877d6ae613.png)

And in console panel:

![image](https://cloud.githubusercontent.com/assets/186682/14733099/390b4fe4-0815-11e6-98a0-de0e5aef68d3.png)

If you narrow it down to the error... it comes down to something in this code.

`if(SW_CACHE_URL.indexOf("?") > -1) { SW_CACHE_URL += "&sw_cache=rebuild"; } else { SW_CACHE_URL += "?sw_cache=rebuild"; }; var xhr = new XMLHttpRequest(); xhr.open("GET",URL,true); xhr.send(); });}</script>`

Hopefully you can fix it fast.

Thanks!

**Comment by Nicholas-Cardot** [comment]
Looks like the final URL variable should be SW_CACHE_URL inside the xhr.open function.

**Comment by Nicholas-Cardot** [comment]
@brianleejackson I've got this fixed. Turns out it was the typo that you see in the comment above. I'm working on fixing another minor bug and then I'll be releasing the solution for this later this afternoon.

**Comment by brianleejackson** [comment]
Ok awesome, thanks for the fast turn around!

**Comment by Nicholas-Cardot** [comment]
@brianleejackson Before I push this update, would you be willing to install this new version and let me know that it's fixed. I prefer not to push a high quantity of updates, so it would be great to have confirmation before rolling it out to everyone. Thanks!

[social-warfare.zip](https://github.com/warfare-plugins/social-warfare/files/232384/social-warfare.zip)

**Comment by brianleejackson** [comment]
Just tested, I can confirm that the new update does fix the issue. No more 404 :+1:

**Comment by Nicholas-Cardot** [comment]
Awesome! That's great to hear! Thanks so much for reporting this and for helping to test it. You're awesome!

**Comment by brianleejackson** [comment]
Np Nicholas. Glad to help out.

**Comment by Nicholas-Cardot** [comment]
Okay. I just released the new version. 1.4.6.
