### ISSUE TITLE
JS error with ACF number field

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#152]
The last version of SocialWarfare (Version 1.4.7) is generating a bug on the ACF plugin : it's making a javascript error on the Number field validation triggers on min/max values if different of 0.

**Comment by nathobson** [comment]
It's not just the number field. I'm having issues with other fields that prevent the image selection for a post/page (Pinterest and Social Media Image) from being selectable.

**Comment by manuhook** [comment]
Hello, I still have this bug, even with the last update.

**Comment by Nicholas-Cardot** [comment]
1. You're using Advanced Custom Fields? Or are you encountering another error?
2. Have you cleared all caching plugins including cloudfare thus guaranteeing that you're using the latest versions of javascript resources?

**Comment by manuhook** [comment]
Sorry it was a stupid cache problem. Everything is fine.
