### ISSUE TITLE
Add YouTube Video Cards

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#157]
From a user:

************************************************************

I had mentioned it to Dustin when you all first launched, but I would love to have the ability to include a YouTube card image when I'm adding images in a post.

If I wanted to add a link as a YouTube video card, the current process works this way:

In a YouTube video, add a URL as a video card. It goes out and retrieves images, none of which are sized for YouTube video cards. I then have to create an additional image and upload it to YouTube.

If you all could add this to the "social warfare process" so that when someone is writing a blog post, they include one extra image for YouTube video cards, now when you add a URL as a YouTube video card, it would pull that image and you could select it.

Less work. A win-win for everyone. You start to train people to put time into adding the necessary images. You all make content look better when it gets shared.

**Comment by ckarasiewicz** [comment]
Hi @Nicholas-Cardot. Here is some additional information on YouTube video cards that might help with my feature request I sent.

A breakdown on the types of YouTube video cards and how to add them
https://support.google.com/youtube/answer/6140493?hl=en

You can include multiple cards throughout a video. You just have to add the URL.

What they do is then go out and pull the metadata. That's where I think Social Warfare could come in handy, being able to provide that information when someone adds a link to a post that they have optimized with the appropriate images for their respective social media channel.

That's as much documentation as I have, but I think it should give you a starting point.

Let me know if I can help to answer any additional questions that you may have or help test.

Christian

**Comment by DustinWStout** [comment]
YouTube cards pull images from the page and don't have any documentation about the method they use to do this. So it's not like an Open Graph protocol where you can declare specific images via meta tags or use some sort of HTML parameters to tell YouTube, "this is the image I want you to pick up." 

Until YouTube makes a change to this, there's no way to programmatically tell it what to find/use.

**Comment by Nicholas-Cardot** [comment]
So I guess I'm going to have to close this as YouTube doesn't have a specific meta tag that they look for that we can output. If they change that in the future, we'll certainly revisit this.

**Comment by ckarasiewicz** [comment]
Well if they ever decide to open things up, you have an idea you can build
on.

Thanks again Nicholas!

Best,

Christian


Web: www.christiankonline.com | www.socialchefs.com

Newsletter: http://bit.ly/autonewsletter

YouTube: www.youtube.com/ckarasiewicz

Facebook: www.facebook.com/askck

Twitter: @ckroks <http://www.twitter.com/ckroks>
