### ISSUE TITLE
User Request for Flipboard Support

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#178]
> I would love to see Flipboard offered as a social share button in the lineup.
> 
> I still have to run my old Sumome social shares in the floating left sidebar option in addition to the warfare social plugin because you don't have flipboard as an option and I often have readers share my content there.
> 
> If you could include flipboard I could remove a 2nd plugin and stay solely with warfare plugins.

**Comment by Nicholas-Cardot** [comment]
Dustin will add the icon to the font and provide color codes to our colors document and then I'll be able to implement this.
