### ISSUE TITLE
User Request: Multiple Users on Social Identity

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#183]
Here is their request:

> My site has many authors -- some have twitter and Facebook profiles entered. I want the publisher tag there in addition to the author tag (if present). I can't see how to do that. I've remedied (well, not really) it for now by having the keep the twitter, Facebook card plugin active. I don't want to do both. Can't social warfare do this?

I think basically what he's saying is he's like to have a site-wide Social Identity, and then an author-specific Social Identity. Then, perhaps the author could have their social tags added on posts that were made by them?

**Comment by Nicholas-Cardot** [comment]
We pull the Publisher tag from the Social Warfare options page. We pull the Author tag from the User's profile. I don't see how this isn't already fully implemented into the plugin.

**Comment by Nicholas-Cardot** [comment]
So apparently it's not outputting any sort of Facebook author tag from the user profile. I'm looking into that now.

**Comment by Nicholas-Cardot** [comment]
Okay, so it is outputting properly. We're putting together some documentation on this now. Then we'll mark this as complete.

**Comment by Nicholas-Cardot** [comment]
Here's my updated documentation on this issue: https://warfareplugins.com/support/open-graph-twitter-cards-yoast-seo/
