### ISSUE TITLE
User Request: Click to Post on Other Social Media Sites

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#188]
Seeking "click to tweet" functionality for Facebook and Pinterest.

> Right now I am aware of the click to tweet feature, but I do not believe there is a similar feature for other social media platforms, e.g. Click to Post (for Facebook) or Click to Pin (for Pinterest). It sounded like you were saying this feature is being added for Pinterest, correct? Are there plan for Click to Post for FB as well

**Comment by Nicholas-Cardot** [comment]
We already have plans for this on Pinterest, but it simply NOT possible for Facebook. Facebook no longer allows URL parameters that let you declare title, description, image, or anything else. No matter where you click on the page, it will ALWAYS use the information from the Open Graph tags. This is a limitation by Facebook so it's literally nothing that we have access to develop. 

Pinterest is a visual platform that requires the pinning of images. As such, we'll be creating overlays that allow you to pin images (which is already an issue here on GitHub. See #173). For the image overlays, we plan on adding all networks that support implicitly stating those parameters via the URL.

Make sense?
