### ISSUE TITLE
`<ul>` in Popular posts contains a double quote

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#190]
I've seen this come up a few times, popular posts UL looks something like this:
```
<ul"> <!--(note the unclosed double quote)-->
   <li><a>item 1</a></li>
   <li><a>item 2</a></li>
   <li><a>item 3</a></li>
</ul>
```

This means that the CSS is a little more tricky:
 `.widget ul li { color:#eee; }` does not work
`.widget li { color: #eee; }` **does** work

**Comment by Nicholas-Cardot** [comment]
This is already fixed in the current beta and we no longer use list items at all. It's now div containers.
