### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#197]
License registration is getting frozen at the loading screen.

-says "please wait"
-the page is not loading, or "working" (the X doesn't show, the refresh button does show)
-the inspect element trick doesn't solve it.
-Javascript error: `XMLHttpRequest cannot load http://warfareplugins.com/registration-api/?activity=register&emailAddress=[removed personal info]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.example.com' is therefore not allowed access.`

This seems to be happening on a bunch of sites

**Comment by andrewmatheson** [comment]
I can verify the same problem on my end. If you use the registration link it works fine (provides the premium code and a success value in JSON), but the interface itself fails due to the CORS issue.

**Comment by Nicholas-Cardot** [comment]
This is really strange because I have the cross-domain header set on that resource.

header("Access-Control-Allow-Origin: *");

**Comment by Nicholas-Cardot** [comment]
What browser and browser version are you using?

**Comment by andrewmatheson** [comment]
I am running Google Chrome 51.0.2704.84 (64-bit) on Mac OSX 10.11.5.

**Comment by Nicholas-Cardot** [comment]
I think the way to fix this is going to be to pass the ajax request to ajax-admin.php and then send the cross domain request via php. This will take a bit of work, but this should eliminate this issue entirely.
