### ISSUE TITLE
Sidebar Widget to Follow and Display Follower Counts

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#20]
Many users are asking for a widgetized feature that allows them to showcase how many followers they have on each social network and that would also make it very easy for users to click those icons and follow them on the respective social networks.

**Comment by Nicholas-Cardot** [comment]
I need design input before I can develop something like this.

**Comment by AoxoA-Create** [comment]
How about something similar to the one on my page:  http://aoxoa.co/austin-edm-photography-dj-photographer/ ?

**Comment by Nicholas-Cardot** [comment]
@AoxoA-Create Good timing. We actually just finished up 3 designs that we'll be using for our widget. Just finished them up yesterday!!!

**Comment by Nicholas-Cardot** [comment]
In an effort to clean up the workflow here on GitHub, we're moving all accepted Feature Requests (including this one) to our internal roadmap so that we can primarily use this space to track bugs, glitches, and plugin & theme conflicts that are occurring with existing features of the plugin. 

So although I'm closing this issue, I'm not dismissing it. I'm simply separating Bugs from Feature Requests by migrating feature requests over to where I'm tracking our roadmap. 

Sometime in the next week or so, we'll have a page up on our website where everyone will be able to publicly view the items (including this one) that we plan to either add to the core plugin or to build out as addons to the plugin. I'll make sure the link to that page is made available at that time.
