### ISSUE TITLE
AffiliateWP Integration: Go ahead and add the "Enhancement" label :-)

### ISSUE THREAD

**Issue by BurlesonBrad** [warfare-plugins/social-warfare#213]
@DustinWStout I can promise that if I open a command line, I just might blow up the whole innerwebs. _**(Getting VVV setup on a Windows 10 unit took 3 people :laughing: )**_ 
_____
But, wait a sec.  If it's this simple to add ```get_referral_var()``` to social buttons in AffiliateWP: 
https://github.com/AffiliateWP/affiliatewp-code-snippet-library/blob/master/misc/append-affiliate-id-to-jetpack-sharing-links.php
....then wouldn't you 

1.  Pull revenue from [this](https://codecanyon.net/item/easy-social-share-buttons-for-wordpress/6394476) 

2. Get more sales by being listed here: https://affiliatewp.com/3rd-party-add-ons/

3. Have a **GREAT** benefit with**OUT** _(hopefully & presumably)_  adding hours to 'support'

Think you can fire that up correctly, or do 'ya think I oughtta give it a whirl?

**Comment by DustinWStout** [comment]
Hey @BurlesonBrad! Maybe I'm just forgetting another part of a conversation we had, but I'm not following this. Can you give me some more context?

**Comment by BurlesonBrad** [comment]
http://screencast-o-matic.com/watch/cDiYb7igOl

**Comment by DustinWStout** [comment]
Thank you for the detailed video @BurlesonBrad! I get it now. So the plugin detects whether or not an affiliate is logged in and if they are logged in, ANY link they share has the affiliate ref=x is automatically added to the share URL. This is a great feature request. We'll keep this in mind for future releases.

**Comment by BurlesonBrad** [comment]
hmmmmmmmm....... ok, so, what I hear you saying is this:
"This would be a great avenue to add value, add revenue, add exposure, and generate even more sales, as long as we make a note to users saying ```this feature does not work for bit.ly links```" 
Right? 

_Yes, I do have a very pragmatic business sense of approaching things_ :stuck_out_tongue_winking_eye:  **HA!**

Perhaps it's a matter of **_perception_** to ask yourself & the existing client base:
1. How many of you utilize the bit.ly functionality? _(it might be less than you think)_
2. How many of you would see a **greater value** in an option that will tie this into AffiliateWP?
3. How many of you would be ok with this feature released even if it did **_not_** integrate w/ bit.ly?

**Comment by Nicholas-Cardot** [comment]
Closing as this is now being tracked in the following issue:

https://github.com/warfare-plugins/social-warfare/issues/257
