### ISSUE TITLE
Slow page loading with lots of tags

### ISSUE THREAD

**Issue by belgarion2k** [warfare-plugins/social-warfare#214]
I updated from 1.4.8 to 2.0.3 and have had to revert back due to a very slow page load.

On 1.4.8 the homepage loads in 1.5~3.0s.  With 2.0.3 it takes up to 36.0s to load.

Using XDebug it appears the slow times come from the `swp_options_display()` method, in particular the get_terms() methods.  The blog has over 7,000 tags which results in over 800ms just on fetching tags, this is further compounded with the fact that `get_header()` calls `swp_options_display()` twice (once during checking of cache, and again afterwards), and `get_footer()` calls it a third time.

It would be great if this could be optimized.

**Comment by Nicholas-Cardot** [comment]
Great call on this. I'm going to remove this feature today and change the tag selector to just a static input box instead. Great catch on that. When I tested this on my dev server, I only had about 5 sample tags and categories so I never even thought about sites with a ton of them.
