### ISSUE TITLE
Image alignment issues with PinIt hover button

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#218]
The current CSS for the PinIt hover span causes images to lose center alignment.

`.sw-pinit {
    position: relative;
    display: inline-block;
    padding: 0;
}`

Changing the display to "block" seems to resolve this issue. Probably worth looking into whether that's a universal problem or specific to certain sites/themes.

**Comment by Nicholas-Cardot** [comment]
It can't be set to block for a lot of other alignemnts, however, I do have a solution.

I set the javascript to check the margin, padding, float and a few other properties and to remove those properties from the image and add them to our wrapper. I'll simply add the display property to the list of properties that get copied over and then that should fix it.

Buuuuuuut, I'll do that when I get home from duties on Monday.
