### ISSUE TITLE
Essential Grids conflict

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#220]
One user has reported a conflict with the Essential Grids plugin in "Even" mode--images are "zoomed in". Switching to "Masonry" grid fixes the problem. 

iRef.5025

**Comment by nutsandbolts** [comment]
Since that's a premium plugin, can we reach out to the dev to see if we can get a copy for testing? I don't have a Warfare email address yet so I probably wouldn't be taken seriously.

**Comment by Nicholas-Cardot** [comment]
When the images are "zoomed in" is it related to the Pin Button wrapper? Or is that not in play in this situation?

**Comment by Nicholas-Cardot** [comment]
And yes, let's definitely try to get a copy so that we can replicate and then fix this issue.

**Comment by Nicholas-Cardot** [comment]
Was that conflict because of the Pinterest button and the way that it was being added? I'd like to see this tested on our 2.1.0 version of the plugin to see if it changed the way these two interact together.

**Comment by Nicholas-Cardot** [comment]
I got this fixed up a few days ago.
