### ISSUE TITLE
Release 2.0.3 broken

### ISSUE THREAD

**Issue by jgadbois** [warfare-plugins/social-warfare#224]
After upgrading I get the following error:

A required file (/home/xxxxxxxx/public_html/wp-content/plugins/social-warfare/functions/media-options.php) was unable to be loaded since it does not exist.

See another person with issue here: https://wordpress.org/support/topic/fatal-error-2235?replies=2

**Comment by Nicholas-Cardot** [comment]
For some reason this file didn't upload when I pushed it to the WordPress repository. It is now in there. Simply delete and reinstall and this error should immediately go away. Sorry for that!
