### ISSUE TITLE
Alt tags don't pull correctly with PinIt hover button

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#230]
(iref 5215)

When the PinIt hover button is used, the first word of the entered alt tag is pulled and displays as the Pinterest description rather than the entire string. Looks like it may be balking when running into special characters within the alt tag.

**Comment by Nicholas-Cardot** [comment]
Can you drop that particular alt tag in here so that I can paste it into my dev site and get this replicated? Thanks!

**Comment by nutsandbolts** [comment]
It was "Healthy & Delicious" something or other. I think it was the ampersand that did it.
