### ISSUE TITLE
Update the positioning method on the Pin it Button images

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#232]
From a user:

> It looks like the hover pin button adds absolute positioning to the original image. Unfortunately there is no definition for that absolute positioning. In our case the images are shifting to the right so the left edge is in the center of the image space.
> 
> I see two different ways to fix that. Either revert the base image to relative positioning or add left: 0; to the positioning so that the image starts in the correct place at the left edge of it's parent container.

As we need the absolute positioning for other reasons, I'm going to attempt the left:0; fix first then look for alternate ideas if that doesn't take care of it.

**Comment by nutsandbolts** [comment]
See also iref 5213 - it's related to this but involves the span tags used with the overlay.

**Comment by nutsandbolts** [comment]
See also iref 5271 - the overlay takes a few seconds to conform to the shape of the image. The site in question has some PNGs with weird rounded corners and the sharp corners show for a split second when hovering.
