### ISSUE TITLE
OG image values being passed when height/width are blank

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#233]
From a user:

> We were having problems with og:image:width and og:image:height being outputted even if there wasn't an og:image tag. They would both have blank values. This caused some trouble as we have another plugin to output the same tags with a default image if needed - but the empty tags were confusing facebook's scraper. I hacked a fix by modifying header-meta-tags.php and putting in an extra check for content in the 'open graph image dimensions' section.

**Comment by Nicholas-Cardot** [comment]
When the actual og:image value is output, I'll record in a variable that we did indeed have an image being output. Then I'll check for that variable before outputting the height and width tags and only output them if we did indeed output an image.
