### ISSUE TITLE
Facebook Image not loading when shared

### ISSUE THREAD

**Issue by disneyinsidertips** [warfare-plugins/social-warfare#237]
Image field is blank on Facebook when post is being shared.

**Comment by Nicholas-Cardot** [comment]
Can you please provide more information about this issue?

1. Do you have a link where I can see it in action?
2. Have you checked the OG data through the Facebook debugger to see if there are any errors?
3. Have you set a Social Media image or a post thumbnail?
4. Are you using the free version or the premium version of our plugin?

**Comment by disneyinsidertips** [comment]
Hi,

I have attached a screen shot.  I have all fields filled to pull both FB & Pinterest images. I have paid version of plugin.  It was working until the last update.


Kristi West

<http://www.disneyinsidertips.com>Disney Insider Tips<http://www.disneyinsidertips.com>, Helping You Navigate the Disney Parks with Ease

________________________________

**Comment by nutsandbolts** [comment]
It looks like Github stripped out the screenshot - do you mind opening a ticket via https://warfareplugins.com/contact-us/ so we can take a look at the issue? That way we can get more details and get this resolved for you.

**Comment by DustinWStout** [comment]
This issue can be solved in this support article: https://warfareplugins.com/support/sharing-facebook-isnt-showing-right-image-title-description/

**Comment by portalsuperacao** [comment]
Support link needs update.
