### ISSUE TITLE
Incorrect info pulled on pages created via OptimizePress

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#238]
iref:5232

When using SW buttons on a page created with OptimizePress, the OptimizePress OG data overrides Social Warfare, even when the OptimizePress SEO fields are empty. Seemingly random images and text are pulled if no SEO fields have been filled in.

**Comment by Nicholas-Cardot** [comment]
Is this being output in OUR open graph meta tags, or are they simply outputting a second set of open graph tags themselves that are then trumping ours because they are farther down the page?

**Comment by nutsandbolts** [comment]
Ours don't seem to output at all on the page when OptimizePress is used to create the page.

**Comment by Nicholas-Cardot** [comment]
Do we have a copy of OptimizePress? If not, we need to reach out and try to get a copy so that we can look into this and try to get it resolved.
