### ISSUE TITLE
504 error on blog archive

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#240]
(iref: 5301)

User submits:

> I get a 504 server error whenever Social Warfare is active on the blog archive page. I've been trying to isolate this problem down to the basics, and my testing has shown some interesting results. I have set up a basic template with no header or footer, just the php to a standard wordpress loop that just runs the social_warfare function on each iteration. I've found that I can load 9 posts and the 504 error starts happening when it reaches 10 posts. The php code I'm using is displayed on the template before the loop for clarity.

Related to previously discussed issues with homepage and/or blog archives.

**Comment by Nicholas-Cardot** [comment]
This has to be a server configuration issue. It's likely that the server is running out of memory or something similar which would explain why it can handle x amount of post, but once it reaches y amount of posts it dies. Unless we can get the hosting provider to provide some more specific information, there's no way that we can replicate or make any attempts to actually solve this. It should also be noted than on 7,000+ active installs, this has only ever been reported once.
