### ISSUE TITLE
Popular posts widget doesn't include thumbnail alt tags

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#241]
(iref 5335)

The popular posts widget returns validation errors when thumbnails are used because of the missing alt tags. May be worth pulling that data if it exists so the output is valid.

**Comment by Nicholas-Cardot** [comment]
Since it's a direct link to a post, should we just make it use the post title as an alt and title tag? Or should we check for an alt tag somewhere else first?

**Comment by nutsandbolts** [comment]
I think that's probably the easiest way to handle it. We could check the image for an alt tag, but honestly I think most people probably don't fill that in, so it seems like a lot of checking for nothing. The post title as an alt sounds like a good compromise.

**Comment by Nicholas-Cardot** [comment]
Perfect. That will be very easy to get implemented then.
