### ISSUE TITLE
Aggressive update Cron scheduling

### ISSUE THREAD

**Issue by shadowlocked** [warfare-plugins/social-warfare#242]
On my staging site I have plugin and core updates disabled by default. This morning I had to turn it off for ten minutes, aware that I might not get what I had to get done finished before Social Warfare checked and auto-installed an unauthorized update.

And of course, it happened - I wasn't quick enough. By the time I disabled updates again, SW had updated from 2.0 to 2.04. 

The Cron job that checks for and auto-installs updates runs every 3600 seconds (once an hour), so there is little chance to evade it if you disable updates.

The only way I can see to get round it, and I presume this would work, would be to deactivate Social Warfare before re-enabling update checks. But this is crazy. People who have expensively-developed sites with custom plugin configurations need to be able to control updates in order to avoid having to restore a site from backup when an unexpected conflict or issue in an update causes problems.

**Comment by DustinWStout** [comment]
Automatic plugin updating is not built into Social Warfare. If Social Warfare is automatically updating itself it is likely due to a WordPress configuration or another plugin which auto-updates plugins.
