### ISSUE TITLE
Exclude Concurra from Frame Buster

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#245]
There is a new analytics service called Concurra (https://concurra.com/) which allows for session recording. It seems Frame Buster conflicts with their software and would be great if we created a rule to allow it to work when Frame Buster is activated.

**Comment by Nicholas-Cardot** [comment]
Does Concurra place the site into a frame somehow?

**Comment by Nicholas-Cardot** [comment]
Unfortunately this isn't possible. Javascript doesn't allow you to get any information about the site that your being framed with. In fact, it throws a security error if you attempt to get that information and the frame is on a different domain that your own. So our plugin runs that check anyways. If we get information back, it means that we're being framed from our own domain (like the customize settings page of WordPress), if we get an error, it's from a different domain so we block it. But beyond a generic security error, there's no way to tell the domain name of a site that is framing us.
