### ISSUE TITLE
Duplicating posts takes share counts with it

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#247]
(iref 5691)

We've had a couple of reports of users with plugins to duplicate a post (monthly reports, book reviews, etc.) so they can use the same formatting. When doing so, the share counts move over to the new post, so the numbers are artificially inflated. Not sure there's a ton we can do about this but it's worth looking into I think.

**Comment by Nicholas-Cardot** [comment]
What duplicate post plugin is being used for this? I want to know so I can check if there is a programatic way to exclude our custom fields from being transferred.

**Comment by Nicholas-Cardot** [comment]
I've contacted the author of that plugin. If they can add a filter hook for us to access then we can fix this. Unless they do, however, there is absolutely nothing we can do at our end to stop this from happening. You can view the progress of our conversation with them at the following link:

https://wordpress.org/support/topic/can-you-make-the-blacklist-hookable-so-other-plugins-can-maximize-compatibility/
