### ISSUE TITLE
Great Plugin

### ISSUE THREAD

**Issue by jimhagadorn** [warfare-plugins/social-warfare#249]
I think the only thing missing is the ability to make the sticky buttons smaller, without custom code. Also it would be nice to have a sticky option on the bottom, much like monarch does, for sharing when the side icons disappear below a certain width.

**Comment by DustinWStout** [comment]
The smaller option has been available for a while and the ability to have the side-floating switch to bottom floating on smaller screens will be included in the next update. :D
