### ISSUE TITLE
Email button - reconsider mailto link?

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#250]
# Notes for testers
1. Move the email button from Inactive Icons to Active Icons. Save changes.
2. View a post. Click the email button. It should open a window to your default email handler. 
# 
original issue

(iref 5732)

If a visitor doesn't have a default email program/app set up, the email button mailto link has nowhere to open, which makes it seem like it doesn't work. It may be worth investigating other options for this so that emails can be sent regardless.

I know this starts veering into SMTP territory which could be a nightmare, but I still think we should consider other ways to configure the email button.

**Comment by 88plug** [comment]
Simple fix here

Removed "noPop" from email.php

Then the link works as it should again.

**Comment by nutsandbolts** [comment]
(iref 16603)

A user has suggested that we allow the email button (maybe as an option vs. the current mailto link) to open a popup with the title, URL, etc. prepopulated and selected so it can be copied and pasted. Many people use Gmail or other browser-based email providers that can't utilize a mailto link, so it might make sense to offer an easy way to grab and share the link (especially with the AffWP addon).
