### ISSUE TITLE
Specify share image for Bloglovin?

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#256]
(iref 5945)

When both images are set via SW settings, sharing on Bloglovin uses the social media image. Bloglovin is better suited for a vertical image such as the Pinterest image (screenshot: https://cloudup.com/crP3gFHVri7)

I don't know if this is something we can control, but if we could make Bloglovin pull the Pinterest image (if set), that would likely be better for 99% of users.

**Comment by Nicholas-Cardot** [comment]
What meta field does Bloglovin look at ?

**Comment by Nicholas-Cardot** [comment]
Unless we know what meta tag or whatever they're pulling from, we won't be able to affect this. I've sent them a tweet and I hope they respond. If so, I'll reopen this and make it work.
