### ISSUE TITLE
Marriage

### ISSUE THREAD

**Issue by BurlesonBrad** [warfare-plugins/social-warfare#257]
Hey, here's the code I told you I'd write @DustinWStout 

What it does is it creates affiliate links out of EVERY URL!!! #wahoo!!!

So, now, any time someone is logged in as an affiliate via AffiliateWP, every blog entry, every  page, every **_"whatever"**_, when a _known_ affiliate is logged in, their affiliate ID is added to the URL when they share using Social Warfare! 

So, my options now are to submit this over to Pippin which I've already done.  Hopefully [....if you're smart ;-) & business savvy ] you'll get my added snippet into the plugin and you'll get more sales from having SW listed here: https://affiliatewp.com/add-ons/3rd-party/ 

CC of the email sent to @sumobi  @pippinsplugins over at AffiliateWP:

> https://gist.github.com/BurlesonBrad/9e663b5db12bce9b73f504674c0b32c7
> I still hate coding, I still love behavioral elements, yet sometimes.... I gotta write the code that 'marries' both of those LOVES
> 
> So, take a peek at this, make sure I didn't do anything that'll wind up jacking with someone's site ;-)
> 
> Seems like if Dustin & the folks over at Warfare Plugins were smart, they'd find a spot to put this in the back end of their plugin and then get it up on your site (https://affiliatewp.com/add-ons/3rd-party/) to give Easy Social Share Buttons a run for their money :-) 
> 
> Anyhow....  I needed it. I saw the behavioral application for it. And I got it done.
> After I modified the user's "logged in" time period... ...and... Now, a quick broadcast email to everyone stressing the importance of "Every URL You Share Can Earn You Money" and [drumroll] every time someone sees a Warfare Plugin Share Button, their 💡  craniums remember 💡 💸  M-O-N-E-Y 💸 , and they are even more inclined to share and earn! 🎆 🎉 

Let's apply this!

Ya see how if you promote this "new feature" to all your affiliates, how the numbers increase?
1. People no longer simply "read" entries, they will even go back and post older entries b/c they see how simple it is for them to possibly earn a commission simply by whacking those wonderful little buttons. 😜 
2. Again, we look at the _behavioral metrics_ & you'll _quickly_ find out that any new blog posts will start having an **INCREDIBLY** higher number of social shares.  Especially when _(/if)_ you were to unbashfully broadcast an email out to everyone blatantly **telling them** what they need to do, and what happens when they share.

**Comment by Nicholas-Cardot** [comment]
I love it and will definitely get it integrated. There's only one issue that I see. If I add that to the plugin, and a site owner doesn't use the affiliate plugin, then it will throw a "Call to undefined function" error when you try to call the affwp_is_affiliate() function. So is there a convenient way that we can test if that plugin is present and activated prior to running the contents of that function?

**Comment by BurlesonBrad** [comment]
.......now I'm back over on some SEO work, but... lemme think....

Isn't that where you'd wanna wrap it in one of those ```if then``` php functions? 

Again, I can peck it out, after I google it, refresh my memory, break it three times, but.... it's that simple little ```if then``` function, right?

I remember it's all over WooCommerce plugins. It checks if WC is active first. If you don't find it before I do, I'll get to it ...................eventually 👍

**Comment by BurlesonBrad** [comment]
@Nicholas-Cardot @DustinWStout : How does this look? 👀 
```
// Append the affiliate ID to Social Warfare buttons
function append_affiliate_id_to_social_warfare_sharing_links( $buttons ) {
	if ( function_exists('affwp_is_affiliate') ) {
		// return if non-affiliate
		if ( ! ( is_user_logged_in() && affwp_is_affiliate() ) ) {
			return $buttons;
		}
		
		// append referral variable and affiliate ID to sharing links in Social Warfare
		$buttons['url'] = add_query_arg( affiliate_wp()->tracking->get_referral_var(), affwp_get_affiliate_id(), $buttons['url'] );
	}
	
	return $buttons;
}	
add_filter( 'swp_network_buttons', 'append_affiliate_id_to_social_warfare_sharing_links', 1, 1 );
```

That way, if AffiliateWP isn't **ACTIVE**ated, then you're good-to-go w/out errors ❗

**Comment by Nicholas-Cardot** [comment]
In an effort to clean up the workflow here on GitHub, we're moving all accepted Feature Requests (including this one) to our internal roadmap so that we can primarily use this space to track bugs, glitches, and plugin & theme conflicts that are occurring with existing features of the plugin. 

So although I'm closing this issue, I'm not dismissing it. I'm simply separating Bugs from Feature Requests by migrating feature requests over to where I'm tracking our roadmap. 

Sometime in the next week or so, we'll have a page up on our website where everyone will be able to publicly view the items (including this one) that we plan to either add to the core plugin or to build out as addons to the plugin. I'll make sure the link to that page is made available at that time.

**Comment by ckmahoney** [comment]
Ping @Nicholas-Cardot and myself as a reminder that we need to also account for AffiliateWP users who select `/ref/141` as their referral variable.

**Comment by ckmahoney** [comment]
Or something like that - the point being we only use query parameters and do not account for path variables.

**Comment by BurlesonBrad** [comment]
https://github.com/AffiliateWP/AffiliateWP/issues/2768#issuecomment-406916753
