### ISSUE TITLE
Page Going Blank With Floating Buttons

### ISSUE THREAD

**Issue by adamhagerman** [warfare-plugins/social-warfare#260]
I had a reader contact me to say that when he started scrolling down one of my articles the page went completely blank except for the floating share bar which actually went to the top of the page when it should have been at the bottom. 

I tried to replicate the result but could not at the time. However this morning, it happened to me. We both had the issue in Chrome. I have not tried other browsers. I actually turned off the floating share bar and it works fine now. I'm going to issue a support ticket.

**Comment by Nicholas-Cardot** [comment]
This should be fixed with the 2.1.0 release coming out shortly.
