### ISSUE TITLE
Settings tabs CSS conflict

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#262]
iref 6483 (screenshots)

With Divi in particular (but several other themes/plugins as well), the use of the .ui-tabs-nav selector in the Warfare settings screen throws off the display of other settings tabs. Should probably make that selector more specific to avoid CSS conflicts.

**Comment by Nicholas-Cardot** [comment]
This should now be fixed in version 2.1.0.
