### ISSUE TITLE
Improve Multisite Support

### ISSUE THREAD

**Issue by robneu** [warfare-plugins/social-warfare#275]
I did a bit of testing on a multisite network that I work on occasionally and I think I can explain the main reason why your license doesn't work correctly on multisite.

The way multisite works is it separates each "site" in the database, so they all have their own posts, options, meta, etc tables. When you use `get_option`, `update_option`, etc on multisite, you're pulling the option from that specific site.

This is why even though you use the main multisite domain to generate and store your key, each site on a multisite needs to be individually activated. They'll all share the same key, but none of the sites know that the main site has been registered so they show up as inactive.

Luckily, there is a fix for it called site options. Here's some more information: http://betterwp.net/wordpress-tips/get-and-update-site-options/

In order to support this, you will need to split your registration information out of the main plugin options into a standalone database value that you can get and set using the `site` option variants. On non-multisite installs, those functions should work the same as the non `site` option getters and setters, so you shouldn't need to do anything special other than pull that option value out and use the different getter/setter method for saving them.

**Comment by Nicholas-Cardot** [comment]
I'll most likely implement something like this after we migrate to Easy Digital Downloads. I'll be rebuilding the registration API at that time anyways, so that is probably the best time to make this transition. Just do it all at once that way.
