### ISSUE TITLE
Pin it hover inconsistent when pages have multiple images

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#286]
On image-heavy pages, the Pin it hover is timing out before all the images load. Sometimes this results in partial loading of the images themselves (or they load with classes missing), and other times only some of the images get the Pin it hover button.

Per the audit, we need to switch from a "number of milliseconds" based check to an images loaded check to ensure all images are handled uniformly no matter how many of them are on a page.

**Comment by Nicholas-Cardot** [comment]
This should be fixed with a commit from yesterday. It should now wait until all images have finished loading before adding the buttons.
