### ISSUE TITLE
Unable to access options panel on multisite installs 

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#29]
Notes from User: *"I ran another test, installing the plugin on a very basic multisite install -- same thing happens ... Super Admin can see the nav menu item and access settings, regular Admin user on an individual site that the plugin is enable for cannot."*

**Comment by BoweFrankema** [comment]
Sadly I have the same issue.. I'm unable to access the settings for the plugin on a Multisite install.

**Comment by Nicholas-Cardot** [comment]
This should be fully resolved in our 2.1.0 update.
