### ISSUE TITLE
Bug with the WhatsApp button on Android device

### ISSUE THREAD

**Issue by mvasquez05** [warfare-plugins/social-warfare#298]
Hi Nicholas i hope that you're very well, i want to report a bug with the whatsapp button in your social warfare plugin. Before i try to explain you the bug sorry for my english because i'm using google translator i hope you understand my words.
The problem is that after i make click over the Whatsapp button in my android smartphone this button disappear and also sometimes other social networks share windows are opened,  and the whatsapp application never opens, i want to show you this problem with a very short video with the hope you understand better in the following youtube link:

https://www.youtube.com/watch?v=kbDwFJgWH-A

Smartphone details:
Brand: LG, Model: LG Spirit, Android version 5.0.1, kernel version 3.10.54+, compilation number LRX21Y )

I have already tested the social warfare plugin with different wordpress themes and with everyone has the same problem so it is not caused by a specific theme.

Also i have already tested others plugins like "Easy social share buttons", "MashShare" and "Ultimate Social Deux", and in all these plugins the whatsapp button works perfectly in my LG Spirit smartphone.

Other big problem with the plugin is that if i add for example 10 ten social networks buttons, this buttons in mobile devices are shown in a very bad way ( too small ), this happen because there is not an option to show/hide the additional social networks, this can be easily solved with the inclusion of an option to show the '+' PLUS button at the end of the share bar to show/hide the secondary/other social networks. You can check how the MashShare plugin implement this feature. This is a essencial feature because there are many users who want to display more than 5 social networks and in mobile devices the horizontal space is very limited.

One suggestions to improve your great plugin:
1. Please implement the LikeAfterShare functionality like the plugin Mashshare already do.

Thanks in advance, and i hope you can fix this whatsapp bug and add the '+' PLUS button option to show/hide the secondary social networks at the end of the share bar as fast as possible,

Best Regards,
Miguel

**Comment by warfare-plugins** [comment]
Fixed. Will be part of 2.2 release next week.
