### ISSUE TITLE
Shares showing in excerpts

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#3]
Depending on how certain themes populate the snippets or "excerpt" for blog posts, sometimes the share button words and share counts are showing up at the beginning of the excerpt.

**Comment by Nicholas-Cardot** [comment]
For extremely short posts where the post itself is shorter than the excerpt length, they seem to also show up at the end of the excerpt.

**Comment by yodjii** [comment]
I beleive this is related to the way you inject your button in the excerpt and content.
To remove your button I have to clean the string retreived by 'get_the_excerpt()': 
`$excerpt= preg_replace('%<div class="nc\_.*?</div>%i', "", get_the_excerpt());`
