### ISSUE TITLE
Add visual themes to the popular posts widget

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#30]
- [x] Create an option for selecting the visual styles
- [x] Output the classes from the selected visual style
- [x] Add the necessary CSS for each style

**Comment by Nicholas-Cardot** [comment]
@DustinWStout ,
1. Add or modify style names in /functions/widgets.php starting on line 77
* A. The value must be lowercase and user underscores if longer than a single word
* B. The conditional (if statement) must match the value.
* C. The style name on the right will be displayed to the user for selection and should be a "pretty" version of the class name.
* D. The class name will be output on the UL tag of the list.

2. Add appropriate CSS to /css/style.css for each visual theme.

**Comment by DustinWStout** [comment]
First style created here: http://codepen.io/dustinwstout/pen/doMQJp

**Comment by Nicholas-Cardot** [comment]
Here are some notes from a user that I think are absolutely terrific ideas:

> I was also wondering if it would be possible to get the Popular posts widget to be able to pull a thumbnail image with each of the popular posts instead of just text and display them in different table layouts such as 2 columns and 5 rows, etc. Those seem to be very popular on sidebars and people like visual much more than text.
> 
> Options to consider including 
> Full text, Abbreviated title text, customized title text, No text just image for each post. 
> Choosing size of thumbnails and layout of thumbnails. 
> Choosing Square or rounded thumbnails. 
> All images on left of text, images and text centered or text with image on left.

**Comment by Nicholas-Cardot** [comment]
So most of these user requests are now implemented into the popular posts widget. Only a couple were left out, but the number of available options for the user to set were beginning to get a bit overwhelming so we'll see what kind of feedback we get when I release this newly overhauled version and then we'll revisit this at that point. 

At this point, however, I'm going to go ahead and mark this as closed.
