### ISSUE TITLE
Buttons are wonky when infinite scroll is being used

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#301]
Not sure if we can do anything about this since we rely on the footer for the button display. If someone has infinite scroll in place, whether for archives or single posts, the first set of buttons displays fine but subsequent ones disappear with a `socialWarfarePlugin is not defined` error.

I'm thinking we could consider an add-on for infinite scroll IF there is a different way to detect where the buttons should be.

**Comment by Nicholas-Cardot** [comment]
Do we know of a specific IS plugin or theme that can be used to replicate this on our beta site?

**Comment by nutsandbolts** [comment]
Jetpack's infinite scroll is what most people are using, but it doesn't work very well with Genesis themes. There are several customer sites with the issue though - I can give you some logins when you have time to look into it.

**Comment by Nicholas-Cardot** [comment]
Now that I know the common plugin being used for this, I should be able to replicate (or at least attempt to) this issue on my development server. Hopefully, once I do that, I should be able to come up with a solution quickly.

**Comment by scott-wiser** [comment]
Let me know if you are aware of any notorious plugin/theme combos.  I can create a number of test scenarios for them also

So this one is Jetpack plugin and Genesis theme?
