### ISSUE TITLE
Social Warfare Custom Options Location

### ISSUE THREAD

**Issue by Gene-W** [warfare-plugins/social-warfare#302]
I cannot seem to move the location of the SW custom options in the post editor. I'm not really sure how it got to this spot, but when I drag it to where it used to be it returns to the top right sidebar as soon as I refresh edit post or open another post to edit.

![659cb3b2-b23e-11e6-9222-e76f4a4358ec](https://cloud.githubusercontent.com/assets/19363963/20696063/7fe9c306-b5b6-11e6-9a50-afc027e369d4.png)

**Comment by nutsandbolts** [comment]
Hi @Gene-W - Sorry you're having trouble! Do you mind opening a support ticket so I can take a closer look at this? When you do, please submit your system status by visiting the Social Warfare settings and clicking the light blue Get System Status button on the right. This will open a box with details about your config, which you can copy and paste into your ticket. Thanks!
