### ISSUE TITLE
Translate all strings

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#303]
From a user via blog comments: 

> Hi
> You have forgotten to translate all strings…
> “Share” or “Shares” is displayed in French instead of “Partage” or “Partages”

**Comment by guilhasn** [comment]
Hi, 
The portuguese translation is missing. 
Instead "Partilhar" i have "Share". 
How can we solve this?
Best Regards, 
NS

**Comment by jonathannbs** [comment]
I can help to translate if you need, hope that you'll fix this soon.

**Comment by guilhasn** [comment]
Ok, how?

**Comment by jonathannbs** [comment]
You don’t know where the problem come from?

Cheers
—
Jonathan Nabais,
contact@jonathannabais.fr <mailto:contact@jonathannabais.fr>
LinkedIn <http://fr.linkedin.com/pub/jonathan-nabais/83/720/a79/> | jonathannabais.fr <http://www.jonathannabais.fr/> | @jonathannabais <http://twitter.com/jonathannabais>

**Comment by guilhasn** [comment]
No!!!

**Comment by jonathannbs** [comment]
Ok I think it’ll difficult to find out if you don’t know where does it come from.

Keep me in touch
—
Jonathan Nabais,
contact@jonathannabais.fr <mailto:contact@jonathannabais.fr>
LinkedIn <http://fr.linkedin.com/pub/jonathan-nabais/83/720/a79/> | jonathannabais.fr <http://www.jonathannabais.fr/> | @jonathannabais <http://twitter.com/jonathannabais>

**Comment by Nicholas-Cardot** [comment]
Here's what I need to do to fix this:

1. I need to port the updated version of the .po file over to poeditor.com. This will list all strings that need to be translated.

2. Anyone who wants to, will then be able to jump onto the translation project and translate any strings that you would like to have translated for your site. Then let me know when your done.

3. Any updated languages files, I'll then reimport into the plugin which will then cause those strings to be properly translated. 

I'm out on holiday right now, but I'll get the ball rolling on this next week when I get home.

**Comment by Nicholas-Cardot** [comment]
https://poeditor.com/join/project/wL4CtEnJr1

If you follow this link, this is where you are all welcome to contribute to the translations if you'd like to have the plugin translated into your respective languages. Once a language is at or close to 100%, I'll import it right into the plugin for you.

**Comment by jonathannbs** [comment]
I just finished the french project at 100%.

Please make an udpate in order to get them on my website :)

Cheers
—
Jonathan Nabais,
contact@jonathannabais.fr <mailto:contact@jonathannabais.fr>
LinkedIn <http://fr.linkedin.com/pub/jonathan-nabais/83/720/a79/> | jonathannabais.fr <http://www.jonathannabais.fr/> | @jonathannabais <http://twitter.com/jonathannabais>

**Comment by Nicholas-Cardot** [comment]
We've added the 100% complete French into the plugin. It will be included in our release next week. If any of you others want it translated into your language, just click over to through the Poeditor link above, add your translations, and then report back here and I'll import your translations into the plugin for the next release.
