### ISSUE TITLE
whatsapp-button broken

### ISSUE THREAD

**Issue by tratz84** [warfare-plugins/social-warfare#304]
The whatsapp anchor is given an 'noPop' class.

in the social-warfare/js/script.js, function handleWindowOpens(), there's a click event set, if an anchor has the 'noPop' class, it returns false. This causes that the href-event is not triggered.

Note, the 'noPop'-class is also used for the Pinterest button, but the pinterest has a 'onclick' event, which does triggered.

**Comment by tratz84** [comment]
Tested with social-warfare 2.2.0

**Comment by marinaaragon** [comment]
Hi guys, I have been told to address my issue with whatsapp button on social warfare here. I must warn you i am pa newbie on all this. Basically, anytime the whatsapp button is clicked on mobile, it just doesnt do anything whatsover. I have updated to the new version of the plugin, but still not working. Any advice please?

**Comment by tratz84** [comment]
fixed it by adding an onclick-event in the anchor: onclick="window.location = this.href;"

but there's probably a better way to do it

**Comment by marinaaragon** [comment]
Thank you for that....where exactly in script.js should i paste that? sorry i am new at all this

**Comment by tratz84** [comment]
in the file functions/social-networks/whatsapp.php

                        $array['resource']['whatsapp'] .= '<a rel="nofollow" target="_blank" **onclick="window.location = this.href;"** href="whatsapp://send?text=' . $link . '" data-link="whatsapp://send?text=' . $link . '" class="nc_tweet noPop" data-action="share/whatsapp/share">';

**Comment by marinaaragon** [comment]
OK. I attach two images (before and after I paste the coding you say) however it does not work yet. What am i doing wrong?
![after](https://cloud.githubusercontent.com/assets/24411390/20928069/61def886-bbc4-11e6-98c7-c39f6226b7be.png)
![before](https://cloud.githubusercontent.com/assets/24411390/20928068/61deed50-bbc4-11e6-9c21-da3fe3795987.png)

**Comment by tratz84** [comment]
remove the ** ** before & after

**Comment by marinaaragon** [comment]
ahhh thank god. finally, thank you for that, sorry for being so dumb with it, really have 0 knowledge on all this. 
Cheers!!

**Comment by tratz84** [comment]
good to hear it's working! :)

**Comment by marinaaragon** [comment]
yes thank you a lot. have a nice day!!
