### ISSUE TITLE
Bitly auth times out, can't complete

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#305]
When authorizing with Bitly in 2.2.0, the Allow/Deny screen on the Bitly website comes up fine, but the Allow button is getting caught in an endless loop of "Waiting for warfareplugins.com..." until it eventually times out. Not sure if this is a bug (labeling it as such since I suspect it may be) or whether we have something going on with the server.

**Comment by Nicholas-Cardot** [comment]
Whether it's in the plugin or on the server, it directly affects the plugin, so I have no problem counting it as a bug.

I've just attempted to authenticate, and mine went through without any issues. I'll have to find a way to replicate this issue.

Most likely, however, this may have just been a temporary glitch on our server.
