### ISSUE TITLE
WP-Rocket Lazy Load and Pintrest Hover Save button incompatibility

### ISSUE THREAD

**Issue by lvvvvvl** [warfare-plugins/social-warfare#306]
Hello,

I opened a support ticket and Audrea told me to open this to accelerate things.

I've been having an issue with the Pinterest hover Save button not working since I installed the plugin. I narrowed it down to the WP-Rocket Image Lazy Load option.

It seems due to the order in which the images are lazy loaded, the Save button attempts to link to the base64 lazy loaded url instead of the images source.

When someone attempts to Save an image to a board, the image is broken as it'll link to the non-existant base64 url. 

Is there any chance to get a fix for this? I really want to be able to use the Pinterest button as it's one of the main attractions about SW PRO

Thank you.

Mateo

**Comment by Nicholas-Cardot** [comment]
For testing purposes, can you provide me with an example base64 URL that the lazy loader is using alongside the regular, standard URL that it translates to. I should be able to make the Pinterest functions intelligently decode that URL prior to creating the share link. And that should fix this right up.

**Comment by Nicholas-Cardot** [comment]
function isBase64(str) {
    try {
        return btoa(atob(str)) == str;
    } catch (err) {
        return false;
    }
}

Here's a function that I should be able to use to test if the URL is base64, then I can simply decode prior to creating the links. That should take care of this.

**Comment by lvvvvvl** [comment]
Sure Nocholas, I've enabled the Hover button on my website and cleared my caches. Here's a random post: https://goo.gl/aRqQi9

**Comment by Nicholas-Cardot** [comment]
Ahhh. I see what you're talking about. I have another idea that should be able to take care of that. The only issue is that I'm away on holiday. I'm looking into this stuff a bit, but I won't be able to actually implement anything until I get home on Wednesday at the soonest.

However, the research I'm doing on my laptop should make it very easy and quick to get these solutions implemented once I'm home.

**Comment by Nicholas-Cardot** [comment]
All we should have to do is to check if a data-lazy-src attribute exists and then use that instead of the source.

https://github.com/warfare-plugins/social-warfare/blob/master/js/script.js#L364-L368

```
if ( $image.data( 'media' ) ) {
	pinMedia = $image.data( 'media' );
} else if ( $image[0].src ) {
	pinMedia = $image[0].src;
}
```

To:

```
if ( $image.data( 'media' ) ) {
	pinMedia = $image.data( 'media' );
} else if ( $image[0].data-lazy-src ) {
        pinMedia = $image[0].data-lazy-src;
} else if ( $image[0].src ) {
	pinMedia = $image[0].src;
}

```
That should automatically detect the lazyload plugin attribute and automatically use the correct image URL instead of the base64 encoded stuff for the media parameter of the share button.

**Comment by lvvvvvl** [comment]
Sure mate, enjoy your holiday! I'll be more than happy to test it out when you push the update :)
