### ISSUE TITLE
Import/export feature?

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#307]
A couple of users have requested the ability to export settings and import them on another site. This would streamline the setup process considerably. May be useful for an add-on since some people may not need or want this ability, but I think it would be a nice addition to the plugin. 

ACF has a nice way of handling this. You can export to a JSON file and import it elsewhere - it's quick and easy. Just something to consider!

**Comment by DustinWStout** [comment]
This feature request has been moved to our internal list.
