### ISSUE TITLE
Conflict with Yoast on archive pages

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#308]
2.2.0 introduced a conflict with Yoast (which was also recently updated). On archive pages such as categories, the blog page, etc. Social Warfare dumps in OG tags for the most recent post on the page instead of using the Yoast meta title and description. This causes problems if someone shares the category page, blog page, etc. on social - it looks like the individual post is being shared instead of an archive page. I know Warfare doesn't have options for archives (image upload, custom description, etc.) but it should be getting out of the way in those cases.

You can see this [on my site](https://www.nutsandboltsmedia.com/blog/) if you view the page source.

**Comment by Nicholas-Cardot** [comment]
https://github.com/warfare-plugins/social-warfare-pro/blob/master/functions/header-meta-tags.php

Wrap the entirely of each applicable function with is_singular() checks should fix this right up.

For example:

`function swp_open_graph_values($info){`

Will become:

```
function swp_open_graph_values($info){
    if( is_singular() ):
```

This will prevent the OG tags from appearing anywhere other than ONLY on single posts, pages, and post types.
