### ISSUE TITLE
HTTP to HTTPS recovery still broken...but only on multisite

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#309]
Just noticed the recovery URLs are still showing the previous one as https when using share recovery. My page source shows this when http is selected as the previous connection protocol:

``swp_post_url='https://www.nutsandboltsmedia.com/update-genesis-child-theme/';
			swp_post_recovery_url = 'https://www.nutsandboltsmedia.com/update-genesis-child-theme/';
``

**Comment by Nicholas-Cardot** [comment]
Can you confirm that this is still happening? If I remember correctly, I think that I got this fixed, but it just hasn't gone out in an update yet.

**Comment by nutsandbolts** [comment]
I'm not sure. Will try to get this tested tomorrow to see if it has been resolved already.

**Comment by Nicholas-Cardot** [comment]
Reopening. This issue is still occurring, but we've narrowed it down to only happening on multisite installs of WordPress.

**Comment by Nicholas-Cardot** [comment]
There's a filter you could use for this purpose. It is called after the mixed content has been fixed, so you can use it to replace the url back to http. To prevent it from replacing back the wrong URLs, I would extend it with your sw_post_recovery_url string. So it would look something like this:

function rsssl_exclude_http_url($html) { 
    //replace the https back to http 
    $html = str_replace(
         "swp_post_recovery_url = 'https://www.nutsandboltsmedia.com/update-genesis-child-theme/';",
         "swp_post_recovery_url = 'http://www.nutsandboltsmedia.com/update-genesis-child-theme/';", 
         $html); 
    return $html; 
} 
add_filter("rsssl_fixer_output","rsssl_exclude_http_url");

Let me know if you have any questions!

**Comment by Nicholas-Cardot** [comment]
The above should work with 2 modifications:

First, we need to check that the http/https settings are set properly. Otherwise, this replace will run all the time even when recovery is not even activated.

Second, we need to dynamically find the http/https in the strings rather than the static URL's that are in there right now.

**Comment by Nicholas-Cardot** [comment]
I've added the filter provided from really simple SSL and it seems to be working properly.
