### ISSUE TITLE
Show "social shares" column only in applicable post type admin screens

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#311]
Right now when Social Warfare is active, every possible admin screen shows a "social shares" column in the dashboard. We should restrict this to only the post types that have a front end output and could realistically have shares.

**Comment by Nicholas-Cardot** [comment]
Looks like we need to change:

```
add_filter( 'manage_posts_columns', 'createSocialSharesColumn' );
add_filter( 'manage_page_posts_columns', 'createSocialSharesColumn' );
```

To something like:

```
add_filter( 'manage_posts_posts_columns', 'createSocialSharesColumn' );
add_filter( 'manage_page_posts_columns', 'createSocialSharesColumn' );
```

This should allow us to specifically target ONLY the posts and pages instead of all post types everywhere. 

https://github.com/warfare-plugins/social-warfare/blob/master/functions/admin/columns.php#L16-L17
