### ISSUE TITLE
Google +, Twitter and Pinterest Shows PHP warning on page

### ISSUE THREAD

**Issue by jdelia** [warfare-plugins/social-warfare#312]
Receiving this notice:
Running on PHP 7.1 on siteground - when I run on 7.0.13 - no message.

Warning: A non-numeric value encountered in /home/jackiede/public_html/rethink.fm/wp-content/plugins/social-warfare/functions/social-networks/twitter.php on line 126

Warning: A non-numeric value encountered in /home/jackiede/public_html/rethink.fm/wp-content/plugins/social-warfare/functions/social-networks/googlePlus.php on line 81

Warning: A non-numeric value encountered in /home/jackiede/public_html/rethink.fm/wp-content/plugins/social-warfare/functions/social-networks/pinterest.php on line 84
on the latest version.

<img width="748" alt="screen shot 2016-12-11 at 7 06 02 am" src="https://cloud.githubusercontent.com/assets/3217274/21079959/595fe242-bf70-11e6-8307-16702d72f5eb.png">

**Comment by jdelia** [comment]
I've rolled back the version of PHP to 7.0.13 and the message is no longer displaying.

**Comment by Nicholas-Cardot** [comment]
http://php.net/manual/en/migration71.other-changes.php

> Notices and warnings on arithmetic with invalid strings ¶
> 
> New E_WARNING and E_NOTICE errors have been introduced when invalid strings are coerced using operators expecting numbers (+ - * / ** % << >> | & ^) or their assignment equivalents. An E_NOTICE is emitted when the string begins with a numeric value but contains trailing non-numeric characters, and an E_WARNING is emitted when the string does not contain a numeric value.
> <?php
> '1b' + 'something';
> 
> The above example will output:
> 
> Notice: A non well formed numeric value encountered in %s on line %d
> Warning: A non-numeric value encountered in %s on line %d
> 

We'll need to do something like the following to make this work:
$array['totes'] += intval( $array['shares']['twitter'] );

**Comment by Nicholas-Cardot** [comment]
Or possibly by specifically typecasting all of those integer variables prior to passing them in.

**Comment by Nicholas-Cardot** [comment]
http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting
