### ISSUE TITLE
Pinterest description limit is too short

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#314]
Per a conversation a customer had with Pinterest support (iref 7776 and Pinterest documentation mentions it [here](https://business.pinterest.com/en/blog/tips-getting-discovered)), descriptions for pins should be up to 250 characters. Only 60 or so will be shown in the normal grid, but the whole 250 will be used for SERPs. Currently we show a limit of 140 in the editor screen so we should definitely get this up to date.

**Comment by DustinWStout** [comment]
Here's why we set the limit to 140:

When sharing a pin through the Pinterest Pin button script (created by Pinterest), it will automatically detect either the Alt Tag OR the custom description we've allowed for in Social Warfare. However, if the person pinning does not modify that Pin description that is automatically pulled in before Pinning (even if only clicking in the description area) then Pinterest truncates the description at roughly 140 characters. 

In all of our testing, the truncation happened anywhere between 141-150 characters, but we wanted to be safe.

So what was happening is Social Warfare users were writing these amazing Pin descriptions and when someone would pin the post, the pin would show up on Pinterest with an incomplete description, truncated with a "..." at the end.

**Comment by Nicholas-Cardot** [comment]
Yeah, what Dustin said. Unless we get confirmation that this bug has been fixed at Pinterest's end, we'll have to leave the current limitations in place.

**Comment by Nicholas-Cardot** [comment]
By the way, this happened when Pinterest rolled out there newest layout (only a couple months ago) so it is very, very up-to-date. This is a bug in their sharing dialogue box that we are one of the only plugins who have noticed and taken action to safeguard our user's against. As soon as we find that they have fixed this bug, we will definitely change the counter limit for that share box.
