### ISSUE TITLE
Icons show as letters on pages built with Thrive Content Builder

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#315]
This has been an issue for awhile but I just noticed some (hopefully relevant) additional info today. When a page is created with the Thrive Content Builder, the inline styles for Social Warfare are stripped out, which means the icon font doesn't load. Check out the source at [this link](http://www.affiliateunguru.com/example-page) which was made with the builder versus [this one](http://www.affiliateunguru.com/team-national-mlm-business-opportunity-scam-review) that is a normal post. If we can figure out how to prevent the inline styles from being removed, we'll be in business.

**Comment by Nicholas-Cardot** [comment]
Is it possible for us to get a copy of the Thrive Content builder so that I can try to replicate this on our development server?

**Comment by nutsandbolts** [comment]
I've emailed them twice to ask but no one ever responds.

**Comment by scott-wiser** [comment]
Maybe we could build a Javascript program to detect missing styles, classes, ids, and whatever else and make repairs.  That would solve the problem for many other problem sources that also strip the data from the HTML.
