### ISSUE TITLE
"Screen Options" tab in Social Warfare settings

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#316]
With WordPress 4.7 the "Screen Options" tab is now bumping the floating menu bar in the Social Warfare settings page.

**Comment by Nicholas-Cardot** [comment]
Dustin, can you show me a screenshot?

**Comment by DustinWStout** [comment]
<img width="1439" alt="screen shot 2017-01-04 at 12 46 05 pm" src="https://cloud.githubusercontent.com/assets/2152604/21658506/d144af90-d27b-11e6-9a88-c85ccf19db01.png">
<img width="1440" alt="screen shot 2017-01-04 at 12 46 18 pm" src="https://cloud.githubusercontent.com/assets/2152604/21658507/d15b98b8-d27b-11e6-9df6-01137bd96b8d.png">

**Comment by Nicholas-Cardot** [comment]
Okay, I just wrote a function to remove the screen options tab entirely but only from our specific admin page. We don't need it there anyways.
