### ISSUE TITLE
Social Share buttons are not rendered inside AJAX generated content. Please Help !

### ISSUE THREAD

**Issue by mvasquez05** [warfare-plugins/social-warfare#318]
Hi Nicholas, I am posting here to try to accelerate things, because to get help through the Premium Support Contact Form takes too long.

Let me explain the issue:
 
I'm using a theme from MyThemeShop (One of the best Wordpress developers) that use Ajax in the Homepage, and here the Social Warfare buttons are not rendered, but in the other pages that don't use Ajax(e.g. Inside a Post or Category) the buttons are rendered/displayed perfectly.
I really need to show the buttons in the Homepage also, not only in Posts or Category Pages.

I'm using the social_warfare(); function because I need to show the social share buttons in a specific place.

I had the opportunity to contact the main developer of MyThemeShop and after check by himself through my Wordpress Admin and cPanel hosting account he told me the following:

"It seems like the plugin is not compatible with AJAX generated content. Could you please ask plugin author if there is a way to make it work after AJAX call? We will be happy to help if there is a way"

The MyThemeShop developer is willing and ready to help you so that you can fix this issue quickly. He is only waiting for an email address through which he can communicate with you. Please Nicholas
tell me what email address can I give to him.

You can check my **TEST Website** in this link: http://entretify.com/ - And there you can verify that when you click the "Test Category" button to see the post inside that category or click over the "Test Post" title to see the content of that post, in both cases the Social Warfare buttons are rendered/displayed perfectly. The problem is only in the Homepage because AJAX code is used to filter the Posts through the Trending, Latest, and Random buttons.

When you need I can provide you with my cPanel hosting account and Wordpress Admin username and passwords to check by yourself. The MyThemeShop developer already has this information.

If you need any other information from my part or some detail in my description of the issue is not clear(I'm using google translator), please do not hesitate to ask me,

Waiting for your answer,

Best Regards,

Miguel

**Comment by Nicholas-Cardot** [comment]
Can you give me WP admin access to your test site only?

**Comment by mvasquez05** [comment]
Of course Nicholas. Is there any way to send you my WP admin username and password privately through github ?

**Comment by mvasquez05** [comment]
Hi Nicholas, here the details:

*Wordpress Admin:*
Username: test
Password: 8x^jA9@e c ec438679bpqimvg $
URL -> http://entretify.com/wp-admin

*Hosting cPanel: *
Username: bmdprope
Password: gm2L95Dff2
URL -> https://tx2.fcomet.com:2083/


Regards,

Miguel


2017-01-04 21:41 GMT-05:00 Nicholas Cardot <notifications@github.com>:

**Comment by mvasquez05** [comment]
Hi Nicholas, have you been able to check the issue ?, remember that I already sent you my WP admin username and password and also my Hosting cPanel account username and password to info@warfareplugins.com because I don't know how to send private messages through github.

You can Ask to Andrea Whitmer, She has access to info@warfareplugins.com

In case you need help to fix the issue, remember that the MyThemeShop developer is willing to help you so that you can fix this issue quickly and He is only waiting for an email address through which he can communicate with you.

Waiting for your comments,

Regards,
Miguel

**Comment by mvasquez05** [comment]
Hi Nicholas, here more details about the compatibility issue to complement the initial description of the issue:

I'm using the social_warfare(); function in two files inside the wordpress Theme, you can access these two files through my cPanel Hosting Account in the following Path:

File 1: **single.php**  in this path -> public_html/entretify.com/wp-content/themes/mts_socialme

File 2: **theme-actions.php**  in this path -> public_html/entretify.com/wpcontent/themes/mts_socialme/functions

Obviously inside these two files I put the social_warfare(); function in the specific place where I want to show the Social Buttons.

Now inside my WP Admin I will show you the theme settings that cause the compatibility issue:

1. In **Appearance -> Theme Options -> Homepage**  when the "Homepage Tabs" option is "ON" the Social Warfare buttons are Not Rendered in the Homepage BUT when the "Homepage Tabs" option is "OFF" the Social Warfare buttons are displayed perfectly.

2. Within / Inside a post there are no problems, the social warfare buttons are always rendered/displayed with either the "Homepage Tabs" option "ON" or "OFF"

3. Within / Inside a category also no problem, the buttons are displayed with either the "Homepage Tabs" option "ON" or "OFF"

The Problem is ONLY in the Homepage when the "Homepage Tabs" option is "ON", this happens because with this setting the Theme use AJAX to filter and display the Posts results.

I really need to show the Social Share Buttons keeping the "Homepage Tabs" option "ON" because if the option is "OFF" then the Trending, Latest, and Random Tabs/Buttons in the Homepage will be disabled/not visible and the end users(visitors of the website) will not be able to filter the Posts.

Nicholas, if you need any other information or some detail in my description of the issue is not clear please do not hesitate to ask me,

I Really need this thing working,

Regards,

Miguel

**Comment by Nicholas-Cardot** [comment]
Can you install a copy of your theme so that I can install it on my own development server. If I can replicate that behavior based on your added details, I should be able to find a solution quickly.

**Comment by Nicholas-Cardot** [comment]
Sorry, I meant, can you give me a copy so that I can install it....

**Comment by mvasquez05** [comment]
Of course Nicholas,  I already sent You a copy of the Theme to the email info@warfareplugins.com

In case you don't have access to info@warfareplugins.com  you can Ask to Andrea Whitmer, She has access.

Regards,

**Comment by mvasquez05** [comment]
Hi, here the Dropbox link to download the copy of the Theme:

  https://www.dropbox.com/sh/cdsw2w95asfere8/AAD9sN5L2wrjjYpQeSFDrDy5a?dl=0

In case that you need I also sent you the Theme through wetransfer.com  and additionally I sent you my 
WP admin username and password and my Hosting cPanel account login details to info@warfareplugins.com

**Comment by mvasquez05** [comment]
Hi Nicholas, have you been able to find a solution to fix the issue ?

Regards,

**Comment by mvasquez05** [comment]
Here another Dropbox link with the copy of the Theme, in case you didn't notice the link that I sent you two days ago:
https://www.dropbox.com/s/2n3v4j3fizyba4p/mts_socialme.zip?dl=0
