### ISSUE TITLE
wordpress visual editor doesn't work when sw is active

### ISSUE THREAD

**Issue by debbit55** [warfare-plugins/social-warfare#320]
wp visual editor goes to white when sw is active. I have tried to ts to no avail and debug doesn't catch it.

**Comment by Nicholas-Cardot** [comment]
Are you talking about the Visual Editor that's built into WordPress post editor or are you talking about some sort of a Visual Editor plugin?

**Comment by debbit55** [comment]
I'm referring to wordpress visual editor.  I'm not sure why it works on one site vs another on the same hosting but.. having reinstalled, still didn't work. brand new install works but then other things foul out. I've been working in wordpress dev for as long as wordpress has been alive and today I finally threw my hands up. Its crazy.
