### ISSUE TITLE
Pinterest Counts are WAY off

### ISSUE THREAD

**Issue by jhirshon** [warfare-plugins/social-warfare#322]
See attached screen shots
![screenshot_20170109-024739](https://cloud.githubusercontent.com/assets/25067278/21869029/70f21b70-d80a-11e6-8c17-634a1b03a948.png)
![screenshot_20170109-024610](https://cloud.githubusercontent.com/assets/25067278/21869031/7398ec0a-d80a-11e6-8985-1a4703de5df6.png)

**Comment by DustinWStout** [comment]
Seems like this may be an individual case, not a plugin problem. If you have a premium license, go ahead and use our contact form in your Account page (warfareplugins.com/my-account) to send our support team a message.
