### ISSUE TITLE
Social Shares no longer visible in Post / Product overview. 

### ISSUE THREAD

**Issue by DomQuixote** [warfare-plugins/social-warfare#325]
Hello, 

In my admin backend, I no longer find the social shares in the post list (or the product list for woo commerce). It cannot be selected in the 'screen options' tab either. Just gone.

Or am I mistaken and were they never there? Starting to doubt myself now...

**Comment by nutsandbolts** [comment]
They were removed by mistake, but they'll be back in the next update we release. Sorry about that!
