### ISSUE TITLE
Add "featured image" toggle for the Pinterest button fallback.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#328]

**Comment by nutsandbolts** [comment]
Suggested wording (or something along these lines):

> "what should social warfare do if you don't select a pinterest image?" with a dropdown for "show my featured image" or "show a selection of all images on the page"

**Comment by DustinWStout** [comment]
I supposed there's no way of "prioritizing" this, is there?

**Comment by Nicholas-Cardot** [comment]
What do you mean by prioritizing? @DustinWStout

**Comment by Nicholas-Cardot** [comment]
**Roadmap:**
1. Add option to the admin options page.
2. Add a default value to the defaults array
3. Use isset() checks and apply to pinterest.php html output.
