### ISSUE TITLE
Update Facebook cache echo

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#329]
Change:

return $activity;

to:

return true;

https://github.com/warfare-plugins/social-warfare/blob/master/functions/share-cache.php#L291

**Comment by Taytay** [comment]
Hello - I am interested in this fix (I reported the issue). I didn't quite follow what you intend to do. Did you mean that you would change `echo $activity` to no longer `echo $activity`?  Thank you.

**Comment by Nicholas-Cardot** [comment]
Yes, that's correct. It will no longer echo it back. Instead, it will simply echo true; to let our plugin know that the function fired off and that's it. Does that make sense?

**Comment by Taytay** [comment]
Yep! Sounds good. Thank you!
