### ISSUE TITLE
LinkedIn uses featured image instead of OG image when sharing

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#337]
Customer reported this issue and I verified on my own site. LinkedIn is ignoring the og:image tag and uses the featured image instead when sharing via the LinkedIn button. This isn't a matter of the image changing and being cached from before - I checked posts that I know have used the OG image in the past when I shared them.

**Comment by Nicholas-Cardot** [comment]
Do we have any theories as to what is causing this or have they simply changed their programming to no longer look at the og:image tag?

**Comment by nutsandbolts** [comment]
I don't know. Not sure if it's a file size issue (I don't think so - my images are tiny) or the dimensions or what.

**Comment by BhavikSheth** [comment]
Ok this finally worked for me. I changed my url from https://bhaviksheth.github.io to https://bhaviksheth.github.io/index.html which made it work.

I also added 'prefix="og: http://ogp.me/ns#"' to every og meta tag before changing the url but I don't know if that made a difference.

**Comment by nformbiz** [comment]
Hi folks, just a note that this issue has not been resolved.  I was back on LinkedIn today and notice once again that on shares LinkedIn is pulling the wrong image.

**Comment by nutsandbolts** [comment]
Did you set your social media image after the post was published? LinkedIn is the only network that doesn't have some sort of URL validator/debugger to force an update when information has been changed. Unfortunately the only recourse I know of is to wait about a week for LinkedIn's cache to clear out.

**Comment by nformbiz** [comment]
Hi Andrea,
I loaded all of the images approximately a week before the post was
published.  I only noticed it because it was shared to LinkedIn by a reader
before I had a chance to share it there and I saw it in my feed and it was
the feature image rather than the social media image.
Mike

**Comment by Vivasergo** [comment]
> Ok this finally worked for me. I changed my url from https://bhaviksheth.github.io to https://bhaviksheth.github.io/index.html which made it work.

It's really working! Thank's
