### ISSUE TITLE
Social buttons placed multiple times for one post_id: not catching multiple runs of `the_content` filter

### ISSUE THREAD

**Issue by SharpenedSpoon** [warfare-plugins/social-warfare#338]
Using WP v4.7.2; SWP v2.2.1

Looks like a refactor possibly broke things?

I have a shortcode that applies the_content filter to its content (so I can recursively process shortcodes), and every time the filter was run, the social buttons were inserted into the page.

Tracked in down, and although display.php line 59 checks to see if the `$post_id` is in `$swp_already_print` (and if so it does not re-print the buttons), in buttons-standard.php line 281, it looks like that line, the only place that the `$postID` is added to that global array, is commented out.

Uncommenting it doesn’t solve the issue however. I fixed it manually (kinda) by pushing the post id to the global array in display.php (right after the check occurs) and I’m going to keep using it, and hope that when my change is overwritten in the next version, this bug is fixed 🙂

----

This issue was posted in the wordpress.org plugin support forums. Since then, the fix I thought would work did not actually work, however that specific bug I don't think it's necessarily something that needs to be fixed. Specifically, since I was running `the_content` filter multiple times throughout one page's worth of content (a decision I am now questioning), the social buttons get placed near the top of the page's content, and not at the bottom as I would like. There's definitely something to be said for me changing my ways on this one.

That being said, the core issue -- that post ids are not tracked at all -- remains and probably needs a bit of attention

**Comment by Nicholas-Cardot** [comment]
Yeah, we can't really support running the content filter multiple times on one page's worth of content.
