### ISSUE TITLE
Twitter images blurry using FB dimensions

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#339]
Using the recommended 1200x628 social media image for FB results in a blurry/distorted image card on Twitter. Twitter seems to prefer a 1024x512 image like we used in the past - older posts without updated image sizes display as expected. I'm wondering if we should allow a separate image for Twitter since they seem to want to change their dimensions every time the wind blows.

**Comment by Nicholas-Cardot** [comment]
Dustin, can you weigh in on this?

**Comment by DustinWStout** [comment]
Sounds like this is not something we can control. Image compression on social networks is done on their end and is (typically) horrible. We never did a 1024x512 option, what was just Twitter automatically resizing. And it looks like that's what they're doing still, but have just gotten far worse at it. 

If anyone else has more insight on this, I'd love to hear it.
