### ISSUE TITLE
Social Warfare *Pro* Plugin Pulling in Inline Styles into Twitter Description Meta

### ISSUE THREAD

**Issue by MBSchneider** [warfare-plugins/social-warfare#341]
Illustration:
SW Pro **Active**
<img width="640" alt="screen shot 2017-02-14 at 2 30 07 pm" src="https://cloud.githubusercontent.com/assets/5150874/23038264/42b78574-f43e-11e6-82d6-c4f8758b54fe.png">

SW Pro **Off**
![screen shot 2017-02-15 at 2 13 17 pm](https://cloud.githubusercontent.com/assets/5150874/23038256/35b10b84-f43e-11e6-9afd-b2a03b0987cc.png)

This occurs when Wordpress post content contains inline <style> tags towards the beginning of the content.  This is then pulled into the Twitter description meta.

`<meta name="twitter:description" content="body { min-width: inherit; } .orangeLink { color: #e1610b; text-decoration: none; text-align: center; } a.orangeLink { color: #e1610b; text-decoration: none; } a.orangeLink:hover { text-decoration: underline; color: #e1610b; } .videoImg { margin-bottom: 20px; } #hero-header-text { font-size: 50px; color: #fff; margin-top: 30px; line-height: 55px; } .quote-text-blue { font-size: 30px; color: #000; line-height: 42px; } .pain-points { text-align: center; background-color: #854fa0; height: auto; background-size: cover; padding-bottom: 20px; margin-top: 40px; color: #fff; } @media only screen and (max-width: 400px) { #hero-header-text { font-size: 42px; } } Choicelunch Providing healthy lunches for students. Read the Full Story &nbsp; &nbsp; Employees 220 Product Insight Industry">`

Can this be filtered out when constructing the meta descriptions?

**Comment by Nicholas-Cardot** [comment]
Are you wrapping the inline styles with proper <style> tags?

**Comment by MBSchneider** [comment]
I am, yes.
