### ISSUE TITLE
Add translation for "Read here" text using email share

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#345]
The current email share text has "Read here" that isn't included in the .pot file. We need to add this so foreign language sites can send out email shares in their chosen language.

**Comment by nutsandbolts** [comment]
Also the two user profile fields (both the title and the description of the fields) isn't translatable currently.

**Comment by Nicholas-Cardot** [comment]
Roadmap:

The "Read Here" text needs modified on the following line:
https://github.com/warfare-plugins/social-warfare-pro/blob/master/functions/social-networks/email.php#L90

The user profile fields need modified inside the swp_show_user_profile_fields() function located here:
https://github.com/warfare-plugins/social-warfare/blob/master/functions/profile-fields.php#L10

Additionally, this function (and probably the entire file) needs proper doc blocks added.
