### ISSUE TITLE
Version mismatch only works when core is outdated

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#346]
The version mismatch nag we added in 2.2.3 does show a dashboard message if core is behind pro, but not the other way around. Since the Github update checker seems to be the problem, we definitely need this working when pro is out of date as well.

**Comment by Nicholas-Cardot** [comment]
When testing the version comparison, I found that changing the last numbers did show the notice for both.  If you have the numbers used to cause the problem let me know.

Also, there's a PHP function which might be used for this if the version numbers follow standards, and the comparison operators are insufficient (they might be ok):
http://php.net/manual/en/function.version-compare.php (edited)
