### ISSUE TITLE
Yummly control fields have stray text on activation

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#347]
When the Pro add-on is activated, Yummly's category and tag fields say "200" and "on" respectively instead of being blank. This prevents the Yummly button from showing up since those categories/tags don't exist anywhere (on most sites anyway). Need to see where that's coming from and make sure nothing makes its way in there unless the user puts something in those boxes.

**Comment by Nicholas-Cardot** [comment]
Missing defaults

**Comment by Nicholas-Cardot** [comment]
This should now be fully fixed.
