### ISSUE TITLE
Ajax call refreshing counters is called on every page load on cached pages

### ISSUE THREAD

**Issue by fvrichard** [warfare-plugins/social-warfare#350]
HI,

we are using your plugin on multiple websites. If the page with old counters is visited, **swp_is_cache_fresh** condition is satisfied and the javascript with **socialWarfarePlugin.fetchShares();**  is included in footer of source code. As you know this call triggers the AJAX for refreshing share counters.

If you are using some caching plugin ( like WP Rocket ) and page is visited by guest, the javascript in footer is cached and each new guest page visit will trigger that AJAX.

I know, the first condition in AJAX call of function **swp_cache_rebuild** is checking again for **swp_is_cache_fresh** and dies otherwise, but it would be best to avoid this redundant AJAX at all.

The solution I can suggest is adding unix timestamp in javascript and compare it with current timestamp on user machine. This will solve 99% of this calls, unless user would have set his/her time incorrectly.

Thanks,
Richard

**Comment by Nicholas-Cardot** [comment]
A unix timestamp? That's actually a damn good idea. What about timezones though? Or does the unix always use Zulu time (Greenwhich Mean Time)?

But what about once that timestamp expires and is cached as expired? Then it will resume running again on every page load won't it? But then I guess that is where the PHP cache check would come in as a fallback, but with a timestamp, it would at the very least massively reduce those calls.

**Comment by fvrichard** [comment]
> The timestamp is the number of seconds (or milliseconds) elapsed since an absolute point in time, midnight of Jan 1 1970 in UTC time. (UTC is Greenwich Mean Time without Daylight Savings time adjustments.)

**But what about once that timestamp expires and is cached as expired?**

I suggest trigger social counters refresh only if timestamp on user machine and timestamp generated on server is equal or difference is less than one minute ( or 15 seconds ? ). When HTML cache ( WP Rocket) expires, the new html is cached, with new timestamp in javascript and it start checking again ( for next one minute ).

**it would at the very least massively reduce those calls.**
Yes, it would reduce all those ajax call and I appreciate if you will implement this in one of next versions.

Thanks,
Richard

**Comment by Nicholas-Cardot** [comment]
Yes, this is definitely a great idea. I think we'll tag the requests with a timestamp and if the timestamp is more than 30 seconds old, we ignore it and don't process the request. This would all but guarantee that only the first person loading the page after the cache has expired will be the one initiating the cache rebuild.
