### ISSUE TITLE
Add tooltips to settings UI

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#351]
We really need to improve the plugin UI as far as the various options are concerned. Right now there are no explanations or links to documentation and we receive a lot of support tickets for things that shouldn't require tickets. I think we need to add the little tooltips like all other plugins use, even if all we do is link to the relevant support documentation on our site.

I realize this makes the admin pages a little less clean, but we can't sacrifice UX for design.

**Comment by Nicholas-Cardot** [comment]
I'm working on creating the KB articles, one for each section of settings. I'm about halfway done now. Once finished, I'll create links in the UI so if user's would like any additional information about each setting, they'll be able to click and read more. Hopefully, I'll have this finished over the next couple of days.

**Comment by Nicholas-Cardot** [comment]
This is now completed.
