### ISSUE TITLE
Typo on user profile field description

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#353]
On the user edit screen, the description below the FB input says "Please enter the URL of your Facebok profile." Need to correct that typo before the next update is released.

**Comment by scott-wiser** [comment]
This commit should contain the fix:

https://github.com/scott-wiser/social-warfare/commit/a25187329afb16c2c55d2ca1fc524244532c4fa3

**Comment by Nicholas-Cardot** [comment]
This is now fixed.
