### ISSUE TITLE
500 error response from /wp-admin/admin-ajax.php POST on action:swp_cache_trigger

### ISSUE THREAD

**Issue by Sierra45** [warfare-plugins/social-warfare#355]
Seeing a 500 error response from POST to ../wp-admin/admin-ajax.php with form data `action:swp_cache_trigger, post_id:[post_id]` on every page load on the front end. The response to a POST to ../wp-admin/admin-ajax.php on the same page with form data `action:swp_facebook_shares_update, post_id:[post_id], activity:[activity_count]` though is 200 OK. 

Both plugins (core and pro) are up to date and disabling other plugins (including caching plugin) has not resolved the issue. Opting for 'Legacy cache rebuilding during page loads' prevents the page content from fully loading so that doesn't seem like an option. Any suggestions? I appreciate any thoughts you may have.

**Comment by Sierra45** [comment]
Enabling WP_DEBUG exposed: PHP Fatal error:  Call to undefined function curl_multi_init() in ../wp-content/plugins/social-warfare/functions/curl_functions.php on line 17

Looks like curl must be enabled 

Thanks again

**Comment by warfare-plugins** [comment]
Yes. This is not a bug in the plugin. It is a plugin requirement for you to have cURL enabled on your server in order for the API calls to the social networks to go through.
