### ISSUE TITLE
Icons covering content on home page 

### ISSUE THREAD

**Issue by GLenotre** [warfare-plugins/social-warfare#358]
Hi!

My issue is that the social warfare icons are floating on the home page. I want to remove them from my home page. It's especially problematic on mobile:
![screen shot 2017-04-06 at 10 58 26 am](https://cloud.githubusercontent.com/assets/11380138/24763835/2f6400b0-1ab8-11e7-9581-7222cbbfccb5.png)

There's no open/closed issue on this, and I've played around w/ different variations. Here are my plugin display selections right now: 
![screen shot 2017-04-06 at 12 07 31 pm](https://cloud.githubusercontent.com/assets/11380138/24766652/bded128c-1ac1-11e7-912c-611eb06f243b.png)

Under Post Type, the only activated Floating Button is for Page, but I want other pages (other than the homepage) to have these floating icons. 

Here's the site: http://www.missmillmag.com/

Thanks

**Comment by GLenotre** [comment]
I solved the issue by going to Styles, then Floating Share Buttons, then adding 1024 under Minimum Screen Width. (It had not been working even with On Mobile turned off.

**Comment by Nicholas-Cardot** [comment]
Have you submitted a support ticket on this yet?

**Comment by Nicholas-Cardot** [comment]
Go to the post editor for the page that is being used as the home page. Then in the Social Warfare Custom Options, set the float location for that page to none. Now the floating buttons will appear on all pages except for the home page.
