### ISSUE TITLE
Conflict with Avada Theme and Fusion Slider

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#36]
When Social warfare is active the slide does not work, you see only a circle loader. When Social Warfare is disabled the slider works as it should.

**Comment by Nicholas-Cardot** [comment]
I would like to see this tested with our new FlexBox based sizing system and our refactored javascript for version 2.1.0. I believe that this issue should be fully resolved in our next release.

**Comment by Nicholas-Cardot** [comment]
I'll reopen this issue if it's still broken after 2.1.0 comes out next week.
