### ISSUE TITLE
IE11 Twitter button conflict

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#360]
In IE11, the Twitter share button opens both the normal popup and a new tab/window instead of just the popup. Jason was able to reproduce this.

**Comment by Nicholas-Cardot** [comment]
Internet Explorer is still a thing? lol

**Comment by Nicholas-Cardot** [comment]
Can you all both confirm for me if this is still doing that in the latest version that I have on the beta site? You can do so simply by opening the following link in IE11 and seeing if it is still behaving that way: 

https://beta.warfareplugins.com/ultimate-social-warfare-test-post/

**Comment by Nicholas-Cardot** [comment]
I can't seem to replicate this behavior. Perhaps a recent change in the code fixed this and it is no longer an issue.
