### ISSUE TITLE
Update language files with newest translations

### ISSUE THREAD

**Issue by scott-t-11** [warfare-plugins/social-warfare#361]
Update each .mo file with the newest translations.
Files are located in the /languages folder
Translations are located on the POEditor project https://poeditor.com/projects/view?id=57349

**Comment by scott-t-11** [comment]
The following commit has the most recent versions of previously included languages
https://github.com/scott-t-11/social-warfare/commit/ccc2b3e7be0b0502e325ad2422d8290bbeeb3cd6

There appears to be a few additional languages that can be added.  Once I figure out the precise syntax for them I'll add another commit.

I'm concerned because some of the previous languages have no second abbreviation (the underscore then caps letters).  There is also one that has the first lowercase letters different than the second caps letters (da-DK).  I'm wondering if this is an error, or if there is another source of information that I am missing, as I was referencing the Multilingual Codex page which shows a single abbreviation per language (https://codex.wordpress.org/Codex:Multilingual)

Also, I'm unsure which language "hy" references.

**Comment by Nicholas-Cardot** [comment]
You can use the following links to determin the naming structure of each translation file. The total format will be the following:

Format:
{text-domain}-{language code}_{country code}.mo

Example:
social-warfare-de_DE.mo

Here are the list of Language Codes:
http://www.gnu.org/software/gettext/manual/html_chapter/gettext_16.html#Language-Codes

Here are the list of Country Codes:
http://www.gnu.org/software/gettext/manual/html_chapter/gettext_16.html#Country-Codes

**Comment by Nicholas-Cardot** [comment]
Here is a list of all the language codes that are available within the WordPress ecosystem. Just make sure to name the .mo files according to the format that I mentioned above whilst using these language codes:

https://make.wordpress.org/polyglots/teams/

**Comment by Nicholas-Cardot** [comment]
Here's some more great documentation about how these translation work with WordPress: https://localise.biz/help/wordpress/loading-translations
