### ISSUE TITLE
Create a System Check Class to Display on the Admin Options Page

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#362]
Let's create a file called system-checks.php and create within that file a class to detect known conflicts which can then alert the user as to how to fix those known issues to ensure that the plugin works properly as it is designed to work.

1. Let's detect the user's PHP version. If the PHP version is less than 5.3, let's alert the user with the following message:

"Your server is currently using PHP version 5.2 (or whatever version it is). In order for our plugin to fetch share counts properly, you must be using PHP 5.3 or newer. To fix this, simply contact your hosting provider and ask them to update your server to the latest stable version of PHP."

2. Let's detect if the user has cURL enabled. If cURL is not enabled, let's alert the user with the following message:

"Your server has cURL disabled. In order for our plugin to fetch share counts, you must have cURL enabled on your server. To fix this, simply contact your hosting provider and ask them to activate cURL on your server."

3. Let's detect what version of WordPress the user is on. If they are using a version that is more than say 12 months old, let's alert the user with the following message:

"Your website is currently using WordPress version x.x. This version is very out of date. For security and compatibility reasons, you should immediately update WordPress to the latest version."

If you can think of any other important checks, add them to the comments below and we can consider adding them as well.

**Comment by scott-t-11** [comment]
Here's the current System Checker subsystem class diagram:
![systemchecker0-3](https://cloud.githubusercontent.com/assets/26015152/25062716/43da51d2-2186-11e7-9d26-2dc5f5f21f5b.png)

Checks 1 and 2 are compete and initially tested.  

I'll complete 3 next, brainstorm on further items, and provide some further thoughts and ideas.

I'm committing what I have now so you can preview the classes.

**Comment by scott-t-11** [comment]
First commit is here:
https://github.com/scott-t-11/social-warfare/commit/3753edeaa5cbb19791d4f39415f8529c264a0853

This has been initially tested on my test server, and I'll test further as the subsystem is expanded.

**Comment by Nicholas-Cardot** [comment]
You can't use open ended conditionals. Toy must use either brackets or end if. Does that make sense?

**Comment by Nicholas-Cardot** [comment]
Also make sure it is outputting separate red notices for each error rather than one red notice with multiple errors inside of it.

**Comment by Nicholas-Cardot** [comment]
@scott-t-11 What's our progress on this?

**Comment by scott-t-11** [comment]
I didn't want to send all my current workspace commits at once because of a min-width flexbox change which isn't yet fully functional at all widths.  I'm attempting to resolve it.

Rather than wait on all other commits, I went ahead and manually added the following commit which adds the following:
1) Places all classes in one file
2) Changed if statement styles
3) Added wp tester
4) Retested all checks
5) Separated each display unit

**Comment by scott-t-11** [comment]
![systemchecker1may2017](https://cloud.githubusercontent.com/assets/26015152/25604610/9aaad19a-2eb9-11e7-8587-22a2fc22998d.png)

**Comment by scott-t-11** [comment]
About the only thing I can think of is to modify the styling for the display box to remove the lock/unlock icon, as that is mainly for the registration.  Otherwise, the suggested class for the styling looks good with the white text and red background.

**Comment by scott-t-11** [comment]
Just as an aside, sometimes it's more efficient to keep classes in their own files.  In the situation where you are not needing to use a class, there you can selectively not load that class.

In this situation, we are using each check each time, so I am not complaining about the classes being in one file.

The efficiency with this design is that each class inherits the swp_custom_check class, and so the code contained in that class does not need to be reloaded or repeated in the swp_php_check, swp_curl_check, or swp_wp_check.  The swp_custom_check has a parent child relationship, where as the swp_system_checker is controlling everything.   So each time the child checks are used from the system_checker up top, the custom_check is slightly optimized.  Very slight, yet enough to make object-oriented architecture worthwhile in this case, and certainly in anything more complex.
