### ISSUE TITLE
Add a custom CSS input for Click to Tweet styling.

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#364]
What do you guys think about adding a small textarea input in the settings for custom CTT styles? We've had a couple of requests for it and I think it could be really useful since the average end user doesn't really know how to add styles to a theme stylesheet.

From Nick:
I'm adding a checklist for implementation of this feature:

- [x] Create the "textarea" option type in options-page.php
- [x] Put the CSS for the textarea type into admin-options-page.css
- [x] Add the option to the options array in options-array.php
- [x] Make sure that the dependency and the dependency values are set up properly
- [x] Add the default (blank) to the defaults in options-fetch.php
- [x] Add the output to the SW header output filter. Check the dependency before output.

**Comment by Nicholas-Cardot** [comment]
Dustin, is this a feature that you'd like to see added to the plugin? I can make it so that when they select "Custom CSS" then a new field appears with a textarea for them to input their custom CSS.

**Comment by DustinWStout** [comment]
Yes, love this idea. Added to global list of feature requests.

**Comment by Nicholas-Cardot** [comment]
I'm adding a checklist for implementation of this feature:

- [ ] Create the "textarea" option type in options-page.php
- [ ] Add the option to the options array in options-array.php
- [ ] Make sure that the dependency and the dependency values are set up properly
- [ ] Add the default (blank) to the defaults in options-fetch.php
- [ ] Add the output to the SW header output filter. Check the dependency before output.

**Comment by Nicholas-Cardot** [comment]
Let's change the classes of the parent container to "sw-grid sw-col-620 sw-fit" so that it consumes the entire width of the remaining 2/3 of the space after the title.

Also, let's set the width to 96% (use the dev tools in FF to confirm if the right edge lines up fairly close to the right edge of the input box a few options above, and set the height to 120px.

**Comment by Nicholas-Cardot** [comment]
Make the HTML/CSS output only if the dependency is correct and the field is NOT an empty string. It could be possible that they set it to NONE and then add their own CSS to their theme or someplace other than our new field.

**Comment by Nicholas-Cardot** [comment]
Put this CSS ouptut function into header-meta-tags.php in pro and make it hook in the same way that the font css is hooked in in header-meta-tags.php in core. And, of course, add those dependency checks mentioned in the comment above. When checking, be sure to use the $swp_user_options global variable, not a get_option() function.
