### ISSUE TITLE
Check Flipboard API

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#365]
Flipboard is no longer allowing people to choose an image to share (iref 9722) - I'm wondering if their API has changed recently. Flipping directly from the Flipboard app or site does still provide an array of images to choose from.

**Comment by Nicholas-Cardot** [comment]
The URL parameters that we use, if I understand it correctly, only allows us to declare the URL and the title and then Flipboard should scrape the page and find everything else on their own. There really isn't a way for us to declare that stuff. I'll have to look into it further though.

**Comment by nutsandbolts** [comment]
We need to reopen this because it's still a problem - not sure why this was closed. The OG tag isn't being used to select the image, so we need to find out what they do use. See iref 13526 which I'm sending your way.

**Comment by Nicholas-Cardot** [comment]
It was closed because I can't find any documentation for how Flipboard works at all which means that there isn't anything I can do to change how shares work on that platform.
