### ISSUE TITLE
Icon and/or count widths overlap or partially hide at reduced widths

### ISSUE THREAD

**Issue by scott-t-11** [warfare-plugins/social-warfare#367]
There's a few tickets discussing hidden counts or icons when widths are low.

Resolve the problem, and, if possible, test in numerous resolutions, widths, and devices to see if the problem is repeatable in edge scenarios.

**Comment by nutsandbolts** [comment]
This can usually be resolved by removing networks so only 3-5 buttons are showing. We've had a ton of requests for separate button display for mobile vs. desktop - definitely something we should consider.

**Comment by scott-t-11** [comment]
My general strategy for mobile vs desktop involves varying how the layout, size, and other styling displays at different widths.

In this case, the differences are not only with the width of the device, also the amount of networks.

I've been experimenting on a solution that will display more of the networks at reduced widths.  My goal has been to have it adapting to the widths, and also work with many more networks.

Once this is ready, I'll send a link which you can test the idea at various widths.

For any features, we could consider giving an option for customers to choose, so if someone likes something they can enable it, if they dislike something, they can disable it.

The current progress on this item involves changes to the styling and testing on one browser/device.  My goal is to test on more devices before I commit a change.

I'm prioritizing getting this and other near finished changes in so you all can see solutions.

**Comment by scott-t-11** [comment]
![oldiconwidth](https://cloud.githubusercontent.com/assets/26015152/25602836/bd0a7154-2eab-11e7-95c9-514814cd196a.JPG)
Shows how a min width would look.
![iconwidths](https://cloud.githubusercontent.com/assets/26015152/25602837/bd0c1306-2eab-11e7-94ab-0efa4894dce6.JPG)
Shows how the widths get on low width screens (it tested ok on mobile, this is with a thin browser)

**Comment by scott-t-11** [comment]
My thoughts are to give it a double row or a five wide per row when it goes into lower widths.  So if it's running out of room, I can set it to drop down to show another row with 5 networks per row (Andrea said over 5 networks is when customers might experience problems with partial visibility)

We might be able to ultimately give customers an option to select dimensions and behavior, such as columns and rows, or even behavioral options.

Anyways, I've spent so much time in the code for this, mostly figuring out how the flexslider works and where all the code is, that if that appears to be a good idea, I can go with multiple rows

**Comment by scott-t-11** [comment]
And we'll need to figure out a way to increase the space so that lower widths don't prevent flexing, as it appears to at very low widths.  This is one reason I don't want to commit other changes, as these changes aren't yet perfectly adapted to all widths.
