### ISSUE TITLE
Foreach throwing warning when supplied with non-array

### ISSUE THREAD

**Issue by TheLastTech** [warfare-plugins/social-warfare#374]
[Mon May 08 00:09:32.387910 2017] [:error] [pid  ] [client ] PHP Warning:  Invalid argument supplied for foreach() in /functions/curl_functions.php on line 21.

can you update the code so it does't emit this warning? 

if(is_array($WHATEVER)) before the foreach

**Comment by Nicholas-Cardot** [comment]
A problem with a solution provided? You make this too easy. Good catch. You need to hang out here more often. :-)

I'll knock this out first thing Monday. We have a release scheduled for tomorrow afternoon so this will be included with that release.

**Comment by Nicholas-Cardot** [comment]
This is now fixed.
