### ISSUE TITLE
The totes field doesn't account for recovery

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#387]
I just noticed today that, when share recovery is active and has recovered shares, the "totes" custom field doesn't update to match. The total count on the buttons will show the recovered total, but the popular posts widget and total shares shortcode still reflect the original count without recovered shares added in. This prevents the widget and total shares from updating to match the button total.

**Comment by Nicholas-Cardot** [comment]
I wonder if this is some sort of a caching issue, because I just looked at the recovery logic, and it definitely dumps it into the totes field before the end of the function.

**Comment by nutsandbolts** [comment]
Could be, but the recovered ones I had were posts from 2013 that haven't been touched in ages, so it should have grabbed those forever ago. It's not like they were recently recovered or anything - I've had recovery active on the site for as long as it's been part of the plugin.
