### ISSUE TITLE
Pinterest is counting URLs with UTM tracking as separate URLs

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#391]
Ran these two URLs (same post) through the Pinterest API with different results for the one with UTM tracking:

https://www.goodenufmommy.com/2017/06/how-to-survive-the-end-of-the-school-year.html

https://www.goodenufmommy.com/2017/06/how-to-survive-the-end-of-the-school-year.html?utm_source=pinterest&utm_medium=social&utm_campaign=SocialWarfare

I'm not sure if this only happens when the permalinks have .html on the end or if it's universal.

**Comment by Nicholas-Cardot** [comment]
I don't think there's anything we can do about this. This is just how Pinterest counts shares.

**Comment by nutsandbolts** [comment]
Can we maybe set the Pinterest button so that, if UTM tracking is enabled, the UTM URL is the one used to hit the API for counts? Or somehow add those together? That's a huge problem for people who have tons of shares but only on one or the other.

**Comment by DustinWStout** [comment]
If it's possible for us to ping the Pinterest API for both versions of the URL (which seems reasonable and not outside the scope of what we're already doing with Share Recovery) then I think we should be able to count both.

**Comment by Nicholas-Cardot** [comment]
Yeah, but just keep in mind that if we do that, we'll be sending 4 API requests for just one network.

**Comment by nutsandbolts** [comment]
Can we do it ONLY if UTM tracking is on? Seems like that would save effort for the people who don't need it, but it's a huge deal - some people are missing thousands of counts because of this.

**Comment by Nicholas-Cardot** [comment]
We added an option so people can specifically decide whether or not to use UTM on Pinterest links. It's not efficient to add more API calls so I think this is the best case scenario for now.
