### ISSUE TITLE
Pinterest image issues with AMP

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#399]
I know AMP support isn't part of the plugin yet but wanted to mention that the hidden Pinterest image is visible (and gigantic) for sites with AMP enabled. Also the Pinterest image isn't available as a choice to pin when viewing the AMP version of the articles. So just some general notes for things to check/test when it's added.

**Comment by DustinWStout** [comment]
Added to global feature request list.

**Comment by ckmahoney** [comment]
I just found this on the Wislist #392  and think that it should actually be removed. Do we still see problems with the OP?

**Comment by nutsandbolts** [comment]
This is still a problem, yes. We haven’t addressed AMP whatsoever.
