### ISSUE TITLE
Buttons not displaying on certain pages or custom post types

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#4]
We are tracking some occurances where despite having the display settings configured properly, the buttons are not showing up on certain pages or post types.

**Comment by Nicholas-Cardot** [comment]
This issue needs more information.

Are you talking about the static horizontal buttons? The left floating buttons?
Is this a repeat of #18 is now therefor fixed?
What specific custom post types are they not displaying on? Were they turned on for that Post Type in the "Display Locations" tab of the settings page?
