### ISSUE TITLE
Disable Pinit Button for Image Links / New Pinit Button Display Option

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#405]
# // **Notes for Testers** 

It is pretty common for an image to be a link. For example, a WooCommerce category page will have many products. Each image is a link to the product page. We want admins to choose whether images like this have a "Save" button or not. 

### What we want to happen: 
If "Hide on Anchors" is on, no "Save" button shows up when hovering an image-link. 
If it is off, then we treat the image the same as all other images. 

### How to test: 
0. Create an image that is also a link. An outline of the HTML might look like:

```
<a href="/category/shoes/summer-flipflops">
  <img src="/shoes/summer-flipflops" />
</a>
```

In Social Warfare -> Display -> Image Hover Pin Button :

1. Make sure "PinIt Button" is ON.
2. Make sure "Hide on Anchors (links)" is ON.
3. Visit the blog post with the image-link. Hover the image, and no "Save" button should show up.
4. Turn "Hide on Anchors" OFF.
5. Click "Save Settings"
6. Visit the blog post with the image-link. Hover the image, and a "Save" button should show up.

If everything goes as described, hooray! We are good to go. 
If something is contrary to what we describe, please let us know in a comment to this issue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

The Pinit button obstructs some ad network images and ad network image overlays. One such network that suffers this is Shoppable.

I can fix it with CSS with, for example,

```
.sw-pinit.curalate-widget-image,
.curalate-widget-processed .sw-pinit-button {
  display:none!important;
}
```

I think a better solution would be to add options to Social Warfare to either,

- Disable Pinit on images used as buttons/link anchors, and/or
- Display Pinit button outside of the image area e.g. above, left, right or below it.

Is there any chance of these changes being implemented?

**Comment by DustinWStout** [comment]
Have you tried the option that limits the Pinit button to only apply to images that meet minimum size/height requirements?

**Comment by VR51** [comment]
I missed this reply. Sorry @DustinWStout. We use the min width/height setting but these images are full-width so that won't work in this case.

**Comment by DustinWStout** [comment]
@VR51 ah, I see. I'll add this to our list of feature requests.

**Comment by DustinWStout** [comment]
Added to global feature requests list.

**Comment by Nicholas-Cardot** [comment]
We just need to add an option to the options page and if enabled, have the JS check for an <a> ancestor to the image before adding the button.

**Comment by ckmahoney** [comment]
As in, the admin provides a CSS selector to ignore?

**Comment by Nicholas-Cardot** [comment]
No, target <a> anchor tags. And make the option something like "Disable On Links"

**Comment by ckmahoney** [comment]
This item is ready for review and testing.

**Comment by JasonWiser** [comment]
tested. works
