### ISSUE TITLE
Pinterest Black Screen

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#407]
Getting reports of Pinterest shares leading to a black screen. The user is unable to share to Pinterest when it shows.

Strangely, this does not happen for all visitors.

- It is known to happen to some/most/all Windows and Mac system users but not Linux systems.
- Browser add-ons are apparently not the cause. My Windows/Mac visitors tested the button with different browsers on different machines both with and without add-ons. The black screen showed in all their browsers.

I use Linux. Tested with Linux using Opera VPN through Netherlands, Canada and US. Non VPN from both UK. Works fine for me in Linux.

I'm awaiting feedback regarding installed antivirus plugins that might interfere with the Pinterest button.

**Comment by nutsandbolts** [comment]
Sorry for the delayed response on this - this was a partial Pinterest outage that affected many social sharing plugins last weekend. It was resolved late Sunday night and should be good to go now - Pinterest is making some changes but we haven't been advised of what they are.

**Comment by VR51** [comment]
No worries about the delayed response. Everyone seems to have slowed down the past few weeks, including me :-) Thanks for your reply, @nutsandbolts.

**Comment by nutsandbolts** [comment]
Very true! I guess everyone is trying to get things done before fall and winter get here - it's been a ghost town in our help desk this week. (Probably just ruined it by saying so) :)
