### ISSUE TITLE
Make Horizontal float buttons display without static buttons present.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#41]
The bottom floating buttons require at least one iteration of the static horizontal buttons. This is because we have no idea how wide your content area is, so we literally create the regular set and then clone that set to the bottom.

However, some users would like to be able to turn on the floating buttons without having the static buttons on the page. We currently have this setup to work for the left floating buttons. Now I need to make it work for the top and bottom floating buttons as well.

**Comment by DustinWStout** [comment]
Isn't this already done?
