### ISSUE TITLE
Admin notice for downgraded accounts

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#412]
(iref.12464)
> Please add a close box to toggle off the message for former pro users that have downgraded to the free version. 
>
> "Important: We’ve made some changes to how your Social Warfare premium license is applied. In order to continue getting all the Pro features you love, please download the Social Warfare - Pro plugin. Once installed, all of your premium features will be immediately restored."
>
> If you want to keep it on people's radar, you can add something to the Social Warfare settings page. But it does not need to be at the top of every single page in the admin.

**Comment by Nicholas-Cardot** [comment]
This is fixed.
