### ISSUE TITLE
Share counts + icon on mobile bug

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#413]
In mobile (iOS) Safari and Chrome, the share counts overlap the icons when they should be hidden. 

![image uploaded from ios](https://user-images.githubusercontent.com/2152604/29628645-fab7a81c-87ea-11e7-8860-aa997c626864.jpg)

**Comment by ckmahoney** [comment]
I am no longer able to replicate this. 

The issue is over a year old; it may already be fixed.

**Comment by Nicholas-Cardot** [comment]
This is now resolved.
