### ISSUE TITLE
Tab CSS to conflict with other admin screens

### ISSUE THREAD

**Issue by xlplugins** [warfare-plugins/social-warfare#415]
Hi, 

I have found that your plugin's CSS is not restricted only to your admin pages. 

Here is the screenshot of tabs getting distorted by CSS of your plugin.

http://i.imgur.com/E6B4pHQ.png || http://i.imgur.com/k5p3BhT.png

Kindly restrict the CSS to not apply to other jQuery tabs in your next update. 

Thank You

**Comment by Nicholas-Cardot** [comment]
Can you show me the address bar of the browser? I thought I had that CSS set to only show up on the post editor for the post options. I'm wondering if whatever that plugin is that you've screenshoted is using some sort of a custom post type or something.

**Comment by xlplugins** [comment]
Hi, 
`add_action( 'admin_enqueue_scripts', 'enqueueSocialWarfareAdminScripts' );

/**
 * Load admin scripts and styles.
 *
 * @since  1.0.0
 * @access public
 * @param  string $screen The ID of the current admin screen.
 * @return void
 */
function enqueueSocialWarfareAdminScripts( $screen ) {
/**
	$screens = array(
		'toplevel_page_social-warfare',
		'post.php',
		'post-new.php',
	);

	if ( ! in_array( $screen, $screens, true ) ) {
		return;
	}
*/
	enqueueSocialWarfareScripts();

	$suffix = swp_get_suffix();

	wp_enqueue_style(
		'social_warfare_admin',
		SWP_PLUGIN_URL . "/css/admin{$suffix}.css",
		array(),
		SWP_VERSION
	);

	wp_enqueue_script(
		'social_warfare_admin_script',
		SWP_PLUGIN_URL . "/js/admin{$suffix}.js",
		array( 'jquery' ),
		SWP_VERSION
	);

	wp_localize_script( 'social_warfare_admin_script', 'swp_localize_admin',
		array(
			'swp_characters_remaining' => __( 'Characters Remaining', 'social-warfare' ),
		)
	);
}`

This is the code which I found written in scripts.php file in your plugin, Yes we have a custom post type and we are using default jquery-ui tabs. 

What I think is, the CSS should be written with a custom tab content wrapper but not for ui-tabs.

Thanks!

**Comment by Nicholas-Cardot** [comment]
Agree. I just need to add the proper specificity selector to limit our CSS to our fields.

**Comment by Nicholas-Cardot** [comment]
This is now fixed.
