### ISSUE TITLE
Error on Registration

### ISSUE THREAD

**Issue by cinghaman** [warfare-plugins/social-warfare#416]
Hi,

Getting error on Registration
PHP Fatal error:  Uncaught Error: Call to undefined function swp_get_registration_api() in /dom18053/wp-content/plugins/social-warfare-pro/functions/admin/registration.php:293
Stack trace:
#0 /dom18053/wp-content/plugins/social-warfare-pro/functions/admin/registration.php(343): swp_check_registration_status()
#1 /wordpress-4.8.1/wp-includes/class-wp-hook.php(298): swp_check_license('')
#2 /wordpress-4.8.1/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress-4.8.1/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /wordpress-4.8.1/wp-admin/admin-ajax.php(44): do_action('admin_init')

And if I don't disable the plugin I get 503.

**Comment by Nicholas-Cardot** [comment]
All of these registration errors are now fixed and will be a part of the next release.
