### ISSUE TITLE
Image hover Pin button refinements

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#418]
The button on images needs some refinements: 

- [ ] It's styling is too big and inconsistent with our other buttons, we need to make it feel more uniform/consistent with the rest of the Social Warfare button styling
- [ ] On hover state, the word "Save" disappears, but the Pin icon still floats to the left and looks awkward. Maybe we should just keep "Save" visible on hover?

**Comment by Nicholas-Cardot** [comment]
Yeah, save is supposed to remain visible, that's a bug, I think. Can you sketch something for me in Illustrator that I can use as a blueprint for these refinements?

**Comment by DustinWStout** [comment]
Don't need to sketch anything up--just make it the same size/shape as the Flat/Fresh style buttons.

**Comment by Nicholas-Cardot** [comment]
Dustin, please review the modifications I've made here and let me know if anything further needs adjusted. I think I got it to match pretty closely, but I'll wait until I have confirmation from you.

https://beta.warfareplugins.com/this-is-a-test-post/

**Comment by DustinWStout** [comment]
There's a `padding: 0 30px;` that could be reduced to `padding: 0 20px;` and would look just a smidge better. I think that would do it.
