### ISSUE TITLE
i seem to be having an issue with socialwarfare plugin displaying odd characters in my website header

### ISSUE THREAD

**Issue by alidixon03** [warfare-plugins/social-warfare#419]
Hi all,

The issue can be seen on all 'post' pages. for example: 

https://www.trailandkale.com/adventures/running-the-routeburn-track/

you can see the characters: "" />" being displayed in the top left. If i disable the plugin, the problem goes away..

Best,

Alastair

**Comment by Nicholas-Cardot** [comment]
This issue has already been fixed. Please ensure that you are updated to version 2.3.2. If you do have further questions, please email info@warfareplugins.com to get fast and helpful assistance.

**Comment by alidixon03** [comment]
Hi Nicholas,
I am on v2.3.2...
