### ISSUE TITLE
jQuery in footer

### ISSUE THREAD

**Issue by richardracko** [warfare-plugins/social-warfare#422]
Hi,

we wanted to enable defer JS loading on our sites via WP Rocket plugin.

There is an issue with inline script in footer, as it's calling jQuery and it's not loaded yet, it produces JavaScript error:
https://github.com/warfare-plugins/social-warfare/blob/master/functions/utilities/share-cache.php#L399

Could you please use wp_localize_script instead or make the action independent from jQuery using:
`document.addEventListener('DOMContentLoaded', function() {`
 Of course in the callback there can be jQuery.

Thanks,
Richard

**Comment by Nicholas-Cardot** [comment]
No. Unfortunately we cannot and will not support deferring javascript files past the DOM loaded event as that is simply a bad practice all around.

**Comment by foliovision** [comment]
Hello Nicholas,

we are not talking about deferring JavaScript past the DOM loaded event is some artificial way, it's just the <script defer> attribute. The way you use `jQuery( document ).ready( function() {` makes it impossible to defer the load of jQuery.

Please let us know if we are on the same page here.

Thanks,
Martin

**Comment by Nicholas-Cardot** [comment]
Okay, so you're not talking about using a script tag to load the JS files after the DOM Load, you're saying that they are indeed available when the DOM Loaded event fires off?

**Comment by foliovision** [comment]
Hello Nicholas,

yes, on DOMContentLoaded jQuery is available.

Thanks,
Martin

**Comment by foliovision** [comment]
Hello Nicholas,

we also see this error:

`Uncaught ReferenceError: socialWarfarePlugin is not defined
    at (index):556`

You can check it on https://foliovision.com/player/ 

```
<script type="text/javascript"> swpPinIt={"enabled":false};var swpClickTracking = true; var swp_nonce = "449943f9c1";
  var swp_buttons_exist = !!document.getElementsByClassName( 'nc_socialPanel' );
  if ( swp_buttons_exist ) {
  swp_admin_ajax = 'https://foliovision.com/site/wp-admin/admin-ajax.php';
  swp_post_id='414';
  swp_post_url='https://foliovision.com/player';
  swp_post_recovery_url = 'https://foliovision.com/2009/09/player';
  socialWarfarePlugin.fetchShares();
}
</script>
```

Could you please simply make that wait for document DOMContentLoaded or load these variables into JS via wp_localize_script() and run that function from one of the .js files of your plugin?

Thanks,
Martin

**Comment by foliovision** [comment]
Hi Nicholas,

Not having this issues fixed is giving us a lot of trouble optimising our clients' sites for PageSpeed. As you know load speed is crucial to decent rankings in Google. What sense does it make to have a social media plugin which means your site ranks much lower in Google? Not much is the correct answer.

If you won't fix this issue, we'll want a pro-rate refund on our 15 licenses and look elsewhere for software which doesn't break or slow our clients' websites.

No one here is going to be very happy, as we've spent a lot of time and money implementing Social Warfare.

Thanks for paying attention this time.

**Comment by Nicholas-Cardot** [comment]
Wait, nevermind, I see what line you're talking about.

**Comment by Nicholas-Cardot** [comment]
Okay, I've made these adjustments. You should be able to download the current version here on GitHub to test it out. Don't forget to remove -master from the zip file name and from the folder inside the zip. Change social-warfare-master.zip to social-warfare.zip and the same with the folder inside the zip.

**Comment by richardracko** [comment]
Hi Nicholas,

these fixes helped, but I realized that same fix is needed for legacy method of fetching shares.

Also I've noticed that condition on [line 370](https://github.com/warfare-plugins/social-warfare/blob/a0bec8d1a955b940f143484848661214280b0720/functions/utilities/share-cache.php#L370) and [401](https://github.com/warfare-plugins/social-warfare/blob/a0bec8d1a955b940f143484848661214280b0720/functions/utilities/share-cache.php#L401) isn't **checking existence of sharing buttons** correctly and **returning true all the time**.

It could be fixed simply by modifying the **swp_buttons_exist** variable:
`var swp_buttons_exist = (document.getElementsByClassName( 'nc_socialPanel' ).length > 0);`

I've created pull request with all these changes: https://github.com/warfare-plugins/social-warfare/pull/423

Thanks,
Richard

**Comment by Nicholas-Cardot** [comment]
Very cool. I just merged it in. Thanks for that!

**Comment by foliovision** [comment]
Hello Nicholas,

thank you, the new version works.

Thanks,
Martin

**Comment by haydenjames** [comment]
I get: Uncaught ReferenceError: socialWarfarePlugin is not defined

What .js file is this from so I can try to exclude from wp-rocket?  thanks

**Comment by Nicholas-Cardot** [comment]
@haydenjames You want to exclude /wp-content/plugins/social-warfare/js/script.min.js

That should do the trick for you.
