### ISSUE TITLE
filter to change site url

### ISSUE THREAD

**Issue by JiveDig** [warfare-plugins/social-warfare#426]
I'm thinking a filter on `$url` here https://github.com/warfare-plugins/social-warfare/blob/master/functions/utilities/share-count-function.php#L15 would be great.

When working on a staging site it would be great to see pull the share counts from the live site posts urls.

I do this already via EA Share Counts plugin here https://github.com/jaredatch/EA-Share-Count#customization. `ea_share_count_site_url` is a super powerful feature for this situation. 

Maybe there is another way that I'm missing though?

**Comment by Nicholas-Cardot** [comment]
So let me clarify to see if I understand what you're asking:

You want me to replace:
`$url = get_permalink( $postID );`

with something like:
```
$url = get_permalink( $postID );
$url = apply_filters( 'swp_url_filter_function' , $url );
```

So that you can write a function on your staging site like this:

```
add_filter( 'swp_url_filter_function' , 'my_social_url_filter' );
function my_social_url_filter($url) {
    // Modify the URL somehow here
    return $url;
}
```

**Comment by JiveDig** [comment]
Correct. I'm somewhat new to Social Warfare (first time trying it in a couple years?). The live site has a ton of shares, but doesn't use Social Warfare. We're rebuilding on staging and I want to use SW, but the share counts are empty. I'm building a "trending posts" type thing, but I have no counts to play with. Does that make sense?

**Comment by Nicholas-Cardot** [comment]
One minute. I'm going to push this change onto GitHub so you can take a copy from here and test to see if it properly meets your needs in this situation.

**Comment by Nicholas-Cardot** [comment]
Okay. I just committed it to GitHub. You can download a new copy of the free version from here and test it out. 

Keep in mind that when you download from GitHub, both the zip and the folder inside the zip will be named social-warfare-master. So be sure to rename the zip and that folder to just social-warfare (removing the -master) before installing.

I hope this helps!

**Comment by JiveDig** [comment]
Okay, it seems to work. I had to use `str_replace` to change the base url, but it works.
I haven't dug into it much, but I wonder how EA allows you to filter only the base and build the full url from that https://github.com/jaredatch/EA-Share-Count/blob/master/includes/class-core.php#L103

**Comment by Nicholas-Cardot** [comment]
I assumed that you would have to use the string replace function in PHP. But, I mean if you're writing a filter function anyways, it's only 1 line of code with a find, a replace, and a haystack,, yeah?

**Comment by JiveDig** [comment]
Yep, not a lot of code and works if that's the most fitting place to allow this functionality. I'm cool with it.

**Comment by Nicholas-Cardot** [comment]
Sweet

**Comment by JiveDig** [comment]
Thanks!
