### ISSUE TITLE
HTML injections on Social Identity page

### ISSUE THREAD

**Issue by AndreyMZ** [warfare-plugins/social-warfare#427]
### Problem description
HTML injections on page `/wp-admin/admin.php?page=social-warfare`.

### Steps to reproduce
1. Log in to WordPress as admin.
2. Go to *Social Warfare* > *Social Identity*.
3. Set *Twitter Username* to `FOO1"><img src="x" onerror="alert(1)" bar="baz`.
4. Set *Pinterest Username* to `FOO2"><img src="x" onerror="alert(2)" bar="baz`.
5. Set *Facebook Page URL* to `FOO3"><img src="x" onerror="alert(3)" bar="baz`.
6. Set *Facebook App ID* to `FOO4"><img src="x" onerror="alert(4)" bar="baz`.
7. Click *Save Changes*.
8. Refresh the page.

### Actual result
Alert messages `1`, `2`, `3`, and `4` are shown.
- *Twitter Username* is displayed as `FOO1`.
- *Pinterest Username* is displayed as `FOO2`.
- *Facebook Page URL* is displayed as `FOO3`.
- *Facebook App ID* is displayed as `FOO4`.

### Expected result
There are no alert messages.
- *Twitter Username* is displayed as `FOO1"><img src="x" onerror="alert(1)" bar="baz`.
- *Pinterest Username* is displayed as `FOO2"><img src="x" onerror="alert(2)" bar="baz`.
- *Facebook Page URL* is displayed as `FOO3"><img src="x" onerror="alert(3)" bar="baz`.
- *Facebook App ID* is displayed as `FOO4"><img src="x" onerror="alert(4)" bar="baz`.

**Comment by Nicholas-Cardot** [comment]
Can you elaborate a bit more on this? I'm not sure exactly what you're asking for here.

**Comment by AndreyMZ** [comment]
I have reported a bug. I hope it will be fixed somewhen.

**Comment by VR51** [comment]
I think the actual result is the expected result.

Social Warefare updates usermeta via the social profile fields function [swp_save_user_profile_fields()](https://github.com/warfare-plugins/social-warfare/blob/1204008eb0571ecd4db74cb4205b0b0296708013/functions/admin/profile-fields.php), which uses the WordPress function update_user_meta(), as seen [here](https://github.com/warfare-plugins/social-warfare/blob/1204008eb0571ecd4db74cb4205b0b0296708013/functions/admin/profile-fields.php).

The function [update_user_meta()](https://codex.wordpress.org/Function_Reference/update_user_meta) uses [update_metadata()](https://developer.wordpress.org/reference/functions/update_metadata/) which both validates and sanitises input.

HTML added into user meta fields is deliberately removed by WordPress to prevent code injection. Social Warfare works as expected.

You can read more about data sanitation and data validation here https://code.tutsplus.com/articles/data-sanitization-and-validation-with-wordpress--wp-25536

**Comment by Nicholas-Cardot** [comment]
@VR51 Yes, exactly. Thank you for clarifying that.
