### ISSUE TITLE
Missing translation functions

### ISSUE THREAD

**Issue by wpmarmite** [warfare-plugins/social-warfare#428]
Hey everyone !

I would like to report missing translations in the Social Warfare widget (/functions/widgets/widgets.php). I18n functions aren't used.

That's not a big deal because we can edit it in the widget settings but I just wanted to let you know :)

**Comment by Nicholas-Cardot** [comment]
I'm not sure what the purpose of an i18 function is when it's an editable field?

**Comment by Nicholas-Cardot** [comment]
Or do you mean the field descriptions/labels?

**Comment by wpmarmite** [comment]
Hey Nicholas, I mean that default values aren't translated. It's possible to edit it but I just wanted to notice it :)

**Comment by Nicholas-Cardot** [comment]
@wpmarmite Yeah, generally I don't think I've translated anything that is fillable since you can literally put anything you want into the value directly through the options.
