### ISSUE TITLE
Widget form PHP notices

### ISSUE THREAD

**Issue by robincornett** [warfare-plugins/social-warfare#429]
The [foreach loop going through the available networks on the widgets page](https://github.com/warfare-plugins/social-warfare/blob/master/functions/widgets/widgets.php#L100) is throwing some PHP notices:

```
Undefined index: facebook | 2 | local.content.dev/plugins/social-warfare/functions/widgets/widgets.php:100
```

If the line is changed to check if the key is set **and** that it exists, the notices are resolved for me:

```
if ( isset( $options[ $key ] ) && $options[ $key ] ) {
```

Note: I am testing this locally and have very minimal settings configured, so it may be that some configuration is missing, but the notices relate to the three networks I have selected to show, so I think it's as configured as it needs to be for this form.

**Comment by Nicholas-Cardot** [comment]
Is that possibly redundant? Wouldn't isset() by itself be enough?

**Comment by robincornett** [comment]
Depending on how the `$options` array is built, not necessarily. It could be possible to have a key set, but with no value, or the value set to false. Doing a check for both is more bulletproof. (I believe that checking for `! empty()` will do the same but be less verbose, but didn't test that here).

**Comment by Nicholas-Cardot** [comment]
This will be fixed in our next release.
