### ISSUE TITLE
Prevent pro features and customizations from persisting when the Pro Addon is deactivated, deleted or unregistered.

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#431]
We need to set the core plugin to reset the styles when the Pro addon is removed or deactivated. Right now the settings persist with no way for the user to change them back to the regular styles/colors.

**Comment by Nicholas-Cardot** [comment]
Make sure that we don't miss any items in the array on options-fetch.php. That should fix this.

**Comment by Nicholas-Cardot** [comment]
This should now be fixed with the new options class framework.
