### ISSUE TITLE
Ensure all custom post types are showing in the "Position Share Buttons" display section or default to off.

### ISSUE THREAD

**Issue by Protohominid** [warfare-plugins/social-warfare#432]
I submitted a ticket to your website on this and it was forwarded to a developer. I supplied an admin account on our site to investigate, but I never heard back, so I'm posting this here to get things moving.

The share buttons are showing in spots where they shouldn't, and I'm assuming it's because we have some custom post types that aren't being recognized by the display settings section of the plugin. For example, we are using the "Text Blocks" plugin...

<img width="360" alt="screen shot 2018-01-19 at 2 08 53 pm" src="https://user-images.githubusercontent.com/1683584/35169493-57915bbc-fd22-11e7-890a-1d5e2cba5b12.png">

...and the share buttons are being inserted after every instance of a text block on the front end.

<img width="801" alt="screen shot 2018-01-19 at 2 10 06 pm" src="https://user-images.githubusercontent.com/1683584/35169538-81dd575e-fd22-11e7-9aa5-1a1b827c7b0e.png">

 That CPT ('text-blocks') isn't showing as an option in SW settings to turn it off.

<img width="738" alt="screen shot 2018-01-19 at 2 11 06 pm" src="https://user-images.githubusercontent.com/1683584/35169568-9fc3896e-fd22-11e7-83fd-ae4e1bd98688.png">

There's another CPT associated with the Toolset Types & Views plugin that is a problem as well.

**Comment by Nicholas-Cardot** [comment]
Initial thoughts are that they are possibly private post types or the post types and our options are loading in a non-optimal order.

**Comment by Nicholas-Cardot** [comment]
This should now be fixred.

**Comment by Protohominid** [comment]
The Text Blocks post type is still not showing for me
