### ISSUE TITLE
Make the network selection in the settings accessible for people using screen readers.

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#435]
A customer who relies on a screen reader mentioned that the drag and drop for the buttons doesn't identify which buttons are which when choosing inactive vs. active. He had to get assistance from someone to know which buttons he was activating. We need to get this fixed - that's a huge issue for people who are visually impaired.

This can be tested with JAWS for Windows (version 17) with IE, Chrome, and Firefox.

**Comment by Nicholas-Cardot** [comment]
Change the aria-label for Google Plus and Hacker News to two separate words as they are spelled at the beginning of this sentence. Capitalize all appropriate letters in the additional labels (e.g. LinkedIn, Twitter, Google Plus).

**Comment by Nicholas-Cardot** [comment]
Make sure they all have a title and an aria-label and then we'll call this one good.
