### ISSUE TITLE
Add a toggle to disable the OG output.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#436]
- [x] Add to options page
- [x] Add to options defaults array
- [x] Add conditional to header-metatags.php
- [x] Make sure default is set to on for pro / off for core
- [x] See comment below regarding title and description.

**Comment by ckmahoney** [comment]
Finished and closing with commit 086dfde

**Comment by Nicholas-Cardot** [comment]
Let's change the title and description to the following:

Title: Meta Tags
Description: Open Graph meta tags and Twitter Cards are the standard for defining which title, image, and description get posted when a share is made.
