### ISSUE TITLE
Add data-pin-description="" to all images in the post content.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#441]
# // **Notes for Testers** 

### What we want to happen: 
When editing a post, you insert an image using the "Add Media" button. The image gets an extra attribute, `data-pin-description="some description"`, added to its markup for display on the server. 

### How to test: 
In Admin: 

In Settings -> Advanced -> Advanced Pinterest Settings,
Find "Description Source" 
Please test first using "Image ALT text".
Then test using "Custom Pin Description". 

Go to the post editor for any page or post. 
Click on "Add Media".
Select an image you would like to use. There are two paths to test:  
  1) With the Social Warfare Pinterest description left blank
  2) Entering a value for the SW Pinterest description
Click "Insert Into Post".

Then, view the post on the front end. 
Using the dev tools, inspect the image. 
The `<img>` tag  should have an attribute `data-pin-description`. 

For path 1:
  If "Description Source" is "Image ALT text", it should be the same as the Alt text.
  Else it is "Custom Pin Description", and it should be the same as what is in the Post Metabox.

For path 2:
  The value should be the exact same description you entered in the image's Pinterest Description Field.

If everything is good, hooray! That's good. 
If anything seems out of place or does not go as expected, please add a comment to this thread  so we can jump on it. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#
This may need us to output the description into a javascript variable and then use that to dynamically add the tag to all the images unless there is a convenient way to filter all the img elements in the post content on the server side with something more reliable than just some sort of a regular expression matching and replacing. 

- [x] Add a Pinterest Description field to the media upload and media edit forms
- [x] Output the per image description (first priority) or the post pinterest description (second priority) to the images in the post.
- [x] Add a checkbox to the main options page which when activated with allow the above two functions to kick in.

This should provide much better support for browser extensions such as the native Pinterest extension, Tailwind, and others.

**Comment by DustinWStout** [comment]
Instead of doing this via Javascript, I think the better route is to add a text field to the WordPress media uploader called "Pinterest Description". This way the pin description is attached to the image in the wp media library and whenever a user selects that image to place it in a post, the pin description automatically comes along with it.

**Comment by Nicholas-Cardot** [comment]
I think the best route is to do both. Many users will not want to have to go back through their past 5 years worth of posts and add a Pinterest description to every single image in all of those posts. So instead, we'll use the post Pinterest descriptions as a default for all images on the post unless they fill out the media pinterest description that you mentioned @DustinWStout in which case we will then use that per image description.

**Comment by nutsandbolts** [comment]
Will this be an option? I can imagine some people won't want to do either of these, especially if they've carefully filled out something else to serve as the description.

**Comment by Nicholas-Cardot** [comment]
What do you mean by filled out something else? Do you mean like the alt tag or something?

**Comment by nutsandbolts** [comment]
Yes, which of course isn't the best way to do that, but some people have done it that way for years and use that field to enter different descriptions for different images.

**Comment by Nicholas-Cardot** [comment]
So what do you suppose is the best way to reconcile these various approaches?

**Comment by nutsandbolts** [comment]
I think we need another advanced Pinterest option that says something like "Per-image descriptions" and let people choose either "Use my Pinterest description" or "Don't set one" or something.

**Comment by DustinWStout** [comment]
@nutsandbolts less options... we choose for them...

- IF single image Pinterest description is set, overwrite post-level Pinterest Description for that in-post image only
- IF no single image Pinterest description is set, use post-level Pinterest Description
- IF no post-level Pinterest description is set, use alt text
- IF no alt text is found, use excerpt (?)
- IF nothing is found, use post title

**Comment by nutsandbolts** [comment]
So maybe a global on/off for this - if turned off (not the default) it skips the second part and goes straight to the alt text? Because some people have literally thousands of posts using the alt text for their in-post images and I hate the thought of angering them.

**Comment by nutsandbolts** [comment]
Just wanted to see where we are on this and whether we can get it done before the next update - several customers are VERY invested in seeing this ASAP.

**Comment by ckmahoney** [comment]
Dustin's outline of description priority makes sense. Is that the direction we would like to go? Copied here. 

```
IF single image Pinterest description is set, 
    overwrite post-level Pinterest Description for that in-post image only

IF no single image Pinterest description is set, 
    use post-level Pinterest Description

IF no post-level Pinterest description is set, 
    use alt text

IF no alt text is found, 
    use excerpt (?)

IF nothing is found, 
    use post title
```

**Comment by Nicholas-Cardot** [comment]
Yes, but right now, we don't have any way to set the "single image Pinterest description"

**Comment by Nicholas-Cardot** [comment]
So we need to add that first. Once that is added, then that flow of logic will be just fine.

**Comment by ckmahoney** [comment]
I started working on that this morning. This code came from somewhere on SO: 

```
    protected function edit_media_custom_field( $form_fields, $post ) {
        $form_fields['swp_pinterest_image_description'] = array(
            'label' => 'Social Warafre Pin Description',
            'input' => 'textarea',
            'value' => get_post_meta( $post->ID, '_swp_pinterest_image_description', true )
        );
        return $form_fields;
    }

    protected function save_media_custom_field( $post, $attachment ) {
        update_post_meta( $post['ID'], '_swp_pinterest_description', $attachment['swp_pinterest_image_description'] );
        return $post;
    }

    protected function add_pinterest_description_field() {
        add_filter('attachment_fields_to_edit', array($this, 'edit_media_custom_field', 11, 2 ) );
        add_filter('attachment_fields_to_save', array($this, 'save_media_custom_field', 11, 2 ) );
    }
```

**Comment by ckmahoney** [comment]
It adds the Social Warfare Pinterest Description field to an image, below the alt text field.

**Comment by Nicholas-Cardot** [comment]
Okay, perfect. Then proceed in accordance with Dustin's flow of control model.

**Comment by ckmahoney** [comment]
The tricky thing is where to put it. 

It made the most sense to add it in the Pinterest class. But the class is initialized too late to reach those hooks. 
Then I tried putting it in the Pro main class, since this would be a Pro feature. But that also fired too late. 

Finally, I was able to see the new field displayed when I put it in the core main file. But that is not a good place for it. 
Thoughts @Nicholas-Cardot ?

**Comment by Nicholas-Cardot** [comment]
So is there any kind of a hook that can be used to pull that data and filter the image output?

We may have to go in through the_content() hook or something, but if they make it able to add data to images, then there should be some mechanism that we can use to filter those images, pull that data, and stuff it into a data-pin-description attribute.

I'm looking into it now.

**Comment by ckmahoney** [comment]
My guess is that it gets stored as a custom field in the attachment's post meta. We'd have to fetch that later with get_post_meta if that is the option the user has set.

**Comment by Nicholas-Cardot** [comment]
https://stackoverflow.com/questions/19757679/modify-html-output-when-add-image-in-posts-and-pages

**Comment by Nicholas-Cardot** [comment]
It looks like we may have to use the image_send_to_editor filter for adding the per-image description. Then we can output the other stuff in a JS variable in the footer so if they haven't added a description on the image itself, we have the fallback calculated and available.

**Comment by Nicholas-Cardot** [comment]
https://wordpress.stackexchange.com/questions/78285/alter-image-output-in-content

**Comment by ckmahoney** [comment]
The image_send_to_editor hook does allow us to edit the markup that is eventually printed on the page. We can do something like adding `data-swp-pin-description=$description`, which would be safer than editing the alt text. (We don't know who or what else might be using the alt text.)

But this is only useful for changing the data attribute for _all_ images on a post. We already have that - it's the Pinterest Description metabox. 

Adding a field in the media uploader is a better approach for having a per-image description.

**Comment by ckmahoney** [comment]
Though, we may need to use that to give each image a `data-id` attribute. 

The issue I'm working through is to find a way to get the pinterest description for each image. Let's say there are five images in a post and each has its own custom pin description. 

With just `the_content`, we only get markup and the post_meta for the page being loaded. No id for the image is passed, so we can not get the image's own post_meta. 

However, if we use the `image_send_to_editor` hook, we can go ahead and tie the image's ID to the image. 

_Then_ we can hook into `the_content` and do something like this (adapted from Filter 2 at https://jhtechservices.com/changing-your-image-markup-in-wordpress/). 
```
function establish_pinterest_descriptions() {
    libxml_use_internal_errors(true);

    $post = new DOMDocument();
    $post->loadHTML($the_content);
    $imgs = $post->getElementsByTagName('img');

    foreach( $imgs as $img ) {

        if( $img->hasAttribute('data-id') ) continue;

        $replacement = $img->cloneNode();

        $id = $img->getAttribute('data-id');
        $description = get_post_meta( $id, '_swp_pinterest_image_description', true );
        
        $replacement->setAttribute('data-pin-description', $description);

        $img->parentNode->replaceChild($replacement, $img); 
    };

    return $post->saveHTML();
}
```

And finally, parse the pinterest description with Javascript. 

What do you think, @Nicholas-Cardot?

**Comment by Nicholas-Cardot** [comment]
Instead of adding the id to the image, why not add the description directly to the image when it's being inserted to the editor? Then we don't have to call the database with get_post_meta for all 5 of those example images to fetch those descriptions.

Then we parse the content, if it doesn't have the data-pin-description attached, then we add one of the backup descriptions on output.

**Comment by Nicholas-Cardot** [comment]
@ckmahoney We don't want to use the send_to_editor function to add this description except for when they specifically fill in that field for the image. None of the fallback methods can be added via this method. 

This is because that description is then permanently stored in the database and it will not be removed when the plugin is deactivated. As such, they need to very, very specifically opt in to having that description permanently attached to that image.

All fallback methods need to be added via the_content() hook so that it is ONLY happening on output and not actually being stored permanently in the database that way. This should also have an option on the options page where they opt in to feature.

So this should be 2 features:
1. An option on the image that let's the user specifically create the data-pin-description attribute for each image.
2. An option on the options page that when activated, our plugin will scan the content for images and any that do not already have the data-pin-description attribute added (AKA the user didn't do step 1 above) then it will automatically generate the description using one of the fallback methods.
