### ISSUE TITLE
Position conflict when homepage is a static page

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#447]
Thought we had this licked but I installed on a new site today and couldn't get the floating left buttons to display on the homepage unless I turned them on for pages.

Steps:

(1) Set all static buttons to none/manual and all floating buttons to OFF
(2) Set a page as the homepage in Settings > Reading
(3) Edit the page and set the floating buttons to ON - no buttons on front end
(4) Turn floating buttons ON for pages in the settings
(5) Observe floating buttons on homepage (as well as every other page - sigh)

We need to look at the logic for front page vs. posts page again and make sure there is a way to keep the buttons on a static homepage even if it's turned off for pages globally.

**Comment by Nicholas-Cardot** [comment]
fixed
