### ISSUE TITLE
PHP compatibility

### ISSUE THREAD

**Issue by bwleung** [warfare-plugins/social-warfare#448]
I have run the PHP 7 compatibility checker on Social warfare 2.3.5 and I received this error for PHP 7 compatibility. Please advise since I am in the process of upgrading to PHP 7

FILE: /nas/content/live/thewoksoflife/wp-content/plugins/social-warfare-pro/functions/update-checker/vendor/ParsedownLegacy.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1412 | ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by nutsandbolts** [comment]
The file referenced is literally checking for the PHP version and only running older code if an older version of PHP is present. Social Warfare is fully compatible with PHP 7.0 and higher. Apologies for any confusion on that!
