### ISSUE TITLE
Add resize options for side floating buttons.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#453]
We'll use the same method that we use for the horizontal buttons and use the transform:scale() property to allow users to make the buttons larger or smaller depending on the plugin user's preference.

**Comment by ckmahoney** [comment]
Look into `transform-origin` CSS property, 
make sure origin is always based on the vertical location (top-left, middle-left, bottom-left)

Allow scale from 70% to 130%

**Comment by Nicholas-Cardot** [comment]
Also, don't forget the right floating buttons. In which case the origin will need to be top-right, middle-right, or bottom-right.

**Comment by Nicholas-Cardot** [comment]
This feature request has now been added.
