### ISSUE TITLE
Hidden Pinterest <img> covers content below

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#457]
# // **Notes for Testers** 

Before, our hidden Pinterest image was basically a glass door sitting on top of the content. Only a developer could know it is was there, so visitors were confused when they were unable to copy text that was hiding below the image. 

### What we want to happen: 
The content of a post should be plain text you can copy/paste and images you can right click. You should be able to highlight all of the text in a post when clicking & dragging.  

### How to test: 
You have the Pinterest browser extension installed (for Chrome or Firefox, for example). 

In Social Warfare -> Advanced -> Advanced Pinterest Settings :
1. Make "Pinterest Image Location" is "hidden". 
2. Make sure you have a Pinterest Image set in the Social Warfare metabox in the post editor.
3. Visit the post on the front end.

The easier way to confirm this works is to use the developer tools and search for elements with the CSS class "swp_hidden_pin_image". Then verify that its z-index is negative and it is in no way blocking access to the content. 

If you do not know how to use developer tools, then try to highlight each paragraph of text using click & drag. 

If everything goes as described, hooray! We are good to go. 
If something is contrary to what we describe, please let us know in a comment to this issue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

IR 15603

Because hidden images are position: absolute, it can potentially make content "underneath" inaccessible to copy/paste/drag. 

- [ ] Add z-index: -10000 to hidden pinterest images

**Comment by Nicholas-Cardot** [comment]
So you would z-index it way down and then bring it back up when it's visible?

**Comment by nutsandbolts** [comment]
Customer checked in to see if this issue is resolved - I wanted to make sure this is included in the next update since it's a simple fix.

**Comment by HeatherKWiser** [comment]
do I also need to make adjustments on the individual post for this to work?
![2018-08-09_1752](https://user-images.githubusercontent.com/42214327/43933185-144f0186-9bfd-11e8-9ae3-daf23b6deac6.png)

**Comment by ckmahoney** [comment]
You can do it in either the global Pinterest settings or on an individual post. 

If in the global settings, you can test on any post. 
If on an individual post, make sure you are testing only on that post.
@HeatherKWiser

**Comment by JasonWiser** [comment]
I do not see this in my dashboard? what am I missing?

the instructions read, 
_In Social Warfare -> Advanced -> Advanced Pinterest Settings :
Make "Pinterest Image Location" is "hidden"._

![2018-08-10_105345](https://user-images.githubusercontent.com/18461953/43966727-a5f75b54-9c90-11e8-9e35-8b317a88c273.jpg)
