### ISSUE TITLE
Refactor the widgets.php file

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#464]
After adding the new fields to widgets.php, we discovered that there are numerous ways to update and improve the codebase increasing readability, efficiency, and logic. This includes using the WP selected() function, converting some of the select options into array based loops, and a few other things.

- [x] Convert the select options into array based loops. $available_options = array('10','20','custom','etc.'); foreach($available_options as $option): endforeach;
- [x] Convert all select options to use the selected() function built into WordPress.
- [x] Add a new @ since to the docblock in the file header to document these updates. 
- [x] Add a thorough docblock to the class
- [x] Add a thorough docblock to each of the class's methods (functions)
- [x] Implement the 4 arguments that can be passed in via the $args parameter to widget()

Also, use ucfirst() on the label (but not the value) of the array items so that "custom" gets capitalized in the dropdown that the end user will see, but the value in the HTML will still be lowercase.

**Comment by ckmahoney** [comment]
TODO:  Finish docblocking widget() once we find out what $args is. 

Ready for review before merge @Nicholas-Cardot.

**Comment by Nicholas-Cardot** [comment]
On line 380, we call echo $before_widget; but that variable is not defined anywhere. I think this is one of the examples that we need to pull from the $args array.

**Comment by Nicholas-Cardot** [comment]
This SO question provides some great context as to where these $args are created and how they are passed into the function:

https://stackoverflow.com/questions/17768968/whats-the-meaning-of-before-widget-and-after-widget

**Comment by Nicholas-Cardot** [comment]
I'm going to leave it branched until we implement what we learned about the $args variable. It appears there are 4 args that can be passed in. Let's get all 4 implemented and then we'll close this out.
