### ISSUE TITLE
Add AJAX page load compatibility to the side floating buttons.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#465]
IR 15662

Our plugin relies on window reloads to fetch data according to the post. When all of the content is loaded via Ajax, we lose the triggers that hook into fetching data. 

Example theme where this happens:
https://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054?s_phrase=creative&s_rank=14

**Comment by Nicholas-Cardot** [comment]
This request isn't compatible with the plugin framework.
