### ISSUE TITLE
[New] Add AMP support to the plugin

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#470]

**Comment by Nicholas-Cardot** [comment]
I think the number one thing that we need to do is to get our CSS and JS registered with the AMP settings somehow so that it will load on the mobile. Without it, none of our shows/hides are getting loaded and it's making our images and buttons go haywire.

**Comment by Lockcuff** [comment]
Would love to see these changes, I have quite a few people wanting to move to AMP and this would help tremendously.

**Comment by Nicholas-Cardot** [comment]
What exactly is AMP support for a plugin? What would it entail? How would the plugin behave differently than it does now?

**Comment by Nicholas-Cardot** [comment]
Closing this as it is a duplicate of #777
