### ISSUE TITLE
Block the Pinterest browser extension from adding its button to images when our buttons is present on the image.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#473]
# // **Notes for Testers** 

Our plugin is known for allowing admins to deliver shares in the best way they see fit. For us, this means we go so far as to override Pinterest's share button with our own.

### What we want to happen: 
When visiting a post, Pinterest's "Save" button does not appear, but instead the Social Warfare "Save" button handles all the pinning. 

### How to test: 
You have the Pinterest browser extension installed (for Chrome or Firefox, for example). 

In Social Warfare -> Display -> Image Hover Pin Button :
1. Make sure "PinIt Button" is "ON". 
  - The other PinIt settings can be anything.
2. Visit a blog post while the Pinterest Browser Extension is enabled.
3. Try to pin using the Pinterest Browser "Save" button. This should fail because the buttons should not exist. 
4. Try to pin using the Social Warfare "Save" button. You should get the Pinterest popup dialogue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

**Comment by ckmahoney** [comment]
Some of the above commits should have actually referenced #405  instead.

**Comment by HeatherKWiser** [comment]
I am struggling with this one...
I installed the pinterest extension. refreshed all my pages and cleared cache
I click the extension button while on a blog post and Voila! I have an entire page of images I can choose from to pin. Seems that is NOT what you are wanting.

Did I miss a step? Let me know if you want me to test this further.

**Comment by Nicholas-Cardot** [comment]
No. Their extension adds a little button on top of the images in the post that allows people to click on that image to pin images from the post. If there is no pin button from Pinterest on the images, then it's working just fine.

**Comment by HeatherKWiser** [comment]
in fact, as I am testing Pinterest button issues are coming up. I am trying to share this post - https://kraaftshaak.com/mixed-media-mania-video-hop-2018-at-the-kraaft-shaak/ - I know it has a Pinterest image in the social warfare box. I can not share to Pinterest using the Pinterest button at all.

**Comment by HeatherKWiser** [comment]
I do have the little pinterest image on all of my images.

**Comment by HeatherKWiser** [comment]
I do have the little pinterest image on all of my images.
I also have a Buffer share image as well (I use Buffer extension)

**Comment by ckmahoney** [comment]
Hi Heather, 
I just checked https://kraaftshaak.com/mixed-media-mania-video-hop-2018-at-the-kraaft-shaak/.

It looks like our `script.min.js` file is not being loaded at all. This is why your Pinterest buttons are not working. The other buttons are also technically not working as they are supposed to, but they still open a new window so it's well enough. 

If you look at the source code, you'll notice that the last 50 or so lines of markup are not valid HTML or JS <script> tags. 

@HeatherKWiser

**Comment by ckmahoney** [comment]
You may need to exclude Social Warfare's Javascript from Autoptimize. Here are the instructions from the Autoptimize developer:

- go to settings -> autoptimize- be sure to click on the "show advanced settings"-button
- go to Javascript options
- find the "Exclude scripts from Autoptimize:" option
- in the comma-separated text-field next to that add plugins/social-warfare/js/ (make sure there's a comma between what's there already and what you're adding
- click on "save changes & empty cache"

**Comment by JasonWiser** [comment]
Pin "save" button IS showing on my images. 
I am confused by what I am supposed to be looking for. 
How can I know the difference between the _Pinterest Browser "Save" button_ and the _Social Warfare "Save" button_
I am not using Autoaptimize

I am testing on https://ontracktips.com which is a "nightmare" site.
