### ISSUE TITLE
"Shares" is cutoff in totes floatBottom in FireFox

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#475]
IR 15899

Example:
https://shotkit.com/best-mirrorless-cameras/

- [ ] Find which element is appropriate to target
- [ ] Update style to fully show the word "Shares"
Verify correct display for:
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Edge
    - [ ] Internet Explorer
    - [ ] Opera

**Comment by nutsandbolts** [comment]
This will fix it (and applies to FF only):

`@-moz-document url-prefix() {
    .nc_socialPanel .totes .swp_label {
        margin-top: 8px;
    }
}`
