### ISSUE TITLE
Make admin setting at least somewhat mobile responsive. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#476]
## Notes for testers

**What we expect**
When viewing your Social Warfare settings on a mobile device, you should be able to change any settings and save those changes. 

**How to Test**

1. Go to the Social Warfare options page on a mobile device, or in dev tools mobile device. 
2. You should be able to navigate the options easily and change any settings like normal. 
3. The "Save Changes" button should be easily visible and clickable. 
4. Change to a device with larger dimensions, such as a tablet. Repeat 1-3.

If one of the settings is not visible or interactive, or if the Save Changes button does not appear, please let us know as a comment to this issue.

Once you have finished testing, please give this comment a thumbs up. 
### end notes
I noticed this earlier today, and then ran across a ticket describing the same issue.

IR 15900

If you view the options page in a tablet screen size, the Save button disappears (can not save plugin settings). The settings navbar also fails to display (Display, Styles, Registration, etc).

Edit the admin stylesheet to make sure all options, settings, and menus are visible and clickable. These breakpoints are borrowed from Twitter Bootstrap v4. 

 - [x] 0 < width < 767
 - [x] 768 < width < 1100
 - [x] 1100 < width

**Comment by ckmahoney** [comment]
Wow, that's a lot of breakpoints. I usually try to focus on three (mobile, tablet, desktop). But it is Twitter, and I'm sure they know a lot more about responsive design than I do.

For a WordPress admin page, I think we can get away with just tablet and desktop. I doubt there are many admins changing their settings on mobile, so creating an entire mobile layout would not be a great use of time. 

How about these: 

0 < width < 768
769 < width 

What do you think @Nicholas-Cardot ?

**Comment by ckmahoney** [comment]
We might let the tablet max size be 992 instead of 768.

**Comment by ckmahoney** [comment]
This is a design related issue, so we actually need @DustinWStout's input more than anything. What do you think, Dustin?

**Comment by ckmahoney** [comment]
bump @DustinWStout

**Comment by Nicholas-Cardot** [comment]
Assigning this issue to Dustin. We need at least some general guidance on this issue before we can begin. Once we get that, we'll pitch the assignment back over to us. Thanks!

**Comment by DustinWStout** [comment]
Working for me pretty well.
