### ISSUE TITLE
Object Oriented Makeover Wishlist

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#480]
- [ ] The social warfare options on the post editor.
- [x] The options array needs to be an extendable class.
- [x] The options page needs to take the object from the object array class and process it into the options page HTML.
- [x] The options-fetch.php needs to be a class that takes the values from the options page and makes them available to the plugin.
- [x] The buttons standard file needs to be a class with getters and setters for customizations.
- [x] The floating buttons on the side needs to be a sub class of the buttons standard.
- [x] The networks need a parent class in core and then each network will be a child class of it.

- - - -
In the comments below we will be sketching out class implementations.

**Comment by ckmahoney** [comment]
```
class Network {
    public $network, $api_url;
    
    __construct() {
        $this->network = $network;
        $this->api_url = $api_url;
    }

    public function fetch_data() {
        $data = // *Make the API request
        
        return $this->parse_data( $data );
    }

    private function parse_data( $data ) {
        // *Network specific parsing 
    }
}
```

**Comment by ckmahoney** [comment]
```

class Facebook extends Network {

    __construct() {
        parent::__construct('facebook', 'https://api.facebook.com');
    }

    public function facebook_only() {
        // *This method is for Facebook use only.
    }
}
```

**Comment by Nicholas-Cardot** [comment]
Closing and moving the final "post editor" refactoring to 3.1 milestone.
