### ISSUE TITLE
LinkedIn share counts no longer working properly.

### ISSUE THREAD

**Issue by MarkFl12** [warfare-plugins/social-warfare#485]
Line 60 of linkedin.php uses the url:

'https://www.linkedin.com/countserv/count/share?url=' . $url . '&format=json'

which is now returning a 0 for every possible url. LinkedIn seem to have deprecated this as you can read here:

https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter

Is there another way to get the counts?

**Comment by DustinWStout** [comment]
Hi @MarkFl12 ! As of last week, we've gotten confirmation that LinkedIn has officially dropped support for share counts. We don't know why, but it seems they've followed the lead of Twitter and Google+ and don't care to house URL share counts anymore.
