### ISSUE TITLE
Share buttons not available on search results and on ajax loading

### ISSUE THREAD

**Issue by B1-0S** [warfare-plugins/social-warfare#486]
In the plugin there are two restrictions that are creating a lot of trouble for a project I'm working on:

The first one is a check not to display buttons in admin (social-warfare/functions/frontend-output/buttons-standard.php, 130) This blocks buttons like ajax load more to render the posts with proper social sharing buttons.

The second one is hard block for the buttons to be displayed on search results(social-warfare/functions/frontend-output/buttons-standard.php, 150). I'm not sure why this is needed in the plugin but it actually makes a mess when the design has share buttons in the loop.

Please let me know if there is something I can do to fix those.
Thanks

**Comment by Nicholas-Cardot** [comment]
We had a lot of complaints about them showing up on search pages. Plus, not many end users are sharing articles from on site search results. 

As far as AJAX support goes, we have another issue tracking this one right now and we are working towards finding a better solution to be able to support AJAX.

https://github.com/warfare-plugins/social-warfare/issues/465
