### ISSUE TITLE
Mobile orientation change doesn't adjust properly

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#49]
If you load a page on a mobile device (ex. iPhone) the buttons display fine.. If you move to landscape (turn phone sideways) the buttons expand to and show numbers. However, if you then switch back to portrait, some of the buttons will not switch back and you end up with two lines.

**Comment by Nicholas-Cardot** [comment]
Apparently the binding to the resize event does not always include orientation changes as well. As such, we need to include a separate listener for orientation changes. Then we'll call our sizing function after the orientation changes possibly including a slight delay to ensure that the orientation change animations are entirely finished before calculating sizes.

Trigger the swSetWidths(); function after the mobile oritentation changes using one of the following methods.

**Pure Javascript Solution:**

    // Listen for orientation changes
    window.addEventListener("resize", function() {
        swSetWidths();
	activateHoverStates();
    }, false);

**jQuery (Preferred) Solution:**

    // Listen for Orientation Changes
    jQuery( window ).on( "orientationchange", function( event ) { ... 
        swSetWidths();
        activateHoverStates();
    });

**Delay the Function (if necessary):**

    setTimeout( function() {
        swSetWidths();
        activateHoverStates();
    } , 500 );
