### ISSUE TITLE
Translate documents to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [warfare-plugins/social-warfare#493]
HI! I'd like to contribute to this project by offering a translation nto Spanish which is my native language, let me know if you guys are interested, CHEERS!

**Comment by Nicholas-Cardot** [comment]
We're getting ready to rebuild all of the translation functions to use the localization functions built into WordPress.org. When that happens (should be in the next 2 months), then we'll be sending out a call for translators who want the plugin translated into their own languages. I hope that helps.
