### ISSUE TITLE
Popular Posts Widget WPML Compatibility

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#498]
I know you have done a lot of work to the plugin recently so this might be fixed already.

The popular posts widget displays all popular posts regardless of site language when WPML is in use to separate multiple language versions of a site.

This could be resolved by using separate social media accounts for each site language but many multilingual authors use one account per network regardless the languages available to site readers. Plus, you would need to provide site admins an option to enter multiple account IDs per social network.

WPML provides a site language test function. I've not investigated the Social Warfare plugin to such an extent to know for sure whether the WPML language test function will or won't work to filter posts displayed by the popular posts widget. I suspect there will be little indication of post language passed back by the networks so this option is probably not viable.

# Suggested Solution

You could provide a text field (or repeater field) in the popular posts widget that allows a site admin to specify a text string to test URLs against e.g. If the URL contains the string /es/ then don't display in this widget, or if the URL contains the query string ?lang=es then do not show in this widget. This type of filter might be the best approach because it has scope to be applied outside of WPML preferences.

What are your thoughts?

**Comment by ckmahoney** [comment]
Hi @VR51,

Within the scope of what already exists in Social Warfare, you might try doing the following:
1. Use the Post Type dropdown menu when creating your settings for this instance of the widget. 
  - Set it to a post type specific to that language, if it exists
2. Use the Network dropown menu to only look at shares for a particular network (if you know your Spanish speaking readers are best on LinkedIn, for example, this might be the best network to sort by)
3. Set a different instance of Popular Posts for each configuration you would like. 

I know this is not the perfect solution, but the reality of your feature request is very distant. I provide these fallback techniques as alternative options and will add your feature request to our wishlist #392.
