### ISSUE TITLE
Not working with visual editor

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#5]
We have had some people say that Social Warfare is not working with their Visual Editor plugin (or a visual editor built into their theme). We have solved a handful of these instances and currently we're only seeing issues with the _Cornerstone Visual Editor_. 

If you have encountered any other conflicts with visual editors, please be sure to add them below.

**Comment by Nicholas-Cardot** [comment]
From one of our users: *Hi! I'm just letting you know that there appears to be a conflict between Social Warfare and WP Visual Composer. When I hit "edit in Visual Composer" the editing screen appears but then goes blank after Social Warfare loads.*
