### ISSUE TITLE
Link Click-to-Tweets to different page

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#50]
Allow for placement of Click-to-Tweets that will tweet a link to a page different than the one it was placed on. (Similar to the ability to add share buttons for a designated post_ID).

**Comment by Nicholas-Cardot** [comment]
This is a great idea and should be relatively easy to do since we laid all the ground work for this type of functionality when we built this functionality into the buttons themselves.

**Comment by lisaleague** [comment]
+1 - can be used for thank you pages for optin offer or webinar registration :)

**Comment by Nicholas-Cardot** [comment]
With tonight's commit to GitHub, this is now possible. Simply add a link to the tweet, and the default link will not be added.

**Comment by lisaleague** [comment]
This will be great on thank you pages to share the lead magnet or webinar! Thanks!

**Comment by Nicholas-Cardot** [comment]
@lisaleague We don't plan on releasing this out to users until around July 1 as part of our 2.0 overhaul of the plugin. However, if you want to start using it now, simply download this version from the GitHub and you're welcome to beta test this version.
