### ISSUE TITLE
Pin hover conflicts

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#501]
Can we leave the Pinterest image hover option OFF by default? It causes conflicts with a lot of other themes and plugins and people think it's SW in general because the conflicts come after they activate Pro. If the option is off until someone turns it on, at least they'll know it was the setting change and not SW itself.

**Comment by ckmahoney** [comment]
Off by default makes sense. We are also experiencing issues on mobile: IR 16153

While on mobile, we need to redefine which events are triggered on touch (rather than hover).

**Comment by Nicholas-Cardot** [comment]
Pin is now set to off by default.
