### ISSUE TITLE
Create classes for each of the new Options Page entities. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#504]
* SWP_Options_Page                
 * SWP_Options_Page_Tab         
 * SWP_Options_Page_Section
 * SWP_Options_Page_Option 
 * SWP_Options_Page_Registration   
 * SWP_Options_Page_HTML          
 * SWP_User_Options   
 * SWP_User_Options_Migration

**Comment by Nicholas-Cardot** [comment]
This already has an issue: https://github.com/warfare-plugins/social-warfare/issues/504
