### ISSUE TITLE
Sketch out SWP_Options_Page_Option

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#508]
Draft a constructor, docblocks, general method declarations, and anticipated arguments and return values for those methods. 

Replaces `options-array.php`.

**Comment by Nicholas-Cardot** [comment]
Well for set premium, it needs a setter, because we decided that it will use two properties. One that is a bool (whether or not it's premium, default tofalse) and one that is a string (which addon must be registered in order for it to work.) Something like this should work:

```
// The Two relevant properties 
public $premium = false;
public $premium_addon = ''; (blank string)
public function set_premium( $premium_addon ) {
   // Sanitize here
   $this->premium = true;
   $this->premium_addon = $premium_addon;
   return $this;
}
```
