### ISSUE TITLE
Conflict with CSSHero plugin

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#51]
When Social Warfare is activated, CSS Hero will load, but not run. It shows up, but it doesn't perform any of its functions.

**Comment by Nicholas-Cardot** [comment]
- [ ] Get the CSS Hero plugin installed on our development server
- [ ] Replicate the conflict on our server
- [ ] Identify the source of the conflict
- [ ] Fix the conflict

**Comment by Nicholas-Cardot** [comment]
This is most likely a js conflict which should now be fixed with the refactored JS in version 2.1.0
