### ISSUE TITLE
Make og:type optional

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#515]
Some of our users have other plugins that set the og:type, but Social Warfare is overriding those settings. Since we already have a dropdown in the Social Identity settings, it should be easy to have a "no output" option in the dropdown to turn this off completely. If we have a filter, it's not documented, so that might be another avenue to pursue.

**Comment by AJ9** [comment]
Hello thanks for raising, that was quick! 

I've taken a look into this and the properties are returned from the `swp_open_graph_html` function in `header-meta-tags.php`. It currently returns nothing and defers if `yoast_og_setting` is found, so the functionality seems to be already there, just needs a flag to be passed through! 

(Hope this helps & thanks!)

**Comment by Nicholas-Cardot** [comment]
So for clarification, you want the option to have Social Warfare set most of the open graph tags but you want to be able to granularly control which ones are output by us and which ones are not? So like you can turn the type on or off but still get the title, description and others being output by our plugin?

**Comment by AJ9** [comment]
Initially the option to disable this feature entirely. Granular control would be a nice to have, but if I have another SEO plugin installed I do not want Social Warfare to output this social meta data too.

**Comment by Nicholas-Cardot** [comment]
In that case we've already completed this and it will be included in our 3.0.0 rollout later in the month. We won't be adding control to turn on each and every individual OG Tag. But you can turn the entire set on or off.
