### ISSUE TITLE
Ensure pin buttons do not appear on Videos in posts.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#517]
IR 16352

When PinIt on hover is activated, a Pin button is showing up on videos. This seems to be well enough for YouTube, but the button is breaking the video on other services (e. g. Wistia). 

We should consider creating a user option to allow PinIt on videos. This can let the user decide to prevent any possible video conflict by turning off the video:hover button option.

**Comment by nutsandbolts** [comment]
Personally I think we should disable it altogether for videos - that seems like too much potential for conflicts and issues.

**Comment by Nicholas-Cardot** [comment]
This should ONLY target IMG tags.  We'll double check this before next release.

**Comment by ckmahoney** [comment]
Andrea, How often does this come up? I remember encountering it one time in a ticket.

If it is often, or if you have seen a plugin or service (like Wistia) where this happens frequently, we can move forward with it. Otherwise we would be trying to create a universal solution for a shot in the dark for edge case sites. 

@nutsandbolts

**Comment by nutsandbolts** [comment]
It's fairly often - basically if people use our Pinterest hover and embedded videos (which is like 65% of the websites on the internet), they're going to run into it. The Pinterest hover in general needs a lot of refinements; most of our customers have to turn it off because of conflicts with their theme, other plugins, videos, or the fact that they can't disable it on a per-page basis.... lots of things we can discuss for 3.2.0.

**Comment by ckmahoney** [comment]
As you encounter any sites that have this, please paste a link here. Do not hesitate to spam it with many examples.

The reason I ask for many - there are quite a few ways to add an image to a video. In short, I'd say it comes down to using a relatively or absolutely positioned placeholder image imposed over the video until the video is playing. Where this image exists in the markup is what we need to know. 

We need to identify the most common patterns in order to prevent our Save button from appearing over videos.

**Comment by Nicholas-Cardot** [comment]
We definitely need a link to an example or to know what plugins or embeds are causing this in order to make any progress on this issue.
