### ISSUE TITLE
Ensure the widget uses the main query via wp_reset_postdata().

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#525]
IR 16085

In cases where other plugins use the WP_Query object, some external mechanism is modifying the WP Query without replacing it for our use. In this case, Post Types Order interfered with our query.

One possible fix may be to use <a href="https://codex.wordpress.org/Function_Reference/wp_reset_postdata">`wp_reset_postadata()`</a> both before and after our queries.

**Comment by Nicholas-Cardot** [comment]
I've noticed this in the past as well and have implemented wp_reset_postdata() in multiple places so far. It's the easiest way to fix it for our purposes.

**Comment by Nicholas-Cardot** [comment]
wp_reset_postdata() is now used both before and after the query in the popular posts widget.
