### ISSUE TITLE
Pop-up ads appear when clicking on Social Warfare buttons in Safari/Chrome on iPhone??

### ISSUE THREAD

**Issue by Qh8HpM** [warfare-plugins/social-warfare#533]
Huge pop-up ads appear when I click on Social Warfare buttons in Safari or Chrome. 
I have tested on two different iPhone and same problem happened.

I had to disabled Social Warfare plugins and everything is fine.
Would you please explain whether SocialWarfare inject ads hiddenly?

![image](https://user-images.githubusercontent.com/10734377/39031683-4f3cf45e-442f-11e8-8641-9556f37cfb68.png)

**Comment by DustinWStout** [comment]
So sorry to hear this is happening for you, @Qh8HpM. 

Social Warfare has *never* and *will never* do any such thing. Whatever the issue is here, it's likely another plugin or possible malware that has infected the website and injected itself into Social Warfare's button outputs.
