### ISSUE TITLE
Make the Pin Hover Button Compatible with Relative URL images.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#538]
# // **Notes for Testers** 

When sharing an image to Pinterest, they need to know the absolute path. However it is common for themes and plugins to use relative paths. For example, instead of 
`<img src="www.example.com/wp-content/images/my-favorite-flowers.jpg" />`

the src might be relative: 
`<img src="/wp-content/images/my-favorite-flowers.jpg" />`

On the front end of the site, the result is the same. You get your image 'my-favorite-flowers'. 
However, sharing to Pinterest did not always give us the same image. Until now. 

### What we want to happen: 
When pinning an image with a relative URL, the image is successfully sent to Pinterest. 

### How to test: 
In Social Warfare -> Display -> Image Hover Pin Button :

1. Make sure "PinIt Button" is "ON".
2. Make sure "Image Source" is "Pin the Image"
3. Click "Save Settings" if any changes were made.
4. Go to a post editor. 
5. Insert an image using the media button.
6. Switch to the text editor if you are using the visual editor.
7. Find the image you have just inserted. It should be in the same place.
8. Trim the protocol, domain name, and TLD leaving only `/wp-content/rest-of-path.../`

For example, when I insert an image on my local site using the Media button, it gives me this:
`<img class="alignleft size-medium wp-image-105" src="http://localhost:8888/swarf/wp-content/uploads/2018/06/teeth-300x218.jpeg" alt="Toy mouth eating a toy donut" width="300" height="218" />`

But I need to trim it to this: 
`<img class="alignleft size-medium wp-image-105" src="/wp-content/uploads/2018/06/teeth-300x218.jpeg" alt="Toy mouth eating a toy donut" width="300" height="218" />`

**The leading forward slash `/` is important.** This tells the browser that you are requesting a resource (image) relative to the current domain. 

9. Save the post.
10. Visit the post from the front end. You can optionally verify the image has a relative path by inspecting it with the developer tools. 
11. Hover the image and click "Save". 
12. You should see the same image come up in the Pinterest popup.

If everything goes as described, hooray! We are good to go. 
If something is contrary to what we describe, please let us know in a comment to this issue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

**Comment by ckmahoney** [comment]
Do we have any context of what this is about?

**Comment by Nicholas-Cardot** [comment]
They wanted it so that images that use links relative to the server such as:

/my-image.jpg 

will work rather than only on stuff like:

http://mydomain.com/my-image.jpg

However, I don't know if there is a practical way to do this.

**Comment by Nicholas-Cardot** [comment]
No because it passes a relative link to Pinterest itself and Pinterest doesn't know what to do with it.

Like you can't pass a relative link through a URL parameter.
Once received by the remote server, if it doesn't have a domain attached, it has no idea where that image is actually from.
https://stackoverflow.com/questions/3496491/getting-the-absolute-path-of-a-img
So when we pull the URL, we just want to make sure that we convert it to absolute before using it in the URL parameter.

**Comment by ckmahoney** [comment]
Here is the pertinent code, I believe. Please correct me if I am wrong.  
From script.js, starting at L425, then L477:
```
        var defaults = {
            wrap: '<div class="sw-pinit" />',
            pageURL: document.URL
        };

        var options = $.extend(defaults, options);
        var bookmark = 'http://pinterest.com/pin/create/bookmarklet/?media=' + encodeURI(pinMedia) + '&url=' + encodeURI(options.pageURL) + '&is_video=false' + '&description=' +  encodeURIComponent(pinDesc);
```

The URL provided to Pinterest is `document.URL`, which should be the full URL. 
Also, those first two variables are redundant. Options is not defined anywhere else. After it has been extended, `options.wrap` and `options.pageURL` are both used exactly once. We can eliminate all of those.

**Comment by JasonWiser** [comment]
tested. works
