### ISSUE TITLE
Compatibility issues exist with the "Visual Composer" plugin

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#54]

**Comment by lisaleague** [comment]
I use with VC and no issues, perhaps the issue is theme related?

**Comment by Nicholas-Cardot** [comment]
@lisaleague Great question. Is Visual Composer a premium plugin or free? Do you have a link to where I can acquire a copy for testing purposes? Thanks!

**Comment by lisaleague** [comment]
Hey Nicholas, I put you in my staging and let you test all you want. Is paid. I'll email your support email.

**Comment by Nicholas-Cardot** [comment]
@lisaleague Wow. That's excellent. I just saw your email. I'm traveling home today, but I'll be in there tomorrow running these tests. Thanks for the access!

**Comment by lisaleague** [comment]
Travel safe! @Nicholas-Cardot
