### ISSUE TITLE
Gracefully fail if PHP version is below 5.4

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#540]
We can perform a simple check to make sure PHP is 5.6 or greater. Something like this:

`if ( version_compare( PHP_VERSION, '5.6', '<' ) ) {`

	/**
	 * Deactivate plugin.
	 */
        add_action( 'admin_init', 'warfare_php_too_old' );
	function warfare_php_too_old() {
		deactivate_plugins( plugin_basename( __FILE__ ) );
	}

	/**
	 * Display notice after deactivation.
	 */
        add_action( 'admin_notices', 'warfare_deactivate_notice' );
	function warfare_deactivate_notice() {
		echo '<div class="php-warning"><p>' . esc_html__( 'Social Warfare cannot be activated unless your server is running PHP 5.6 or newer. Please get in touch with your web host to move to a supported version of PHP.', 'warfare' ) . '</p></div>';
		if ( isset( $_GET['activate'] ) ) {
			unset( $_GET['activate'] );
		}
	} 
`} else { 
*load the plugin files*`

**Comment by Nicholas-Cardot** [comment]
We're working on trying to keep the plugin compatible as far back as 5.3 so we don't necessarily want the plugin to just shut down if they're below 5.6.

**Comment by ckmahoney** [comment]
In Core during activation, run a check on the PHP version. If the PHP version is below what we support, we do NOT load any SW code and instead display a dashboard notice telling them to update their version of PHP.
