### ISSUE TITLE
social warfare too slow

### ISSUE THREAD

**Issue by shuaiZend** [warfare-plugins/social-warfare#541]
every post page well post data to admin-ajax.php.
my wordpress have **70K PV/day** pages views.
this post **data can't cache**.
every post request‘s **response times is 1s+**.
**have any idea can cache? or disabled Share Counts?**

I used php 7,
server is 32core,128G RAM..  and use WPFC, cloudflare

**Comment by Nicholas-Cardot** [comment]
This should already be fixed and will be included in our 3.0.8 release later today or first thing tomorrow.

**Comment by shuaiZend** [comment]
i wanna disable share counts. well fast?
