### ISSUE TITLE
Approx. 50% of the translations don't work

### ISSUE THREAD

**Issue by nicolasricher** [warfare-plugins/social-warfare#542]
Hi there, 

I am in charge of the French Translation (both on PoEditor and translate.wordpress.org) and even though I have translated every string possible, it doesn't seem to work in the back-end.

We have both French and English sentences everywhere.

Could you take a look at the issue?

(Social Warfare and SW Pro are updated to 3.0.8)

Here are 5 screenshots to show you how it displays:

![page1](https://user-images.githubusercontent.com/7459831/40586307-dd084cf8-61c0-11e8-90de-cd9b9eb2deb1.png)
![page2](https://user-images.githubusercontent.com/7459831/40586308-e1c3b23c-61c0-11e8-8c3c-4194ce914bde.png)
![page3](https://user-images.githubusercontent.com/7459831/40586317-f46cd24c-61c0-11e8-8fe4-81e9833e5a19.png)
![page4](https://user-images.githubusercontent.com/7459831/40586319-f6838378-61c0-11e8-9407-2f6959cd5049.png)
![page5](https://user-images.githubusercontent.com/7459831/40586322-f844a1c4-61c0-11e8-9106-811fc8e8a1e2.png)

**Comment by ckmahoney** [comment]
It could also mean that the text displayed has changed and we don't have a translation for it, 
Or that we have new text that does not have a translation. 

We should keep a record of which texts we do have translations for, and for which languages.

To find out which calls to gettext we are using, we can do a global search for `__(`. From there we can collect and organize the texts and keep them in some kind of spreadsheet to record which languages have a translation for each text.

**Comment by ckmahoney** [comment]
This issue is sitting here, but what are we doing about it? 
The developers can prepare lines for translation, but we do not have any translators on our team.

**Comment by nicolasricher** [comment]
You don't have to translate anything, the community will take care of it: https://translate.wordpress.org/projects/wp-plugins/social-warfare

**Comment by Nicholas-Cardot** [comment]
This is an ongoing, never-ending maintenance issue. As such, there is no need to a singular GitHub issue to track it. Closing.
