### ISSUE TITLE
Remove (or replace) StumbleUpon button

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#546]
Since StumbleUpon is being shut down, the StumbleUpon button will no longer work, and therefore should be removed.

**Comment by nutsandbolts** [comment]
We don’t want to replace it with the new service?

**Comment by DustinWStout** [comment]
I have reached out to the Mix team, though, to see if there is going to be a "Mix" (which is what StumbleUpon is being rolled into) share button. If so, it might be highly advantageous for us to make these buttons the same, preserving share counts from the former.

**Comment by DustinWStout** [comment]
As of now (via the Mix team) they have NO PLANS for a Mix share button.

**Comment by Nicholas-Cardot** [comment]
This has now been removed.

**Comment by alif** [comment]
@DustinWStout We have instructions available on our Mix Badge. I'm not sure who told you we didn't have plans for it but here's the info on it:
https://community.mix.com/blog/2018/7/12/add-a-mix-badge

Let me know if you have any questions or need anything from us. Happy to help in any way I can!

**Comment by Nicholas-Cardot** [comment]
@alif Thanks for letting us know. We'll work on getting this added back in.

**Comment by alif** [comment]
Thanks @Nicholas-Cardot!

**Comment by DustinWStout** [comment]
Yes, @alif much appreciated!

**Comment by DustinWStout** [comment]
@Nicholas-Cardot you think there's a way to tie this to the old StumbleUpon button as a replacement rather than a brand new button?

**Comment by Nicholas-Cardot** [comment]
I guess I don't really understand the difference between the two. You just mean you want to preserve the share counts? Or is there something more that you're looking for?

**Comment by DustinWStout** [comment]
Will think on this more and continue the convo internally.
