### ISSUE TITLE
Create a dismiss-able notice class. 

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#547]
We want to create a dismiss-able notice class to allow us to be able to quickly and easily create notices in the WordPress dashboard.

Project Checklist:
 - [x] Move the class into the utilities folder.

Timeframe Checklist
 - [x] Add a parameter to the add_cta method to accept a timeframe. Timeframes include 'permanent' or 'temporary'.
 - [x] Add a data-timeframe tag to the cta <a> anchor tag which will say permanent or temporary.
 - [x] Make the JS function look at the data-timeframe tag and ping either perma-dismiss or temp-dismiss methods.
 - [x] Make the perma-dismiss method store a timestamp instead of a boolean (true) for the value in the database.
 - [x] Make the conditional to show or not show the notice look at the boolean (as it does now) and also check if it's a timestamp and see if 30 days have transpired.

The class will need to be easily instantiated to create and manage notices both in the WordPress dashboard and within our own options page. Once dismissed from either, it needs to be dismissed from both.

This link provides the visual style for what we will want it to look like: https://github.com/warfare-plugins/social-warfare/issues/528

Ideally, it should simply be called with a simple instantiation and a couple of setters, and then PHP will take care of the rest.

```
$StumbleUpon_Notice = new SWP_Dashboard_Notice();
$StumbleUpon_Notice->set_key('stumble_upon_notice')
    ->set_message(__('Our message goes here.','social_warfare');

```

Pseudo Class Code:

```
class SWP_Dashboard_Notice() {

    public $key = '';
    public $message ='';

    __construct() {
        add_action('admin notices or whatever it's called' , array($this , 'show_notice' ) );
    }

    public function set_key($key) {
        $this->key = $key;
        return $this;
    }

    public function set_message($message) {
        //same as set_key
    }

    public function show_notice() {
    }

}
```

 - This will need a mechanism to check the social_warfare_notices option in the database to see if the notice has already been dismissed. 
 - This will also need a mechanism to handle admin-ajax ping that will be sent from the JS to permanently dismiss the notice and update that option in the database.
 - This will get added to two hooks. The WP hook, and a proprietary one that we will make specifically for our admin options page since we don't show other notices on our options page.
 - JS will be added to admin.js (since this will be all over the dashboard) that will detect our notices (a unique class, perhaps) and will handle the dismisses. 
- A mechanism needs to exist to add different types of dismiss options. Instead of an x on the side, we may want a call to action with a link, for example.

I will be updating this issue with more guidance as I sketch it out.

**Comment by ckmahoney** [comment]
What is the scope of where this class can place notices?

Dashboard and generic admin notices are easy to implement, since they have the WP hook. The method you have outlined is near close to what works. 

If we want to include a notice on the options page, we would have to either: 
 - Create a Notice option (in the same vein as  SWP_Section_HTML), where the HTML generation is handled entirely on the server.
or 
 - Create a Javascript interface for inserting notices (a rudimentary implementation of this exists for the StumbleUpon notice right now). 

In either case, you are correct that we will have to create an ajax ping to permanently dismiss the notice. 

Here's a bit more pseudo code, not merged with the previous examples. 

```
__construct() {
    if ( $this->should_display_notice() ) {

        if ( $this->is_dashboard_notice()) :
            add_action('wp_dashboard_notices', [$this, 'create_dashboard_notice']);
        elseif ( $this->is_options_notice()) : 
            $option = new SWP_Option_Notice( $key, $message );
        else :
            // Widgets? 
            // Tricky to place Options page notices? 
            // We can handle them here. These will be less frequent. 
        endif;
    }
}

add_action( 'wp_ajax_perma_dismiss', array( $this, 'perma_dismiss' ) ); 
add_action( 'wp_ajax_nopriv_perma_dismiss', array( $this, 'perma_dismiss' );

public function perma_dismiss() {
    $notices = get_option( 'social_warfare_dismissed_notices', [] );
    $notices[$_POST['key']] = true;

    echo json_encode( update_option( 'social_warfare_dismissed_notices', $notices ) );
    wp_die();
}

add_action( 'swp_footer_scripts', [$this, 'setup_ajax'] );
private function setup_ajax() {
    ?>
    <script>
    $.post({
        url: '<?php echo admin_url( 'admin-ajax.php' ); ?>',
        data: {
            action: 'perma_dismiss',
            key: '<?php echo $this->key ?>';
        }
    })
    </script>
    <?php 
}

public function should_display_notice() {
    $notices = get_option( 'social_warfare_dismissed_notices' );
    if ( true === $notices[$this->key] ) {
        return false;
    }

    return true;
}
```

**Comment by Nicholas-Cardot** [comment]
No. The whole point of this class is that we will NOT be using JS to output the notice. It will be entirely handled via PHP. The only thing JS will do is have a generic dismiss handler which will be simply a click bind to something with our proprietary class which will look at a data-notice-key attribute of somesort and send the dismissal to admin ajax for storage in the database. 

We will need to create a spot on the options page which will use a hook like: 

```
$notices = array();
$notices = $apply_filters('swp_options_page_notices' , $notices );
if ( !empty( $notices ) ):
    blah blah
endif;
```

**Comment by Nicholas-Cardot** [comment]
```
$.('.swp_dismis_notice').click( function() {
    var key = $(this).attr('data-notice-key');
    // Send key to admin ajax
});
```

**Comment by ckmahoney** [comment]
Using JS was only 50% of the proposed options :)

Yes, we will have to have some javascript to handle clicks and handle the ajax update. My previous comment offers a suggestion of how to implement the ajax portion. The click handler can look something like this: 

HTML
```
<div class="swp-admin-notice" name="stumble_upon">
    <p>Did you know stumbleupon is dying...</p>
</div>
``` 

In the SWP_Notice class: 
```
public function add_click_handler() {
    <script>
        jQuery("[name]=<?php echo $this->key ?>").on("click", function(e) {
            jQuery(this).hide();
            // do ajax request. 
        } 
    <script>
}
```

**Comment by Nicholas-Cardot** [comment]
If you use your click handler (JS) instead of the one I'm proposing, you'll have to output a different/unique click handler for every single notice that ever goes to the dashboard. If you use my implementation above, you only need one generic one that gathers the key, hides the box. and then runs the ajax request.

**Comment by Nicholas-Cardot** [comment]
That generic click handler can then be included in admin.js instead of dynamically being generated over and over.

**Comment by ckmahoney** [comment]
Alrighty, that is reasonable. 

Let's also consider cases where users do not frequently update their plugin. Here's a scenario:
Sally updates to 3.0.9 and sees a notice that StumbleUpon is disappearing and goes ahead and dismisses it. Then she totally forgets about it, and July doesn't update to 3.0.10 for whatever reason. 

Now she has a broken StumbleUpon button, at least for a few days, until the visitors to her site tell her the button isn't working.

To prevent this:
If we know an issue is time sensitive, we can put time sensitive checks where appropriate in the code. So in 3.0.9, in SWP_Stumble_Upon:

(very pseudo)
```
__construct() {
    $today = date();
    $expiry = date_create(1170288000) // whatever the expiration date is in seconds

    //* If $today is after $expiry, do not add to the networks array. Just bail.     
    if ( false === date_compare($today, $expiry) ) {
        return;
    } 
}
```

**Comment by Nicholas-Cardot** [comment]
I think that 99% of notices will only ever need to be one-time notices.
