### ISSUE TITLE
Move the controller for the update checker

### ISSUE THREAD

**Issue by warfare-plugins** [warfare-plugins/social-warfare#551]
The controller for the update checker needs to be moved outside of the SWP_Addon class into some sort of a standalone class that can be called directly in the main file of the addon plugins. As it is now, if they update core, the version mismatch prevents the updater from loading at all. 

- [x] Move the update checker function into the main file (social-warfare-pro.php)
- [x] Make the conditional only check for 3.0.0 (core) or greater. It does not need an exact match.
- [x] Use the key mentioned in our private chat.

This should ensure that all updates for pro are completely seamless moving forward.

**Comment by warfare-plugins** [comment]
Currently this function lives on line 320 of the the Social_Warfare_Pro class. It needs moved to the main social_warfare.php file and needs to have ONLY a check for greater than or equal to 3.0.0 in order to call the update checker class. 

That method is checking that we are ahead of 2.3.5, but that method never gets called because of the version mismatch stopping the entire Social_Warfare_Pro class from being activated.

**Comment by Nicholas-Cardot** [comment]
This should now be solved.
