### ISSUE TITLE
Auditing Discoveries Needing Feedback

### ISSUE THREAD

**Issue by warfare-plugins** [warfare-plugins/social-warfare#552]
I've added todo's inside of the following files while auditing and cleaning them. See the files for the actual todo's. We need to review these together to determine the appropriate action to take:

- [x] The Click to Tweet Class
- [x] The options page section class. Funnel the $key through set_key. Clean up set_key to use type checking.
  
- [x] The options page tab class. Same as above. Clean up the $key assignments.
- [x] The options page class.
- [x] Is the Options_Page_Section class in the admin folder a duplicate needing deleted?

**Comment by Nicholas-Cardot** [comment]
These should now all be solved.
