### ISSUE TITLE
Floating & Mobile Buttons Fixes

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#554]
This is the central hub for discussion on bugs related to the floating buttons (top and side), as well as buttons on mobile. 

- [x] Mobile buttons not showing on mobile (IREF 18148, 19583)
- [x] Floating buttons are not displaying correctly: Top buttons are visible too much (TicketID 174065
), side buttons not visible (TicketID 177459) 
- [x] Mobile side floating buttons have opacity: 0 and z-index: [big number], blocking clicks below. 
- [x] Mobile float bar shows if set to "top" or "bottom", even if floating buttons are off. (IREF 19204)
- [x] Icon next to total shares is missing on floating buttons. See [screenshot](https://cloudup.com/cf8cmx2056m)

**Comment by Nicholas-Cardot** [comment]
This issue should now be fully solved.
