### ISSUE TITLE
Shortcode for Pinterest image

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#563]
# // **Notes for Testers** 

A long sought feature for Social Warfare, bloggers can now use the shortcode `[pinterest_image]` to place their Pinterst Image inline exactly where they want it to go. 

### What we want to happen: 
The admin can use the `[pinterest_image]` shortcode to insert an image. The optional parameter of ` id="3156" ` can be used to specify an image. 

If the image has a Social Warfare `data-pin-description`, the pin description will automatically be added to the image. 

Else, if the post has a Social Warfare Pinterest Description, that description will be added to the image. 

Else, we will use the image's alt text. 

### How to test: 
1. Go to an existing or new post. 
2. In the SW Metabox, add a pinterest image. 
3. Use the shortcode `[pinterest_image]` to place the pinterest image. 
4. View the post. 
5. (optional) Use the `id="x"` parameter, where X is the post id of an image to use. 

If the post has your pinterest image exactly where you put it, great, we are good to go. Hooray!
Else, please let us know what happened as a comment to this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

A user has requested a shortcode to place the pinterest image in the post content manually instead of above/below the content. This would likely be useful for a number of customers, especially if we included (optional) parameters for width, height, and alignment.

**Comment by Nicholas-Cardot** [comment]
What's the difference between this and simply adding an image to the post, which users can already do?

**Comment by nutsandbolts** [comment]
Because it adds the Pinterest data junk to the HTML instead of being just a random media upload.

**Comment by ckmahoney** [comment]
As far as I know, a shortcode would be less effective. The media uploader attaches all the standard attributes, and any other filtering is handled in other places.

**Comment by nutsandbolts** [comment]
¯\_(ツ)_/¯

**Comment by Nicholas-Cardot** [comment]
@ckmahoney I don't think they would need an ID. I think the shortcode would be 100% dependent on the Pinterest image field for the post.

So when processing the shortcode [pinterest_image] we would simply insert the Pinterest image for that post into that spot with the appropriate data-pin-description and whatnot filled out on it.

**Comment by Nicholas-Cardot** [comment]
Notes:

1. The data-pin-description is being output empty. Have it first look at the Pinterest Description meta field and then use the post title as a fallback.

2. Use that description to also populate the title and alt tag for the image.

3. Change "swp-image-wrap" on the div wrapper to "swp-pinterest-image-wrap"

4. Add a unique CSS class to the img itself.

**Comment by ckmahoney** [comment]
The default CSS class, if none is provided, is `swp-pinterest-image`.

**Comment by Nicholas-Cardot** [comment]
Also, go ahead and move all this to pro.
