### ISSUE TITLE
Update Compatibility With Yoast

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#564]
Instead of integrating with Yoast, we are now simply going to check if their OG tags or Twitter cards are turned on and if ours are also turned on. If so, we are going to display a notice to the user letting them know that they either need to turn ours off or turn theirs off.

    	if ( defined( 'WPSEO_VERSION' ) ) :

First check if Yoast SEO is active, also check if it is on version 7 or higher using a version check. Otherwise the OG and Twitter Card check functions won't exist. They were added in version 7.

You can then use the following methods to check for their OG and Twitter Card status:

`WPSEO_Options::get('opengraph')` and `WPSEO_Options::get('twitter')`

This should, I believe, be a non-dismissible notice. They will need to fix the issue, then the notice will go away.

**Comment by nutsandbolts** [comment]
So am I understanding correctly that we will no longer allow Yoast to output its tags when our custom options aren't filled in? For example, if I have 1000 posts and I just bought SW, I might want to use the Yoast tags for the old posts but use SW's from now on. 

LOTS of our customers do things this way - if they have to choose between losing all their existing OG data or adding it all back manually, that doesn't seem like much of a choice.

**Comment by ckmahoney** [comment]
True, we would like to remove Yoast as a dependency of our plugin. Instead, we will let users know that they need to either use our meta tags or use Yoast's meta tags. If both are active, we will display a notice telling them to turn one or the other off. Otherwise they will have two different sets of (potentially different) meta tags. @nutsandbolts

**Comment by Nicholas-Cardot** [comment]
This should now be fully resolved and should now continue to function as it has historically.
