### ISSUE TITLE
Ensure strings are UTF-8 encoded before being sent to network APIs.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#571]
# Notes For Tester

**What we want to happen:**
Using our Click To Tweet, or the Tweet button, should deliver the exact message Admin set, regardless of the language in which it was written.

## How to test

1. Choose either a click to tweet orCustom Tweet text (in the meta box) 
2. Populate the tweet text with non-latin characters. (See the next comment in this thread for some test text). 
3. Attempt to tweet the message using the Tweet button or the click to tweet that you created.
4. View the tweet on Twitter. The text should be exactly the same as you entered for the Click to Tweet. 

If the tweet shows up with non-Latin characters, nothing trimmed, then we should be good to go! 
If something goes awry, then please let us know as acoment to this issue. 

If the process is not clear or something does not make sense, please use Slack to ask questions. 

**End Notes for Testers** 
# 

TicketID 184726

Users who write in other languages, such as Arabic, need to have their text encoded in UTF-8. Otherwise the character length may not be properly counted and the text may be rejected. 

From Twitter: 
https://developer.twitter.com/en/docs/basics/counting-characters.html

This is particularly important as we move into more global markets whose native tongues use characters with varying byte lengths.

**Comment by ckmahoney** [comment]
Here are some test strings: 

```
// LTR
$japanese = "りトぴ動定へゃろご掲殉情づだに提刈拒禎阻か。資やへ掲責ご景制ぼをーが望治だふばん歳朝ケウ政教ニ囲主カヒヱ挙情むめびゅ氏3経地ラうぜ者護辺リエタヌ存八クき票備ぼも結誕よつト込亜才滅ょまい。18和ネ豊影ルコネラ圧知写だご阪強レカフ口8目摩ムヌ汁学ムタ芸紙展スばわこ点室アル上奏訳迷妻スで。";

$cyrillic = "Лорем ипсум долор сит амет, евертитур диссентиунт сит еа, сеа те аеяуе вереар. Ат лабитур цонституто интерпретарис сеа, ест не виртуте рецтеяуе, усу ет дицта граеце фиерент. Усу хабемус лобортис витуператорибус не, ноструд аццусата ин вим. Ан солум цонвенире про, евертитур делицатиссими еу меа. Вис ан дицо алияуам тхеопхрастус, видит натум сцрипсерит ат еам.";

// RTL
$arabic = "عل حلّت تكتيكاً مما, قام تجهيز الشهيرة التاريخ، أم. مئات كانت حين ان, و فقد قِبل بأضرار, عن حدى ببعض بمعارضة. أم بحق وحتّى موالية بتخصيص. ٣٠ بشكل سليمان، بالمطالبة ولم, أن جنوب أمّا الا. الضغوط مليارات المتحدة ذلك كل, الى زهاء بخطوط التغييرات ان. تعداد الحكم يتم في.";

$hebrew = "של עזה מיזם לציין אדריכלות, ליום ל ההפוך המקושרים צעד אם. מה ראשי ישראל מוסיקה צ'ט, בקר את יוצריםגולשות ואלקטרוניקה. בדף בה עמוד פוליטיקה. על עוד מתוך שפות, ברית ובמתן תחבורה אנא את, עזרה המלצת משפטית צ'ט מה. אל כלל בארגז אנציקלופדיה, ישראל עקרונות אל תנך.";
```

**Comment by ckmahoney** [comment]
Notes

`get_bloginfo( "charset" )` will return the encoding for pages and feeds. 
https://developer.wordpress.org/reference/functions/get_bloginfo/

`mb_convert_encoding( $string, $to_encoding, $from_encoding )`
http://php.net/manual/en/function.mb-convert-encoding.php

`utf8_uri_encode( $utf8_string, $max_length )`
https://codex.wordpress.org/Function_Reference/utf8_uri_encode

So maybe if we did something like : 
```
$site_encoding = get_bloginfo( "charset" );

// filter $site_encoding to match a valid PHP encoding constant name

$converted_string = mb_convert_encoding( $string, 'UTF-8', $from_encoding )

$tweet = utf8_uri_encode( $utf8_string, $max_tweet_length );
```

**Comment by Nicholas-Cardot** [comment]
Here's the real kicker. Once it gets passed over to Twitter, how will Twitter know what encoding the text is in?

**Comment by ckmahoney** [comment]
Twitter expects UTF-8. 
https://developer.twitter.com/en/docs/basics/counting-characters.html

**Comment by ckmahoney** [comment]
So, we are fortunate to know that the output must be UTF-8. We are (hopefully) fortunate that the `get_bloginfo( "charset")` will tell us which encoding we are coming from.

**Comment by Nicholas-Cardot** [comment]
Yes, and without knowing what we are coming from, the mb_convert_encoding will be somewhat useless. So this is likely a great solution.

**Comment by ckmahoney** [comment]
I have to wonder though, how does WordPress interact with the Database? I know information can be stored in many different types of encoding in the db. I always set mine to `utf8_general_ci`, but that does not mean the world does. 

Does WP translate what is stored to the site's preferred encoding, or is the site's encoding the same as the DB's encoding?

It will be in our interest to set up new sites in different languages. And if possible, setup new databases in different encodings. 

And hopefully get a lot of international beta testers.

**Comment by Nicholas-Cardot** [comment]
Updated with some notes for testers. Should be a super easy one to test. Just make a tweet with some non-latin characters and attempt to tweet it.
