### ISSUE TITLE
Mobile Button Issues

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#572]
# // **Notes for Testers** 

Unfortunately for the 3.1.1 release, there was a small javascript error that flooded us with messages about the floating buttons and mobile buttons not working. 

It's a bit like when one bulb blows on a string of lights, they all blow out. One error in a Javascript module breaks the rest of that module. Depending on the way scripts are bundled, the module could mean all javascript running on the front end. 

### What we want to happen: 
Seamless, full functionality of the webpage when mobile or floating buttons are on the screen. Mobile and floating buttons should behave as they are told to do in the Social Warfare settings.

### How to test: 
It would be tedium _ad infinitum_ to test all configurations of mobile and floating buttons per user. 
Instead, just use the settings you have. If everything checks out, change a few things and try again. Do this as long as you want. 

If there is ever a javscript error, or some kind of functionality breaks (ours or some other plugin), please let us know in a comment below.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

1.  [x] 1. Does not display on core-only, no pro. 
TicketID 185839

The 50px padding is created at the top of the post only when at the top of the post. When scrolling through the content, the bottom floating buttons are not visible. 

<hr/>

2. [x] 2. Mobile buttons switch more than once to responsive mode. 
TicketID 186536
https://youtu.be/-py1S1uFBpA

Floating buttons: Bottom
Mobile floating: Top

Notice that as he minimizes the window, the floating buttons jump from bottom to top to bottom to top. This jump should happen a maximum of 1 time, iff the mobile location is different than floating location. 

<hr/>

3. [x] 3. Not visible On Mobile 
TicketID 187135

To get the bottom-floating buttons visible, I had to give the client the css `.nc_wrapper: bottom 80px !important` because the bottom floating buttons were below the fold. 

*This may be an edge case*. I was not able to replicate the issue, nor have I seen it on other sites. 

<hr/>

4. [x] 4. Side floating (incorrectly) trumps bottom bar
TicketID 186787
https://www.perfectleap.com/healthcare-business-data-storage

Floating buttons: left
Mobile float: bottom

 On a mobile view, the side floating buttons persist and cover up the content. The bottom floating buttons exist but are not being toggled. 

<hr/>

5. [x] 5. When floating buttons are set to top, mobile floats to bottom instead. 

Need to make sure that the mobile buttons have the same position as the floating bar. 

<hr/>

6. [x] 6. On mobile, side floating buttons are shown when top bar should be shown. (See comment below)
TicketID 191123

**Comment by ckmahoney** [comment]
6.  [ ] 6. On mobile, side floating buttons are shown when top bar should be shown. 
TicketID 191123
www.parkedinparadise.com
```
array (
  'location_archive_categories' => 'below',
  'location_home' => 'none',
  'location_post' => 'above',
  'location_page' => 'none',
  'total_shares' => true,
  'network_shares' => false,
  'twitter_id' => 'parkedparadise',
  'twitter_cards' => true,
  'button_shape' => 'flat_fresh',
  'default_colors' => 'full_color',
  'single_colors' => 'full_color',
  'hover_colors' => 'full_color',
  'float_default_colors' => 'full_color',
  'float_single_colors' => 'full_color',
  'float_hover_colors' => 'full_color',
  'float_style_source' => true,
  'button_size' => '1',
  'buttonFloat' => 'full_width',
  'transition' => 'slide',
  'float_screen_width' => '700px',
  'ctt_theme' => 'style1',
  'twitter_shares' => false,
  'floating_panel' => true,
  'floatOption' => 'bottom',
  'float_background_color' => '#ffffff',
  'float_button_shape' => 'boxed',
  'custom_color' => '#000000',
  'custom_color_outlines' => '#000000',
  'recover_shares' => false,
  'recovery_format' => 'unchanged',
  'recovery_protocol' => 'unchanged',
  'recovery_prefix' => 'Unchanged',
  'decimals' => '1',
  'decimal_separator' => 'period',
  'totals_alignment' => 'totals_right',
  'google_analytics' => true,
  'dashboardShares' => true,
  'bitly_authentication' => false,
  'minimum_shares' => '25',
  'cache_method' => 'advanced',
  'full_content' => false,
  'rawNumbers' => false,
  'notShowing' => false,
  'visualEditorBug' => false,
  'loopFix' => false,
  'frame_buster' => false,
  'analytics_medium' => 'social',
  'analytics_campaign' => 'SocialWarfare',
  'swp_click_tracking' => true,
  'order_of_icons_method' => 'manual',
  'pinit_toggle' => true,
  'pinit_location_horizontal' => 'left',
  'pinit_location_vertical' => 'top',
  'pinit_min_width' => '200px',
  'pinit_min_height' => '200',
  'pinit_image_source' => 'image',
  'pinit_image_description' => 'custom',
  'utm_on_pins' => true,
  'pin_browser_extension' => false,
  'pinterest_image_location' => 'hidden',
  'pinterest_fallback' => 'all',
  'emphasize_icons' => 0,
  'floatLeftMobile' => 'bottom',
  'force_new_shares' => false,
  'order_of_icons' => 
  array (
    'facebook' => 'facebook',
    'pinterest' => 'pinterest',
    'twitter' => 'twitter',
    'google_plus' => 'google_plus',
    'reddit' => 'reddit',
  ),
  'swp_og_type_page' => 'article',
  'swp_og_type_post' => 'article',
  'single_custom_color' => '#000000',
  'locationattachment' => 'none',
  'locationrevision' => 'none',
  'nav_menu_item' => 'none',
  'shop_order' => 'none',
  'shop_order_refund' => 'none',
  'shop_coupon' => 'none',
  'shop_webhook' => 'none',
  'float_location_page' => 'on',
  'float_location_post' => 'on',
  'yummly_categories' => '',
  'yummly_tags' => '',
  'pinterest_id' => 'parkedinparadise',
  'facebook_publisher_url' => 'https://www.facebook.com/parkedinparadise/',
  'facebook_app_id' => '2007952562785868',
  'recovery_permalink' => '',
  'recovery_subdomain' => '',
  'former_domain' => '',
  'current_domain' => '',
  'tweet_count_source' => 'opensharecount',
  'og_tags' => true,
  'button_alignment' => 'full_width',
  'float_location' => 'left',
  'float_alignment' => 'center',
  'float_size' => '0.8',
  'float_mobile' => 'top',
  'float_button_count' => '',
  'float_custom_color' => '',
  'float_custom_color_outlines' => '',
  'ctt_css' => '',
  'og_page' => 'og_article',
  'og_post' => 'og_article',
  'click_tracking' => false,
  'last_migrated' => '3.0.5',
  'float_before_content' => false,
)
```

**Comment by Nicholas-Cardot** [comment]
I believe that 6 was caused by a JS error that has now been fixed.

**Comment by nutsandbolts** [comment]
`Uncaught TypeError: Cannot read property 'indexOf' of undefined` on line 334 with the latest changes to testing
