### ISSUE TITLE
Floating buttons don't show until bottom of content

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#573]
# // **Notes for Testers** 

Visitors should only see share buttons when the blogger says they should. 

### What we want to happen: 
If Float Before Content is enabled, we should see buttons as soon as the page loads. The buttons are always visible, even before we have reached the post content. 

If it is disabled, we should have buttons that only appear once the author's content is present on the screen. This is the default behavior. 

### How to test: 
Social Warfare -> Styles -> Floating Share Buttons : 

1. Make sure "Floating Share Buttons" is on.
2.  Set "Float Position" to "left" or "right".
  > (optional) this will make it easier to see.
3. Set "Float Before Content" to ON.
4. Click "Save Changes". 
5. Visit a post. Do the buttons behave according to the description above? 

If everything goes as described, hooray! We are good to go. 
If something is contrary to what we describe, please let us know in a comment to this issue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

If your settings are configured as follows, the result is that your floating buttons do not show until the bottom of the content: 

- Position: Below the content
- Float before content: OFF

This should not be the case. Buttons should show immediately after the start of the content even if static buttons are only at the bottom (or there are no static buttons whatsoever).

Nick: Target the first parent of the social panel. This will be the content div container. Use the jQuery.top() or whatever to locate the top of the content. Make this content dependent, not just panel dependent.

**Comment by ckmahoney** [comment]
This is contrary to the description found at https://warfareplugins.com/support/options-page-styles-tab-floating-share-buttons: 

> **Float Before Content:** Turn this option on if you want the floating buttons to appear before the first set of static horizontal buttons.
> Turn this option off if you want the floating buttons to appear only after a set of static horizontal buttons has been shown.

As per this description, the behavior is as expected.

**Comment by ckmahoney** [comment]
Although the description's title is contrary to itself. Either it should say 

Float Before Buttons: Turn this on...

or 

Float Before Content: ... show before the_content ...

**Comment by DustinWStout** [comment]
@ckmahoney all that shows is that the description was written under the assumption that everyone wants buttons above the content. This was a wrong assumption. 

The function should follow this description: 

> **Float Before Content:** Turn this option on if you want the floating buttons to appear before the beginning of the page content (aka `the_content()`).

**Comment by Nicholas-Cardot** [comment]
@ckmahoney 

1. Use jQuery/JS to target the first parent of our social panel. This should be the container their theme uses to store the content. 
2. Get the location of the top of that container. 
3. Use that information/variable in the existing conditional. 
4. Update the description in the docs.
5. Close this issue or tag it as ready for testing.

**Comment by JasonWiser** [comment]
tested. works
