### ISSUE TITLE
Improve the Addon update installation process. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#575]
# // **Notes for Testers** 

### What we want to happen: 
On your Plugins page, you see an update is available for Social Warfare Pro.
You click "Update plugin". 
It updates, we're done. 

### How to test: 
As soon as you install the testing version of Social Warfare and Social Warfare Pro, your version numbers will be at the newest version, so WordPress will think everything is up-to-date. 

We need to make WordPress think that an update is available. To do this, we will manually change the version number to something lower. 

Open the file **social-warfare-pro.php**. On line 6 and line 19 you can see where we set the version number. Change it to the following: `2.0.0`. It is important to have three digits separated by two decimal points, in the form of `x.y.z`. 

Save the file, then go to the Plugins page again (or reload if you were already there). 

It should say an update is available. 

Press "Update Now". If everything is good, hooray! That's good. 
If anything seems out of place or does not go as expected, please add a comment to this thread  so we can jump on it. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

Right now, as of v3.1.1, many users face difficulties and inconveniences when updating from one version of Social Warfare Pro to the next. They are forced to deactivate, delete the old copy and upload, install, and activate the new copy. 

We would like the admin to see the update notification, click "Update", and have the plugin seamless updated, just as they do with any other premium plugin. 

Currently we are waiting on a response from Easy Digital Downloads. We would like to force their update checker to always return true and allow the admin to update, even if their copy of Pro is not active or up to date. 

Other things we can consider:

Do not disable Pro features when the updates are out of sync. 
This is reasonably doable: Any part of core that runs Pro code will need to check the Pro version number to make sure the feature exists. The Pro plugin will always be as up to date with itself, so it will not need to perform these checks.

Do an update check ourselves. If an update is required, install the files ourselves with server-side code. 
This is doable, but not an ideal approach. We would prefer to use WordPress native upload/install/update features.

**Comment by ckmahoney** [comment]
To test this: 

You do not have to install previous version of Pro. The only thing you need to do is change the version number in the following places: 

**social_warfare_pro.php**
[L6](https://github.com/warfare-plugins/social-warfare-pro/blob/b31358610b66fb620e5419da3729e1249fee3d1d/social-warfare-pro.php#L6)
[L19](https://github.com/warfare-plugins/social-warfare-pro/blob/b31358610b66fb620e5419da3729e1249fee3d1d/social-warfare-pro.php#L19)

As long as the version number is below 3.1.1 (the current version number for SWP), you should get the update notice and the option to update from within the dashboard. If you do not, reply to this thread and please try clearing your server cache. 

@nutsandbolts 
@DustinWStout

**Comment by ckmahoney** [comment]
# // **Notes for Testers** 

### What we want to happen: 
On your Plugins page, you see an update is available for Social Warfare Pro.
You click "Update plugin". 
It updates, we're done. 

### How to test: 
As soon as you install the testing version of Social Warfare and Social Warfare Pro, your version numbers will be at the newest version, so WordPress will think everything is up-to-date. 

We need to make WordPress think that an update is available. To do this, we will manually change the version number to something lower. 

Open the file **social-warfare-pro.php**. On line 6 and line 19 you can see where we set the version number. Change it to the following: `2.0.0`. It is important to have three digits separated by two decimal points, in the form of `x.y.z`. 

Save the file, then go to the Plugins page again (or reload if you were already there). 

It should say an update is available. 

Press "Update Now". If everything is good, hooray! That's good. 
If anything seems out of place or does not go as expected, please add a comment to this thread  so we can jump on it.

**Comment by scottwyden** [comment]
I'm not able to update.  Here is a video showing: https://www.useloom.com/share/1d1043e2c0d64e8db9b3fbb05a0376c5 Let me know if you'd like me to do anything to help troubleshoot this.

**Comment by Nicholas-Cardot** [comment]
@scottwyden We haven't moved this fix into the testing branch yet. We will be moving it to the testing branch by close of business tomorrow afternoon. We have internal beta testing scheduled to run from Monday through Friday or next week and public beta testing scheduled to run Monday through Friday the week following.

Once this is moved to the testing branch, you'll need to download both core and pro from the testing branch of these repositories, rename the zip and the folder inside the zip to remove the testing branch name, and install that version to test if this has been fixed or not.

I hope that helps!

Additionally, here's a public calendar that I've created so that you can see when we are moving things onto the testing branch: https://calendar.google.com/calendar?cid=c2l0ZXNrZXRjaDEwMS5jb21fb3RrOHJyb2FwNnE1ZHBxc2pxMGc4YWVhYmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by scottwyden** [comment]
Oh I see. Thanks!

**Comment by JasonWiser** [comment]
does not work.
I followed the directions exactly, and I get "Download failed. Unauthorized."
![2018-08-10_114116](https://user-images.githubusercontent.com/18461953/43967502-85a4844c-9c92-11e8-9455-4f73fbdaca1b.jpg)

**Comment by JasonWiser** [comment]
tested. works.
done. (that _was_ magic!)

**Comment by meymigrou** [comment]
Tested and it's working!
