### ISSUE TITLE
Custom Color text color is being overwritten by theme.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#577]
# // **Notes for Testers** 

Custom Colors help the buttons panel fit in with the admin's theme. Sometimes the theme is a little aggressive with its CSS and ends up discoloring our button text.

### What we want to happen: 
An admin sets a custom color or custom color outline. 
That color gets used for the button background (or outline), and an easy-to-see white text color is used for the buttons. 

### How to test: 

In Settings -> Styles -> Visual Options : 
1. For any of the Default, Hover, or Single color hover dropdowns, select "Custom Color" or "Custom Color Outlines"
2. Enter a valid hex color code. Eg, #a9cc33
3. Press "Save Changes"

The buttons should now reflect the color you set in step 2. The text of the buttons must be white. If the button text is anything but white, please let us know in a comment to this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

We have seen a few cases where a custom color buttons panel is all one color. This happens when a theme styles all <a> tags to a specific color, then the admin uses that same color code for the custom color.

We have styled the color to be white, but since the theme sometimes overrules our style, we need to add !important declarations to each of the custom color options.

**Comment by nutsandbolts** [comment]
But if they are using custom outlines we don’t want white icons, so we need to figure out a way to make the CSS more specific.

**Comment by ckmahoney** [comment]
Good catch. We'd apply the same !important to the custom color outlines text as well. This is what the code looks like before. From [line 758 in SWP_Pro_Header_Output](https://github.com/warfare-plugins/social-warfare-pro/blob/b22b5839afb583b17447ce4b70ae421d448e0aeb/functions/frontend-output/SWP_Pro_Header_Output.php#L758)


`"{color:" . $custom_outlines . " }"`

and after:

`"{color:" . $custom_outlines . "  !important}"`

**Comment by Nicholas-Cardot** [comment]
@HeatherKWiser Right now, we haven't built in the ability for the preview to show the "Custom" color options. It only shows all the other ones. This is something we are hoping to add in 3.3 next month. Also, it ONLY shows a preview for the "Visual Options" and not the button order, though that is a really good idea. I think I might just add that to the list to make it do that in the future.

**Comment by HeatherKWiser** [comment]
after following your test instructions, this is the result, back end set up and front end result
![2018-08-09_1631](https://user-images.githubusercontent.com/42214327/43931242-6cf67928-9bf2-11e8-90aa-a31501bc546e.png)
![2018-08-09_1635](https://user-images.githubusercontent.com/42214327/43931249-72231d2a-9bf2-11e8-89dc-098350672a32.png)

**Comment by Nicholas-Cardot** [comment]
@HeatherKWiser If you look at the first screenshot of the two in the comment above, you'll see at the bottom there is a popup message. It states that the preview does NOT reflect the custom colors.

The underline and the icons/text being purple on a purple background means that your theme is overruling the text color. We will look into seeing if there is an effective way to force those to work properly when using a custom color. It shouldn't be too difficult to accomplish. Thanks for bringing that one to our attention.

**Comment by HeatherKWiser** [comment]
sorry Nick, I saw the pop up after all the screen caps were made. Also - that pop up is stuck. see below.
![2018-08-09_1651](https://user-images.githubusercontent.com/42214327/43931742-fcc2729e-9bf4-11e8-8e34-62c3c52ee552.png)

**Comment by HeatherKWiser** [comment]
I did get it to leave with a refresh of the page. just FYI

**Comment by JasonWiser** [comment]
tested. Color is changing as it should for both buttons.
