### ISSUE TITLE
Buttons do not display after "post_updated" fires. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#578]
# // **Notes for Testers** 

### What we want to happen: 
After a post is published or updated, the next person to view the post should see a complete set of Social Warfare buttons. 

### How to test: 
1. Go to an existing or new post. 
2. Click "Update Post" or "Save Post"
3. In a new tab, view the post. 
4. Open a new tab to the same post.  
5. Do they have the same buttons panel? 

**Note** If you are testing on a high traffic site, please use an old post that is not likely to be visited by others during your test. 

If the buttons are the same, we are good to go, hooray!
Else, please let us know what happened as a comment to this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

I have noticed during development that if I click "Update Post" to an existing post, the next pageload for that post does not display any buttons. It does display the total shares count. 

On refresh, the buttons display as normal. 

In a production environment, this is probably going to go unnoticed as it would most often affect one person one time, unless the admin is frequently updating the post. Nonetheless, we do not want it to be happening at all.

**Comment by ckmahoney** [comment]
When the network does not have any shares saved in the post meta, it will display after 'post_updated'. 

For example, I added Pinterest to my buttons. Pinterest has no shares for "Hello World". I click update post, visit "Hello World," and my Facebook and LinkedIn buttons are gone, but I see Pinterest. I refresh the page, and my buttons panel has all three: Facebook, LinkedIn, and Pinterest.

**Comment by ckmahoney** [comment]
At the time of issue creation, the described behavior happened consistently. 

I can no longer replicate this issue. While we did not specifically target this during development, other patches may have fixed this bug.

**Comment by Nicholas-Cardot** [comment]
I agree. I think this has been resolved. Let's tag is as "Ready for Testing" and revisit it only if anyone is able to replicate this issue again.

**Comment by Nicholas-Cardot** [comment]
So it sounds like it was hiding/showing certain buttons but only on the page load where the cache was being rebuilt. Can you replicate this by using the cache rebuild URL parameters?

**Comment by JasonWiser** [comment]
tested. works
