### ISSUE TITLE
What's with the shadow bellow the sharing buttons?

### ISSUE THREAD

**Issue by meymigrou** [warfare-plugins/social-warfare#580]
I've just noticed a shadow bellow the sharing buttons on Social Warfare v.3.1.1. This is in my test blog, with the stable release I don't see any shadows.

![social-warfare-sharing-buttons-shadow](https://user-images.githubusercontent.com/30810726/42981997-dc63f7ce-8be7-11e8-84a6-1f7734af96fa.png)

P.S. Sorry if you already knew about it or someone else already posted it.

**Comment by DustinWStout** [comment]
Hi, @meymigrou! Some themes put a `border-bottom:` on links, and that looks like exactly what's happening there. Change to a different theme to see the border is probably gone. 

Easy css fix is to add the following to your theme: 

```a.nc_tweet { 
border-bottom: none !important; 
}```

Might not work with every theme perfectly, but if you submit a support ticket, we can inspect it directly and give you a sure fix.
