### ISSUE TITLE
Beta Test Comments/Issues

### ISSUE THREAD

**Issue by joetracy** [warfare-plugins/social-warfare#583]
- Display > Position Share Buttons > Home > Above (or Above and Below) > Save > Reload Home Page > No Buttons > Try Different Browser > No Buttons > Clear Cache > No Buttons (this is for the home page, right?)
- Same as above, but for Archive & Categories.
- When you change EXCERPT to FULL CONTENT, then the BELOW shows on Home page (for the post on the Home page) and Archive.
- Registration > Social Warfare Registration > Click with no info entered > Failure Message > OK > SUCCESS (?) message displays.
- Everytime you click Save Changes, it first briefly shows the red X fail box before showing the Success box.

Other Notes
- Also tested all graphic/text/info links to Website - worked great!
- I have PRO installed, but can't test it because beta key for pro license wasn't included in beta test email.
- When having issues with the HOME and ARCHIVE & CATEGORIES (Display), I clicked the "i" button, but it says nothing in your help section about the Home and Archive & Categories display.

SYSTEM STATUS

WordPress Version | 4.9.7
-- | --
PHP Version | 5.6.36
WP Memory Limit | 40M
Social Warfare Version | 3.1.1

If there is a different format you would like me to use for these beta test notes, let me know and I'll use it. As a first time Social Warfare beta tester, I want to make sure I'm doing it in a way that best works for you. - Joe

**Comment by Nicholas-Cardot** [comment]
Ha ha. No worries. You want to go ahead and copy/paste your notes above into a comment on that issue and then we can close this one out.

**Comment by joetracy** [comment]
I have the content copied, so feel free to close this one out. Thank you for being so cool about it - much appreciated.

**Comment by Nicholas-Cardot** [comment]
Oh yeah, no worries. :-)
