### ISSUE TITLE
Don't Fetch Share Counts if Counts are Turned Off

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#585]
# // **Notes for Testers** 

Our plugin automatically updates the share counts based on a schedule. 

New posts (less than 3 weeks old) check for updates up to one time every 1 hour. 
Mid aged posts (less than 60 days old) check for updates up to one time every 4 hours.
Old posts check for updates up to one time every 12 hours. 

Some people do not want to use the share count feature, so we can bypass all of the above checks and save server resources. 

### What we want to happen: 
The admin decided not to display share counts or total shares, so no network requests should be made. 

### How to test: 

In Settings -> Display -> Share Counts :
1. Set "Button Counts" to "OFF"
2. Set "Total Counts" to "OFF" 
3. Press "Save Changes"

Then, you can use this query parameter to see if we are fetching counts: 
`?swp_cache=rebuild`

Copy this text and paste it at the end of your site's url. So for http://example.com/hello-world, it would like like this: 

https://example.com/hello-world?swp_cache=rebuild

If the admin settings are correct and there are no bugs, you should get this message at the top of  the page or before the content: 

>No Shares Fetched. Share counts are disabled in the settings.

(Protip: `ctrl + f` or `cmd + f` for a keyword in this phrase to easily see if it got printed.)
 
If you encounter something contrary to the above, please reply to this thread. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

Make it so that the Post_Cache->rebuild_share_counts() doesn't run if both share counts (individual and total) are turned off.

**Comment by JasonWiser** [comment]
I followed the instructions and it crashed my site. 
I deactivated the plugins and the site came back

**Comment by JasonWiser** [comment]
[08-Aug-2018 15:47:00 UTC] PHP Fatal error:  Uncaught Error: Class 'SWP_Plugin_Updater' not found in /home/ontrackt/public_html/wp-content/plugins/social-warfare-pro/functions/Social_Warfare_Pro.php:146
Stack trace:
#0 /home/ontrackt/public_html/wp-content/plugins/social-warfare-pro/functions/Social_Warfare_Pro.php(17): Social_Warfare_Pro->update_checker()
#1 /home/ontrackt/public_html/wp-content/plugins/social-warfare-pro/social-warfare-pro.php(30): Social_Warfare_Pro->__construct()
#2 /home/ontrackt/public_html/wp-includes/class-wp-hook.php(286): initialize_social_warfare_pro('')
#3 /home/ontrackt/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /home/ontrackt/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /home/ontrackt/public_html/wp-settings.php(327): do_action('plugins_loaded')
#6 /home/ontrackt/public_html/wp-config.php(97): require_once('/home/ontrackt/...')
#7 /home/ontrackt/public_html/wp-load.php(37): require_once('/home/ontrackt/...')
#8 /home/ontrackt/public_html/wp-cron.php(33):  in /home/ontrackt/public_html/wp-content/plugins/social-warfare-pro/functions/Social_Warfare_Pro.php on line 146

**Comment by HeatherKWiser** [comment]
I turned off button counts and total counts and saved. I then followed the instructions to query.
I do not see the text anywhere on my page.
I have used ctrl +F to find "fetched" on the page. Nothing.

Not sure it worked as expected.
sorry

**Comment by JasonWiser** [comment]
I tested, 
No text on the page
