### ISSUE TITLE
Remove the Newsharecount.com from the options.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#587]
# // **Notes for Testers** 

### What we want to happen: 
When selecting which service to use for Tweet Count registration, you should no longer see New Share Counts as an option. If you previously had New Share Counts as your service, the "Tweet Counts" switch should be set to OFF.

### How to test: 
In Settings -> Social Identity -> Tweet Count Registration :
1. You should see no reference to New Share Counts at all. 
2. If you were using OpenShareCounts, you are done. 
3. If you were using NewShareCounts, make sure that "Tweet Counts" switched itself to "OFF".

If you encounter something contrary to the above, please reply to this thread. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

**Comment by JasonWiser** [comment]
tested. works.
