### ISSUE TITLE
Add support for Twitcount.com share counts for Twitter

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#588]
# // **Notes for Testers** 

This item requires Pro is installed. 

### What we want to happen: 
When selecting which service to use for Tweet Count registration, you are able to enroll in TwitCount and tweets counted for www.yoursite.com. 

### How to test: 
In Settings -> Social Identity -> Tweet Count Registration :
1. Click the button that says "Click here to visit TwitCount.com"
2. Make sure "Tweet Counts" is set to "ON"
3. Set "Tweet Count Source" to "TwitCount.com" 
4. Press Save Changes

On your frontend, visit a few blog posts. Write down the number of twitter shares it has. 
Tweet it. Tweet the same post multiple times if possible. 
Check back 24 hours later. 

If the shares counts have increased, we are good! 
If not, please paste links to the stuck counters as a comment to this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

**Comment by JasonWiser** [comment]
it is not intuitive what aI am supposed to be doing once I press the Twitcount button.
[BUG] need to rename the dropdowns to Twitcount.

**Comment by HeatherKWiser** [comment]
testing this and I am kind of stuck at this point...I followed the instructions, got to this part "Click here to visit TwitCount.com" so I am on this site, registered (signed up) and now it is asking me to customize my button. which do I choose?
see image below:
![2018-08-09_1643](https://user-images.githubusercontent.com/42214327/43931497-7fe9d772-9bf3-11e8-931a-77229ca75e9d.png)

**Comment by agnelvishal** [comment]
> testing this and I am kind of stuck at this point...I followed the instructions, got to this part "Click here to visit TwitCount.com" so I am on this site, registered (signed up) and now it is asking me to customize my button. which do I choose?
> see image below:
> ![2018-08-09_1643](https://user-images.githubusercontent.com/42214327/43931497-7fe9d772-9bf3-11e8-931a-77229ca75e9d.png)

Click "Continue" button

**Comment by Nicholas-Cardot** [comment]
you're not usin their button. Your usin ours. So just skip throuh that part.
