### ISSUE TITLE
Build a class to manage the swp_user_options global array more effectively.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#590]
# **Notes for Testers** 

### What we want to happen: 
When going from an addon (e.g. Pro) we need the plugin to keep the user's addon settings in the database, but only display Core settings. 

## How to test

This has two sides to test: Going from an Addon down to Core, and going from Core back to the Addon. "Pro" is a suitable addon to test with. This will be the addon we reference through the notes.

### Step 1: Enable Pro options. 

1. Make sure you start with Pro registered. 
2. Update the settings to use Pro options.
> The easiest to test are Social Warfare -> Styles ->  Visual Options. Change them so they are **not** "Flat & Fresh" or "Full Color".
3. Click Save Changes. 

### Step 2: View the Post

1. Open a new tab, and view a post with the buttons. They should look as you set them. 
2. Keep this tab open, and do not refresh it later. 

### Step 3: Unregister the Addon

1. Return to your Settings tab, and go to the Registration section. 
2. In Social Warfare - Pro Registration, click "Unregister Plugin." 
3. After it takes you to the Display tab, reload your page.
 > It takes one extra pageload for the options to update.  
4. Open the test post again in a new tab. The Pro styles should have been reset to default Core styles (Flat & Fresh, Full Color). 

Any other settings that were Pro should also have been reset. 

This is the first of two checkpoints. If something has gone wrong, please let us know as a comment on this issue. Otherwise, please proceed to step 4. 

### Step 4: Re-register the Addon

1. Grab your license key. You can get it from https://warfareplugins.com/my-account/license-keys
2. Go to Social Warfare -> Registration
3. Enter your license key. 
4. Press "Register Plugin."
5. After it takes you to the Display tab, reload your page.
6. Open the test post in a new tab one more time. This should be the third tab you have opened for the same post. 

All Social Warfare features in the first and third tab should be exactly the same. 
The second tab, when the addon was unregistered, should only have Core features. 

If this is true, then we should be good to go! 
If not, please try refreshing the third tab a few times. If it still doesn't match the first tab, let us know what was not the same as a comment on this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 
**end notes**

#

## Problem

If a user has previously made changes to styling that are only available in Pro, but they downgrade to only Core, their styles **should** revert to a standard style. Instead, this is what happens (no styling): 

<img width="865" alt="screen shot 2018-07-27 at 10 40 04 am" src="https://user-images.githubusercontent.com/2152604/43337766-9442d79c-9189-11e8-982d-32a86d0de638.png">

We've seen many support tickets come in about this, and while it's easy to explain, would save us a TON of time in support if the plugin just reverted to default styles.

Important: This needs to happen on output only and not in the database. Otherwise people will immediately lose their settings during updates, if they manually uninstall/reinstall, etc. So keep the settings in the database the same, but filter non-existent options when they're pulled out of the database.

## Solution 

We are going to create a class to manage the creation of the $swp_user_options global array.

This class will contain methods that capture all of the available options, values for those options, and defaults for those options. We will then store those options in the database which will make them available very, very early in the loading process. This will allow us to use them to filter the $swp_user_options array to make sure that it only contains options that are indeed still available, only uses values that are indeed still available, and if an option doesn't exist in that array, it will add it using the default.

**Comment by ckmahoney** [comment]
I think that should do it.
Added notes for testers. This is ready for testing.
