### ISSUE TITLE
Make the shortcode accept a URL instead of an ID.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#591]
# **Notes for Testers** 

You can now use a permalink for the shortcode. It must be a permalink on the same domain. External sites and subdomains will not work, but query parameters should be fine.

### What we want to happen: 
When using the `url` attribute on our shortcode, sharing from the buttons panel will share the page you linked instead of the current page. 

## How to test: 

1. Copy the URL for a post or page. 
2. On the same site, go to the post editor for a different post or page. 
3. Use the shortcode in the following format: 
`[social_warfare url="https://example.com/different-post"]`
where you replace the value of the shortcode with the URL in step 1. 
4. Click "Save Changes"
5. View the post on the front end.
6. When you click a share button from the shortcode panel, does it pull up data from the linked URL?

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**end notes**
#
This can be accomplished by having the shortcode handler method convert the URL to an ID prior to instantiating a buttons panel.

https://developer.wordpress.org/reference/functions/url_to_postid/

```
if( !empty( $args['url'] && empty( $args['id'] ) ):
    $post_id = url_to_postid( $args['url'] );
endif;
```

- [x] Make it so that if both are added, the ID will trump the URL.
- [x] Make it check to see if an ID was returned from the function. Return if not.

**Comment by ckmahoney** [comment]
This has been noted and is ready for testing.

**Comment by DustinWStout** [comment]
Not working at all.

**Comment by ckmahoney** [comment]
Can you please specify which post you tried it on, and the post to which you tried getting display data for? 

Note that it has to be a link on the same domain.

**Comment by Nicholas-Cardot** [comment]
This conversation was discussed further in slack to get more guidance. We have made commits relevant to the bugs identified by @DustinWStout above and this should not be fully fixed on the testing branch.

**Comment by coreyzev** [comment]
Tested. While the URL is working as intended. The ID is not taking priority over the URL when both are included.
