### ISSUE TITLE
Make Pro no longer depend on checking what version core is on.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#592]
# **Notes for Testers** 

Our plugin has previously been incompatible with itself when Core and Pro are on different versions. We now would like the plugin to be backwards compatible with itself. 

### What we want to happen: 
You should be able to use any version Pro v 3.3.0+ with any version of Core 3.3.0+. (3.2.90+ in testing).

So the solution that we had to go with will not allow us to make the plugin compatible with old versions of the plugin. However, we have made it so that once upgraded to 3.3.0 (3.2.90+ in testing), the versions will no longer need to match as long as both version are greater than 3.3.0. 

This version mismatch incompatibility will therefore become more and more irrelevant as we move forward above and beyond the 3.3.0 release.

### How to test: 

1. Install the current testing versions of Pro and Core from the testing branch.
2. Open social-warfare.php in the top level directory of the Social Warfare core plugin.
3. Change the version number on line 6 and line 19 to anything equal or greater than 3.3.0. Whatever version you pick, use the same version on both lines.
4. The plugins will now believe that they are on two different versions but all pro features should continue to work.

**End of Notes for Testers**
#

We need to go through pro file by file and find every time something from core is called. If a class is instantiated or extended or if a function/method is called, we need to wrap it in a check for existence. 

So when the main class is created, for example, we'll check for the class being extended:

```
if( class_exists('SWP_Addon') ):
    class Social_Warfare_Pro extends SWP_Addon {
    }
endif;
```

This will make it so that 99% of features will still be able to function properly even when the versions are mismatched.

Make sure that everything in 3.2 dev branch is merged into 3.3 before and while working on this, but don't let anything from the 3.3 dev branch leak into 3.2 or into the testing branch.

**Comment by ckmahoney** [comment]
Notes for testers have been written. This is ready for testing.

**Comment by JasonWiser** [comment]
1. I had 3.2.91 core and pro installed
2. I deactivated and deleted 3.2.91 core
3. I got the alert "You have pro but you need to have core installed" [paraphrase]
4. I installed 3.0.1 core
5. the site went 500 / had to delete 3.0.1 from cPanel
6. installed 3.0.5 core
7.  the site went 500 / had to delete 3.0.5 from cPanel
8. installed 3.0.9 core
9. the site went 500 / had to delete 3.0.9 from cPanel
10. downloaded 3.2.2 core
11.  the site went 500 / had to delete 3.2.2 from cPanel
12. deleted both core and pro
13. installed 3.0.1 core and activated
14. installed 3.2.91 pro 
15.  the site went 500 

this does not work. 
this did not pass my test
tested on two sites, both sites broke

**Comment by Nicholas-Cardot** [comment]
@JasonWiser You're absolutely right. I've made a new commit to the testing branch and I've changed the testing notes. It should now only take a few seconds to test the new approach to the solution that we're taking.

**Comment by coreyzev** [comment]
confirmed
