### ISSUE TITLE
Add a Mix network to the available buttons.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#593]
# **Notes for Testers** 

In June, StumbleUpon closed itself off as a network service. 
Mix is the replacement, so naturally we added a Mix button to our panel. 

### What we want to happen: 
When viewing a buttons panel with the Mix button, you should: 
- See the Mix icon on an orange button.
- Click it to share the post to Mix.

## How to test: 
In Social Warfare -> Display -> Social Networks :

1. Add Mix to the buttons panel. 
2. Press "Save Changes".
3. Visit a post. 
4. Click the Mix button to share the post.
5. Verify the share title and description match what you expect.
6. Verify on Mix that the share was made.

If all of the above goes through, we are good to go. Hooray!
If one of the above does not happen, please let us know as a comment to this thread. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**end notes**
#

Just use the SumbleUpon icon for development purposes until @DustinWStout can get us an updated font with the new icon added into it.

Here is the primary color for CSS: #fd8235
We'll need an accent color from Dustin for the 3D ones.

Write a public method inside the Mix class that checks for the old StumbleUpon counts and if they exist, migrate them into the mix meta field for counts. You can use the cache update filter inside the Post_cache class to make sure that it runs whenever the cache is updated.

**Comment by DustinWStout** [comment]
@Nicholas-Cardot @ckmahoney here are the new Mix colors (my closest estimate since they don't have a brand style guide I can find): 

primary: #f4812c
secondary (outline/hover): #c96a29

will work on getting the icon into our icon font next.

**Comment by Nicholas-Cardot** [comment]
@DustinWStout Awesome. Great work on that. Much appreciated.

**Comment by ckmahoney** [comment]
This issue has been updated with notes and is ready for testing.

**Comment by DustinWStout** [comment]
@ckmahoney I just saw Mix sent us their official color palette and the primary needs to change to: #ff8226

**Comment by DustinWStout** [comment]
Not sure what happened, but this is what I see when trying to share with Mix button:

<img width="828" alt="screen shot 2018-08-24 at 1 55 38 pm" src="https://user-images.githubusercontent.com/2152604/44607495-7f2e8e00-a7a5-11e8-95cf-04be93741b9e.png">

This is the link in the URL of the popup window: http://test.dustn.co/hello-world/http%3A%2F%2Ftest.dustn.co%2Fhello-world%2F%3Futm_source%3Dmix%26utm_medium%3Dsocial%26utm_campaign%3DSocialWarfare

**Comment by ckmahoney** [comment]
The the time we created SWP_Mix, Mix was yet to be released and we did not know the sharing API. 

They still do not have one published, but by using https://www.addtoany.com/services/mix_button I was able to find this as the base share URL: 
>https://mix.com/mixit

And the query paramter "url", so a fully qualified Share link would be like :
```https://mix.com/mixit?url=http%3A%2F%2Ftest.dustn.co%2Fhello-world```

I have not found any parameters for a description or tag. 

Looks like Mix displays their own engagment count. I have yet to see if they make that information available.

**Comment by ckmahoney** [comment]
The count itself is accessible in the page data as raw JSON. It is not assigned to a window variable from what I found, but the containing script does have an `id` attribute and could easily be targeted with PHP. With that object, let's call it `$mix`, you can get share counts at the following index:  
`$share_counts = $mix['articleProfile']['article']['count'];`

**Comment by JasonWiser** [comment]
I cant find the "Mix" icon. Which one is it? 
An excellent UX improvement would be to add a hover text of each of the networks.
When in Dashbaord -> Social Warfare -> Display -  Social Networks -. (Active, Inactive, Button Ordering) add hover text to each of the buttons. I had to go look up Mix and never did find it

**Comment by Nicholas-Cardot** [comment]
Adding a hover text is a terrific idea for those. Great idea. That would definitely be a huge help.

**Comment by coreyzev** [comment]
Tested. working.
