### ISSUE TITLE
Refactor the utility, registration, and options-fetch files. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#594]
# **Notes for Testers** 

This is a development specific issue that should actually be 100% unnoticeable on the front end. Please help us verify that the following are true: 

1. While Social Warfare 3.2.9 (or 3.3.0+)  is active, you do not see any errors like "File does not exist", "Failed to load class", "Class not found", "Failed to load required file . . .", or any other error that indicates something is missing. 

2. The plugin directory structure looks like this, where each of the list items is a directory (folder): 
```
- social-warfare
    - assets
        - css
        - fonts
        - images
        - js
    - languages
    -lib
        - admin
        - frontend-output
        - options
        - social-networks
        - update-checker
        - utilities
        - widgets
```
```
 - social-warfare-pro
    -lib
        - admin
        - frontend-output
        - meta-box
        - social-networks
        - utilities
```

Don't worry about finding specific files. If the folders match the outline above, the files are fine as well.

If your plugin looks like the above and you don't encounter and PHP errors/warnings, we are good to go! Give this a thumbs up. 
Else if the above does not match or you find errors, please reply to this thread explaining what happened. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

#

## Original Issue 
- [x] Rename /functions/ to /lib/
- [x] Rename SWP_Addon to Social_Warfare_Addon
- [x] Move Social_Warfare_Addon up one level so it live next to Social_Warfare
- [x] Create the SWP_Utility class. Make public function become public static methods.
- [x] Move registration.php out of the /includes/ folder. Refactor, clean, etc.
- [x] Study options-fetch.php. This should be fully replaced with SWP_User_Options.
- [x] Remove the /includes/ folder.
- [x] Rename /plugin-update-checker/ to /update-checker/ or /updates/
- [x] Rename all files in pro to begin with SWP_Pro_ (to include social network classes)
- [x] Finish up the non-classes inside the /lib/admin/ folder in both core and pro.

utility.php needs to become `class SWP_Utility`, which will have public static methods.

**Comment by ckmahoney** [comment]
This has been annotated and is ready for testing.

**Comment by JasonWiser** [comment]
Checked file structure in FTP on 2 site. 
no errors.
Done

**Comment by coreyzev** [comment]
No issues.

**Comment by Nicholas-Cardot** [comment]
All files are in the right place. No missing file errors.
