### ISSUE TITLE
WooCommerce Customer Orders Are Given Bitly Links

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#597]
**Developer Notes from Nick:** We need to make this so that short links are only generated on public facing post types. Or possibly we make a drop down just like the location options where users can manually control which post types the link shorteners will work on.

When a purchase is made through WooCommerce a Bitly link is created for each of the share options. Bitly links should only be generated for public pages.

Not sure your best solution for this but I suggest you add checkboxes for site admins to opt-in to Bitly links for preferred post/page types only.

**Comment by lvvvvvl** [comment]
Same thing is happening with Easy Digital Downloads, it's burning through our 500 complimentary custom domain bitly urls every month.  I'd be happy with the checkbox option suggested by @VR51

**Comment by VR51** [comment]
I messaged Social Warfare customer support about this. I was told the developer team is aware of the issue.

A day or two after opening this issue I noticed that this has been flagged before in issue #534. Looks like the fix has been kicked down the road into version 3.3.0. The issue referenced speaks specifically about the Bitly custom domains being quickly eaten up by SW on plugin activation.

**Comment by ckmahoney** [comment]
Hello @VR51 and @lvvvvvl 

I just wanted to let you know that we had created an official issue for this bug (#534). We are currently testing the new changes, and if the tests pass, this feature will be included with version 3.3.0 on September 10. 

If you are interested in participating in the beta tests, please let us know! You can tag me here and I'll get you more info about it.
