### ISSUE TITLE
Check each Pro network for updates to the share fetch API. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#598]
Networks change their APIs, and we need to follow. 

Check each of the following networks for changes to their share count API. If there are updates, create an issue for that network and update the code accordingly. 

- [x] Buffer
- [x] Flipboard
- [x] Hackernews
- [x] Pocket
- [x] Reddit
- [x] Tumblr
- [x] WhatsApp
- [x] Yummly

**Comment by ckmahoney** [comment]
@Nicholas-Cardot 

In Reddit, what does the 'score' value indicate?
Is that shares, or does it also count upvotes? 

**SWP_Reddit.php**, L 81
```
foreach ( $response['data']['children'] as $child ) :
    $score += (int) $child['data']['score'];
    endforeach;
endif;
```

**Comment by Nicholas-Cardot** [comment]
Yeah, it should be combining shares and upvotes.

**Comment by ckmahoney** [comment]
In that case, we can also fetch upvotes from Hackernews. 

And why stop there? If we are just getting 'likes', why not fetch likes from Facebook too and add that to the share count? 

So the question is, what is the borderline between a share and a like?

**Comment by Nicholas-Cardot** [comment]
We already do count likes from Facebook. The goal has never been to count shares. The goal has always been to count social media "activity" related to a URL.

**Comment by nutsandbolts** [comment]
Facebook's share API counts "engagements" - shares, likes, and comments. It combines them into one total.

**Comment by ckmahoney** [comment]
In that case, we can add the points value provided by HackerNews.

**Comment by ckmahoney** [comment]
Networks have been checked, two issues created. One for Tumblr, one for HackerNews.
