### ISSUE TITLE
Script.js does not execute properly, share buttons open in new tab.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#599]
## Notes for testers

**What we expect**
When clicking any of our buttons on desktop, they should open in a new window (not a new tab). 

**How to Test**

1. Visit a post. Wait a few seconds to make sure the page has loaded. (In Firefox, and perhaps other browsers, there is a spinning loading icon in the tab that indicates the document has not finished loading). 
2. Click one of our share buttons. The popup should be in a new window, **not** a new tab. 

If something does not go as described above, please let us know in the comments. 
Once you have finished testing, please give this comment a thumbs up. 

### end notes

**Problem**
When clicking one of our share buttons, the window opens in a new tab. If the button is Pinterest, nothing happens on click. 

**What we want to happen**
Clicking any share button opens a popup with the share API. 

**Why is this happening?**
We think sometimes it is because our script is not loaded. Othertimes I can tell the script is loaded by inspecting the Network tab of the dev tools. 
Perhaps the `handleWindowOpens` function is executed on pageload, before the content is delivered to the page? This could happen if the content is loaded via ajax. 

In that case, we can run a check something like this:
1. Send a JS variable from PHP that says there should be buttons on the page. 
2. Set a timer to check if the buttons exist yet. 
3. When the buttons exist, initialize Social Warfare.
4. Close the timer.

**Comment by ckmahoney** [comment]
This also appears to happen on mobile, with no console errors present. Ticket ID 204293

**Comment by Nicholas-Cardot** [comment]
I've seen this issue pop up very, very randomly for a very long time now. I think there are a number of plugins and things that can cause JS not to load, and if the JS doesn't load/execute it's going to cause this.

I like the timer approach to it as well. How do you make it see the variable if it's not seeing the buttons? What if the variable doesn't exist yet either.

**Comment by ckmahoney** [comment]
We print the timer with the variable in wp_footer_scripts. 

I think we'll have to move this into Fezzick though, as i am still waiting on logins for a few test sites.

**Comment by Nicholas-Cardot** [comment]
Agreed. Plus that's probably a bit much to try to slip into Count Rugen this late in the game. Moving it now.

**Comment by ckmahoney** [comment]
Commit fdc3e2501512dc0d41a85412bffc0592193070f3 referenced this issue.

**Comment by iHelpers** [comment]
Using Firefox 63.0.1 with "Content Blocking" disabled and Safari 12.0.1  Facebook and Pinterest open in new tabs. Clicking email does nothing.

**Comment by nutsandbolts** [comment]
@iHelpers Do you have a default email program set on your computer? If you use browser-based email the link won't know what program to open in.

**Comment by iHelpers** [comment]
Yes, using the default Mac Mail. After testing more, it looks like it doesn't work if Mail is running in it's own 'workspace'.. Once out of it's workspace the email button works as expected so this could be an OSX thing..
FB and pinterest still open in new tabs instead of pop-ups no matter what.

**Comment by ckmahoney** [comment]
@iHelpers DMing you in Slack about this.

**Comment by ckmahoney** [comment]
On a fresh install, all buttons except Pinterest are opening in a new tab. Pinterest opens in a new window.

**Comment by ckmahoney** [comment]
This may not have actually been broken, but is actually just something is prone to break when we have errors in our JS. 
Ready for testing.
