### ISSUE TITLE
DOMDocument does not recognize HTML5 elements.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#600]
# // **Notes for Testers** 

### What we want to happen: 
When using the [pinterest_image] shortcode, you are able to view the content without any "Invalid tag" warnings. 

### How to test: 

1. Go to a blog post, and insert the following HTML5 tags somewhere in the content. You should be able to copy the following code directly into the text (not visual) editor: 
```
<main>
<article>
Thanks for testing out this new feature! 
Today's date is <time>August 15, 2018</time>
Here's some data: <data value="bit">00101101</data>
</article>
[pinterest_image]
</main>
```

2. Make sure you have a Pinterest image set for the blog post. 
3. Click "Save Changes".
4. Visit the blog post on the front end. Does it throw any warnings? 

If you are able to view the post without error, hooray! We are in the clear. 
If you encounter something contrary to the above, please reply to this thread. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

**Problem**
TicketID 199321

We use the `DOMDocument` class to parse `the_content` so we may add our own data-pin-description to images. 
However, `DOMDocument` parses the text as HTML (4), and many users have modern tags present only in HTML5. 
This makes the class throw warnings saying tags are invalid. 

**Solution**
https://stackoverflow.com/questions/9149180/domdocumentloadhtml-error

To surpress the Warnings, put

`libxml_use_internal_errors(true);`

before the call to loadHTML and

`libxml_use_internal_errors(false);`

after it.

**Comment by ckmahoney** [comment]
This has been annotated with notes for testers and is ready for testing.

**Comment by JasonWiser** [comment]
installed new file. 
added test HTML5 markup in text editor
no errors on frontend of page
checked inspect element -> console - no errors
check server logs -> found same error several times

[15-Aug-2018 09:41:51 UTC] PHP Warning:  Error while sending QUERY packet. PID=3068040 in /home/ontrackt/public_html/wp-includes/wp-db.php on line 1924

I will check back in 10 miuntes

**Comment by JasonWiser** [comment]
Should the error happen in real time? I deleted the errors from my log, then hit refresh on the page (hoping to trigger an error, not sure how to test and force trigger the error other than to 'Publish" and refresh page

**Comment by Nicholas-Cardot** [comment]
That error is unrelated to this. If you loaded a page with an HTML5 tag in the content text, it should have showed up in the log pretty much right away. So everything sounds good so far from your testing. Thanks!

**Comment by meymigrou** [comment]
No errors or warnings for me either! Looks good.
