### ISSUE TITLE
Mobile floating buttons add padding to top when set to bottom. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#602]
# **Notes for Testers** 

### What we want to happen: 
When using mobile floating buttons, we should see the top buttons on the top of the device and the bottom buttons at the bottom. There should be extra padding created for these panels to be inserted without covering content. But, the padding should not be noticeably visible. 

### Step 1: Set the floating buttons to mobile.

In Social Warfare -> Styles -> Foating Share Buttons,

1. Set "Floating Buttons" to ON. 
2. Set "On Mobile" to Bottom of Screen. 
3. Make sure the minimum screen width is a reasonable number (at least 756px)
4. Press Save Changes

### Step 2: Verify floating buttons should exist for the post. 

In Social Warfare -> Display -> Position Share Buttons,

1. Verify that floating buttons are ON for the type of post you are checking. 
2. In your target post's editor, verify in the Social Warfare meta box that the floating buttons are "default" or "on". 

Save as necessary. 

### Step 3: View the target post on mobile. 

You should see the regular buttons panel, if any, displayed as set. 

As you begin scrolling through content and the regular buttons go off screen, the floating button bar should stick to the bottom to take its place. 

There should not be any padding on the top of the screen, or at the top of the page. 

If all of the above checks out, hooray! We are good to go and you can give this a thumbs up.
If something is buggy or weird, let us know as a comment to this issue .

If something is not clear or does not make sense, please let us know in Slack. 

** end notes **
# 
Original Issue. 

**Problem**
TicketID 191881

Our `toggleFloatingBar()` function adds padding to the top or bottom of the page, depending on where the floating buttons are set. 

However, it is only checking the position of the desktop buttons. It does not account for the position of mobile buttons. 

**Solution**

We need to adjust the code to see if we are mobile. If mobile, use the `data-float-mobile` attribute instead of the `data-float` attribute. 

Something like 
```
if ($(window).width() > $(panel).data("min-width") {
    var location = $(panel).data("float");
} else {
    var location = $(panel).data("float-mobile")
}
```

**Comment by ckmahoney** [comment]
This has been annotated and is ready for testing.

**Comment by Nicholas-Cardot** [comment]
Looks good. Let's see what the testers find. :-)

**Comment by coreyzev** [comment]
Tested, seems fine.
