### ISSUE TITLE
Print Friendly

### ISSUE THREAD

**Issue by diggisaur** [warfare-plugins/social-warfare#61]
Can we incorporate Print Friendly into the toolbar. Aside from making print friendly copies of webpages it also allows to export to PDF and send as email. So it is essentially 3 plugins in 1. Would love to see it added.

**Comment by lisaleague** [comment]
Print Friendly already has a send by email function. Adding this to Social Warfare could potentially cause issues for those who already use this Print Friendly. 
You can put Friendly on your pages manually or in your template file, so you should be able to easily place in a way that is compatible with both your theme and with Social Warfare.

**Comment by Nicholas-Cardot** [comment]
We've discussed this and we feel that for the most part this is covered by other plugins and it's outside the scope of a social media plugin. We plan on introducing an email button, but it will email a link and a description of the post, not a PDF. As such, we're going to close this request.
