### ISSUE TITLE
Add the Pinit On Hover checkbox on a per-image basis. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#610]
# **Notes for Testers** 

Sometimes we want a particular image not to be featured as a Pinterest image. This new option lets you decide if you want an image to be pinnable on a per-case basis. 

### What we want to happen: 
If an image is opting out of pin on hover, you are not able to "Save" that image even though you can pin other images in the post with the "Save" button. 

### Step 1: Enable Pin on Hover
1. In Social Warfare -> Display -> Image Hover Pin Button, set Pinit Button to "ON."
2. Set Image Source to "Pin the Image."
3. Set Hide on Anchors to "OFF." 
4. Press "Save Changes". 

### Step 2: Opt out of Pin on Hover for an image. 
You can do this either in the Media editor, or when inserting media in the post editor. 
These steps are for using the post editor. 

1. On a post, click the "Add Media" button. 
2. Select the image you would like to target.
3. In the "Attachment Details" panel to the right, check the box labelled "Hover Pin Opt Out." 
4. Click "Insert into post". 
5. Click "Update." 

If there are no other images in this post, add another one so we can compare the two. 
*Do not* check the box labelled "Hover Pin Opt Out" for the second image. 

### Step 3: Verify the "Save" button does not appear on the opted-out image.

1. View the freshly updated post on the front end. 
2. Hover your mouse on the opted-out image. There should be no "Save" button.
3. Hover your mouse on any other image in the content. There should be a "Save" button. 

#

If all of the above goes through, hooray, we are good to go! Give this a thumbs up. 
Else if the above does not work, please reply to this thread explaining what happened. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
If you have the Pin on hover button activated, you should have the option to disable this on a per-image basis.

**Comment by ckmahoney** [comment]
Commit 8c09ead  referenced this issue.

**Comment by ckmahoney** [comment]
Commit [6af60e1](https://github.com/warfare-plugins/social-warfare-pro/commit/6af60e127b1b7f7f453a8eb21f589e9986261e60) references this issue.

**Comment by ckmahoney** [comment]
This has been annotated and is ready for testing.

**Comment by JasonWiser** [comment]
on one site, I do not see the  "Hover Pin Opt Out." in the  "Attachment Details" panel to the right. (wisersites.com) 
-----------
on the Guttenberg test site - (ontracktips.com)
The hover pin opt out is NOT working consistantly

Secondly, it should be noted that the only opportunity that the user has to check the "Hover Pin Opt Out" button is when the image is added to the block. Once saved, the on page "Block editor" does not include our options. Neither "Social Warfare description" nor "Hover Pin Opt out" checkbox. 

So if someone were to want to change this from hover opt in to hover opt out, they would need to delete the image block, and re-upload from the media editor.
