### ISSUE TITLE
Remove nested functions within SWP_Pro_Pinterest.php

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#611]
# **Notes for Testers** 
***Updated on 22 AUG 2018***

### What we want to happen: 
When using more than [pinterest_image] shortcode, we need each one to display the image without throwing any `Warning: cannot redeclare function . . . ` errors. 

### Step 1: Add two [pinterest_image] shortcodes to a post. 
1. In the post editor, insert an image for the Pinterest image media box. 
2. Press save the changes by pressing "Update."

### Step 2: View the post. 

If you get two copies of your image and no errors, great! 

#
If all of the above checks out, hooray! Give this a thumbs up. 
If something goes awry, please let us know as a comment to this issue. 

# **Original Issue**

#### Problem
We were getting `warning: cannot redeclare function get_image_size()` when using the [pinterst_image] shortcode.

**Comment by ckmahoney** [comment]
This issue now has notes for testers and is ready for testing.

**Comment by VR51** [comment]
Posting this error here because it might be fixed since you removed the nested functions. Something for you to test. WP Debug reports $alignment on line 157 of SWP_Pro_Pinterest.php to be undefined.

**Comment by JasonWiser** [comment]
I am not clear on the instructions. 
Am I supposed to add [pinterest_image] two separate times in the post editor?

**Comment by coreyzev** [comment]
@JasonWiser Yeah. Mine looks like this: 

![image](https://user-images.githubusercontent.com/2052536/45242559-8209a280-b2be-11e8-89e6-3cb2120109f3.png)


Also tested, no errors.

**Comment by Nicholas-Cardot** [comment]
Jason, no, I see no reason to use it twice either, but someone did, and it threw an error so we fixed it and this test confirms that we fixed it.
