### ISSUE TITLE
Decimal separator only using comma

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#613]
# **Notes for Testers** 

### What we want to happen: 
Social Warfare displays a period for the decimal separator when "period" is selected, and a comma when "comma" is selected. 

It should also respect the number of decimals, as well as the using the appropriate suffix ("K" for thousands, "M" for millions).

### Step 1: Find or fabricate a post with over 1,000 shares. 
For the test to be effective, we need to have a post which reports over 1,000 shares as well as a post which reports over 1,000,000 shares. 

You can fool Social Warfare into thinking the post has shares by manually editing a post's custom fields. The plugin Show Hidden Post Meta allows you to do this. 

1. Install and activate [Show Hidden Post Meta](https://github.com/warfare-plugins/social-warfare/files/2336364/show-hidden-post-meta.zip) if you do not have it. _The link is a .zip file._
2. Edit the post you will be testing on. 
3. In the screen options at the top of the post editor, make sure "Custom Fields" is checked (so its meta box is visible below the content editor).

Social Warfare meta keys are in the following pattern: 
`_network_shares`

Where $network is any one of the following (core) networks: 

```
['facebook', 'pinterest', 'linkedin', 'mix', 'twitter', 'google_plus', 'total']
```
Notice 'total' at the end. This value is computed as the sum of all other network shares. 

Example custom fields with Facebook and Pinterest as your active networks would look like this: 

```
___________________________________
|  key                |   value   |
| _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
| _facebook_shares    |   3113    |
| _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
| _pinterest_shares   |    431    |
| _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
| _total_shares       |   3544    |
___________________________________
```

4. You can either edit existing custom fields, or create new custom fields, to fabricate share data for this test. 
4a. The first set of tests should be for share totals between 1,000 and 999,999.
4b. The second set of tests should be for share totals at or above 1,000,000.

5. Save your new custom field data, and update the post. 

### Step 2: Enable Share Counts.

In Social Warfare -> Display -> Share Counts,

1. Set "Button Counts" to ON.
2. Set "Total Counts" to ON. 
3. Take note of the minimum shares value. 
4. Save Changes. 

### Step 3: Set the Decimal Separator. 

In Social Warfare -> Styles -> Total Counts,

1. Set "Decimal Places" to One or Two. 
2. Set the decimal separator. 
2a. For the first set of tests, set "Decimal Separator" to Comma.
2b. For the second set of tests, set "Decimal Separator" to Period. 

Save Changes. 

### Step 4: Visit the post on the front end. 

Because you manually edited the post meta, all of that share count data should already be loaded and ready for display. 

Check to make sure that the separator is the one you selected (period or comma), and that the number of digits displayed after the separator matches your setting for Decimal Places (one or two). 

Then, edit the post meta share counts so you can increase share counts to over 1,000,000. 

Reload the page, and confirm that with the updated share counts, the same rules apply.

#

If everything goes as planned, hooray! We are good to go. Give this a thumbs up. 
If something is contrary to what we expect, please let us know as a comment to this issue.
 
If something is not clear or the process does not make sense, please use Slack to ask questions. 

**end notes**
#
Despite setting the Decimal Separator to "Period" it is displaying a comma. 

<img width="568" alt="screen shot 2018-08-24 at 1 53 10 pm" src="https://user-images.githubusercontent.com/2152604/44607412-3971c580-a7a5-11e8-999c-73d2499ed246.png">

**Comment by ckmahoney** [comment]
This issue has been annotated and is ready for testing.

**Comment by rangerdth** [comment]
In testing, regardless of the number of decimal places or type of decimal separator, I was only able to view commas.

**Comment by coreyzev** [comment]
Tested working w/ period and commas
