### ISSUE TITLE
Pinterest Button does not work on Mobile (JS likely) 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#614]
## Notes for testers

**What we expect**
You can visit a post on mobile and click the Pinterest button (not the hover "Save" button) to share a post.

**How to Test**

1. In Social Warfare -> Display -> Social Networks, make sure Pinterest is in the Active networks.
2. Visit a post on mobile. Find a set of horizontal share buttons, and click the Pinterest button. 
 - It can be a static button or a floating button (one that is sticky to the top/bottom of screen), but it can not be a "Save" button.
3. The Pin dialogue should popup like normal. 

If any of the steps do not go as described, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

**Testing Notes:**

Attempt to click on the Pinterest share button from a mobile device. Did it work?

**Original Issue:**

TicketID 203725

When viewing on a mobile, the main Pinterest button does nothing on click. The other buttons share as expected. This is true using a regular browser at mobile dimension, so it is not device-specific.

**Comment by ckmahoney** [comment]
That was the key difference between this issue and #599 is that the other buttons open a new tab, whereas here they open in a new window. 

However that may be a browser inconsistency. 
Sometimes in Firefox they open in a new tab, whereas the same post viewed in Opera opens in a new window. 

But posts on this site all open in a new window in Firefox. 
https://warfareplugins.com/tips-for-new-bloggers/

So something causes them to open in a tab instead of window in Firefox, and that is issue #599.

**Comment by Nicholas-Cardot** [comment]
Yeah, so if the JS fails, those buttons are just being controlled by a target="_blank" and some browsers open that in a new tab and some open it in a new window. Most modern go the way of the tab.
