### ISSUE TITLE
Make floating buttons independent of static buttons; remove excess SWP_Buttons_Panels.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#615]
## Notes for testers

**What we expect**
You can have floating buttons on a page without there being any static buttons. Specifically, you can have a set of floating horizontal buttons (top/bottom) with no static buttons. 

**How to Test**

1. In Social Warfare -> Styles -> Floating Share Buttons, set Float Position to "Bottom of Page." Save changes.
2. Create a new post. In the meta box Social Warfare -> Other Post Options, turn Static Button Location to "none/manual placement."
3. Add a lot of filler content/Lorem Ipsum to the post so there is plenty of room to scroll.  
4. Save the post and view it on the front end. 
5. As you scroll down the page, the floating buttons should stick to the bottom. 
6. Change Float Position to "Top of Page." Save changes.
7. Visit the post again, and it should behave the same except with buttons sticking to the top of the page. 

If any of the steps do not go as described, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

The top/bottom floating buttons are dependent on a set of existing horizontal buttons being present on the page. 

Some option configurations allow for top/bottom floaters, but no horizontal buttons. 
This configuration would break the JS on the site when the floaters could not find buttons to clone. 

This code, in SWP_Buttons_Panel->render_HTML()  (Line 468), was written to work around that. 
```
if ( !$this->should_print() ) :
    //* Top and bottom floating buttons require a button panel present on the page.
    $float_location = $this->get_float_location();

    if ( true === $this->option( 'floating_panel' ) && 'top' ==  $float_location || 'bottom' == $float_location ) :
        //* Using display: none interfere's with the element's position,
        //* Which we need to be calculated correctly.
        $style = 'opacity: 0;';
    else :
		return $this->content;
    endif;
endif;
```

However it is now presenting other problems. When on an archive page, for example, there is a set of hidden buttons printed for each one. The hidden buttons are actually occupying some space ni the DOM, so when 9 of them get stacked on top of one another, the effect is noticeable. 

Further, while we want to just remove this code and call it done, that makes the Top/Bottom buttons not work. 
Fortunately it does not throw a JS error like before, but instead no buttons are displayed.

**Comment by Nicholas-Cardot** [comment]
1. Let's add a check for is_singular() so that this workaround only shows up in single blog posts.
2. Let's add something to the JS that sets it to display:none after cloning it or something like that.

**Comment by ckmahoney** [comment]
Patched, this is ready for testing in Core 3.3.96.

**Comment by meymigrou** [comment]
Working like a charm! But if I set the "Float Position" to "Bottom of the Page" from the settings and try to change it to "Top of the Page" from the post settings, the floating buttons remain with their default option from the settings and don't listen to the post's settings. Does that make any sense? :P

**Comment by meymigrou** [comment]
@ckmahoney it does! Thank you very much for explaining. Everything else working great :)
