### ISSUE TITLE
Restore the "has_plugin_conflict()" check in Buttons_Panel.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#618]
# **Notes for Testers** 

### What we want to happen: 
If using BuddyPress, posts/pages using BuddyPress should display the full user data instead of whitescreening. 

### Step 1: Install and set up BuddyPress.
1. Download from the WordPress Repo.
> You can find it by searching "buddypress" in the Add New plugins page,
> or get it here: https://wordpress.org/plugins/buddypress/ 
2. In Settings -> BuddyPress, make sure "Extended Profiles" is checked. 
3. Click Save Changes.
4. In Settings -> General, make sure "Membership" is checked so anyone can register. 
5. Click Save Changes.
6. Confirm Social Warfare 3.2.9x (the testing version) is active in the Plugins page. 

### Step 2: Create a BuddyPress profile page. 

If you already have a BuddyPress profile on your site with Social Warfare, you can visit it now. Otherwise, 
1. Visit your site incognito or in a private session.
2. Register and activate a new user. 

### Step 3: Visit the Profile page while Social Warfare is active. 

Go to your BuddyPress profile page. 
> By default, you can access this at `/members/$username/profile`, where '$username' is the username of the user's profile. 
> For example, `https://warfareplugins.com/members/ckmahoney/profile`.

You should see your name, description (if you wrote one), and a couple menus. If so, we are good to go and you can give this a thumbs up.

If the only thing you see is the username, and nothing else, then there is a plugin conflict and the problem is not solved. Please let us know as a comment to this issue. 

If something is not clear or does not make sense, please let us know in Slack. 
# **Original Issue**

Ticket ID 206417

We used to check if a site is using the Buttons Panel on that page, and if so, disable SW on those pages. 

The function still exists, too: `SWP_Buttons_Panel->has_plugin_conflict()`.

But it may be checked too late in the game. See Buttons Panel [L909](https://github.com/warfare-plugins/social-warfare/blob/00a481e92893666f38c5f91d268fa6e36c818905/functions/frontend-output/SWP_Buttons_Panel.php#L909)

**Comment by coreyzev** [comment]
Tested. Getting errors from `SWP_Buttons_Panel`. Debugged by echoing/dump out the variables we're testing, and they all come back false at the point in the loop where `has_plugin_conflict()` is called. 

Recommend relocating `has_plugin_conflict` to a point later in the loop.

**Comment by ckmahoney** [comment]
I also confirm the undefined index errors.

Right now we have `Social_Warfare::has_plugin_conflict()` running at 'plugins_loaded'. This is a good point to run the check for the following reasons: 

1. We need to verify that all plugins, including Social Warfare, SW addons, and BuddyPress have loaded. 
2. We need to prevent creation of any SW components if BuddyPress exists on the page. 

Button components start getting created at 'template_redirect', which happens much later than 'plugins_loaded.'

I think the current layout would be fine if the 'is_buddypress()' function did what we expect it to. However, it is returning `false`, even on the BuddyPress profile page. Perhaps BuddyPress hasn't registered itself as active on this page by 'plugins_loaded'? 

If there is a better point in the WordPress chronology to run the check, we can certainly try it.

**Comment by coreyzev** [comment]
tested no errors.
