### ISSUE TITLE
Share counts are not being correctly reported. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#619]
## Notes for testers

**What we expect**
When viewing any post, the share count data are the correct numbers. 

**How to Test**

1. Go to the Social Warfare -> Display -> Share Counts -> Minimum Shares. Set the value to 0 so all shares will get displayed. Save changes. 
2. Visit a post that has share data. For each network that shows share data, please find the fetch API link (see below) for the corresponding network, and open that link in a new tab.
3. The result is likely to be a JSON object, you might have to read it carefully to find something that says "shares", "likes", "reblogs", or something else that implies share data. Find that number, and see if it is close to the number SW displayed. 
 - Note - for Facebook specifically, we add a few different numbers together. 

If the reported numbers do not match what we have displayed, please let us know as a comment to this issue.

Once you have finished testing, please give this comment a thumbs up. 

*Fetch API Links*
To use any of these is a two step process. First copy the link as it exists into a new tab, but do not go yet. Then copy the permalink of the post you are checking, and add it to the end of the URL you started in the new tab. Then you can go and see share data. 

Note that not all networks offer a share count API service.

```
facebook: https://graph.facebook.com/?fields=og_object{likes.summary(true).limit(0)},share&id=

pinterest: https://api.pinterest.com/v1/urls/count.json?url=

twitter (open share count): https://opensharecount.com/count.json?url=

twitter (twitcount): https://counts.twitcount.com/counts.php?url=

buffer: https://api.bufferapp.com/1/links/shares.json?url=

hacker news: https://hn.algolia.com/api/v1/search?tags=story&restrictSearchableAttributes=url&query=

reddit: https://www.reddit.com/api/info.json?url=

tumblr: https://api.tumblr.com/v2/share/stats?url=

yummly: https://www.yummly.com/services/yum-count?url=
```
### end notes

Ticket ID 206686

We first noticed the reported share counts behaving strangely when unpublished drafts would appear to have 70 shares from Facebook, and published posts would report numbers much higher than were actually provided by Facebook.

Now, we are also seeing incorrect count data from Pinterest. 
For example, [this post](https://oceanstoalpines.com/dive-trip-caribbean-islands/) displays 86 pins, but only 59 are [reported from Pinterest](https://api.pinterest.com/v1/urls/count.json?url=https://oceanstoalpines.com/dive-trip-caribbean-islands/). 
 
This implies that it is not our communication with Facebook that is the problem, but is actually an error with our code. 

We need to investigate SWP_Post_Cache, SWP_Social_Network, and their related reading/writing systems.

**Comment by ckmahoney** [comment]
Changed from "draft" to "official." 
The problem is not just with facebook, but also with pinterest.

**Comment by Nicholas-Cardot** [comment]
I just checked that post and both the post and the API are reporting the same number. This was perhaps due to some sort of a caching issue.
