### ISSUE TITLE
Issue with special characters on Facebook

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#62]
Posts shared on Facebook can't read quotation marks or apostrophes in the titles and instead render code -- so it comes out gibberish like:

> `Who Is Max&#8217;s New Boyfriend Owen on &#8216;2 Broke Girls&#8217;?`

And it should be:

> Who Is Max’s New Boyfriend Owen on ‘2 Broke Girls’?

It appears that the OG meta tags generated by social warfare now contain raw encoded HTML.

**Comment by Nicholas-Cardot** [comment]
This appears to be unrelated to Social Warfare. Our plugin is outputting the character codes in a format consistent with the way WordPress outputs the titles and other properties. Testing these characters through the Facebook Debugger and the share button seem to indicate that they are indeed being parsed properly.
