### ISSUE TITLE
Totals only appear on one set of buttons, rather than both. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#621]
Ticket ID 203267

This user has set the totals to be on the right, and to have above & below content buttons.
However, the totals only appear on the right hand side of the bottom floating buttons.

When he sets the totals to the left, they only appear on the left hand side of the bottom floating buttons.

We need to review the logic in SWP_Buttons_Panel, probably the `render_total_shares_HTML` method.

**Comment by Nicholas-Cardot** [comment]
This should now be resolved. It's also possible, that if you have too many buttons being displayed, the flex/responsive attributes could cause total shares to begin hiding in order to fit everything into the panel properly.
