### ISSUE TITLE
Add tooltip text to the button selection icons.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#623]
## Notes for testers

**What we expect**
In Social Warfare -> Display -> Social Networks, when hovering over any of the Active or Inactive Icons, the name of the network appears in a red text bubble right above the network. 

**How to Test**
Go to Social Warfare -> Display -> Social Networks and hover over the icons with your mouse. 

If it does not look correct as described above, please let us know as a response to this issue. 

When you have tested this, please give this comment a thumbs up. 

### end notes
By adding a hover text to the icons, users will be able to identify the names of the social networks with which they may not otherwise be familiar. This will be especially helpful for icons like Mix that really haven't been around for very long and as such, many users may not yet recognize the logo.

**Comment by ckmahoney** [comment]
Kind of forgot about this issue, even though it is much closer to being done than not. 

https://github.com/warfare-plugins/social-warfare/blob/development-3.4/assets/js/admin-options-page.js#L787

Can we get a mockup please for the design of where the tooltip will go?

**Comment by DustinWStout** [comment]
let's change the background on these to `#ced3dc` and the font color to `#30394f`.

**Comment by iHelpers** [comment]
On both Safari 12.0.1 and Firefox 63.0.1 the buttons appear but are offset about 1.5 button-widths to the right.

![screen shot 2018-11-08 at 9 10 04 am](https://user-images.githubusercontent.com/39499655/48215161-7f671000-e336-11e8-8fe1-0a9be6cb71f5.jpg)

**Comment by ckmahoney** [comment]
@iHelpers I was not able to replicate this in Firefox or Safari.

Was the window less than full screen in either browser when you saw this happen? Are you able to replicate it still?

**Comment by iHelpers** [comment]
Does it full screened or windowed, 100% repeatable ..

**Comment by ckmahoney** [comment]
Now on a fresh install of WP in a new environment, I am able to replicate the issue and acknowledge the bug still exists. 

<img width="503" alt="screen shot 2018-11-14 at 2 42 01 pm" src="https://user-images.githubusercontent.com/26120849/48508023-7c2ec100-e81b-11e8-9fee-cc8da7ae26bd.png">

**Comment by ckmahoney** [comment]
I see the cause of discrepancy: 

When you have the admin menu collapsed on the left, the tooltips are correct. 
When the admin menu is expanded (default), they are offset to the right by the width of the menu.

**Comment by ckmahoney** [comment]
Commit 1f37600ef7dede25fe6f5df9c9f59d6df0a24b0a, among others, reference this issue.
