### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by scottwyden** [warfare-plugins/social-warfare#625]
The moment I uploaded 3.2.91 of both plugins, I got a WSOD and HTTP ERROR 500.

This is what's in the logs provided by WP Engine:

`[Fri Aug 31 17:37:03.738168 2018] [:error] [pid 1369] [client 100.1.211.80:32412] PHP Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /nas/content/live/socialwarfare/wp-content/plugins/social-warfare/lib/utilities/SWP_Utility.php on line 143, referer: https://socialwarfare.wpengine.com/wp-login.php?redirect_to=https%3A%2F%2Fsocialwarfare.wpengine.com%2Fwp-admin%2F&reauth=1`

`[Fri Aug 31 17:37:06.600679 2018] [:error] [pid 31446] [client 100.1.211.80:32426] PHP Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /nas/content/live/socialwarfare/wp-content/plugins/social-warfare/lib/utilities/SWP_Utility.php on line 143`

`[Fri Aug 31 17:37:11.688849 2018] [:error] [pid 31446] [client 100.1.211.80:32441] PHP Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /nas/content/live/socialwarfare/wp-content/plugins/social-warfare/lib/utilities/SWP_Utility.php on line 143`

Please let me know if you need me to troubleshoot this in some way.

**Comment by Nicholas-Cardot** [comment]
Moving this to https://github.com/warfare-plugins/social-warfare/issues/612

Since this isn't a bug in a publicly released version, but only in our beta version that is unreleased, I'm adding it to the beta checklist and closing it out here.
