### ISSUE TITLE
Prevent shortlink creation for autosaved posts. 

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#626]
## Notes for testers

**What we expect**
Bitly shortlinks are only created for published posts, not posts saved as a draft. 

**How to Test**

1. In Social Warfare -> Advanced -> Bitly Link Shortening, turn Bitly ON. If your account is not connected to Social Warfare, you will need to authorize SW to use your Bitly access token. 
2. Start a new post. Give it some content and save a draft, but do not publish the post. 
3. Preview the post. After the page has loaded, reload it one time. 
4. Hover any of the buttons (except Pinterest or Email) in your panel. Your browser should display the destination url at the bottom of your window. There should **not** be any bit.ly or other shortlink in the url. Instead, it should look more like the permalink to that post.

If it still shows a shortlink, please let us know as a comment to this issue.

Once you have finished testing, please give this comment a thumbs up. 
### end notes

"I’m not sure how or why, but it looks like Social Warfare is creating bitly links for autosaves when Gutenberg is activated…"

**Comment by ckmahoney** [comment]
Notes:
Buttons do not display on previews anyway, step 3 is currently incorrect.
Viewing the Custom Fields, looks like it did go ahead and great a shortlink for this unpublished post.

**Comment by Nicholas-Cardot** [comment]
Just pushed a commit that should fix this up. Please take a look @ckmahoney
