### ISSUE TITLE
Add Print CSS to hide the buttons panel on Printed pages

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#627]
@media print {
    // Hide the buttons panel
}

**Comment by coreyzev** [comment]
Buttons still show up on print preview. (Pressed ctrl+P)

![image](https://user-images.githubusercontent.com/2052536/45241546-d9a60f00-b2ba-11e8-9e8e-286b5e8c2d6f.png)

**Comment by coreyzev** [comment]
Now working as expected.

**Comment by Nicholas-Cardot** [comment]
While the buttons were hiding, the priority of CSS rules was overriding the display:none and only the opacity/visibility was going away meaning that they were still consuming space (albeit invisible space) in the page.
