### ISSUE TITLE
Total shares do not display when using the shortcode. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#628]
## Notes for testers

**What we expect**
When using the `[social_warfare]` shortcode, we get a set of buttons exactly as they would appear above or below the content. 

When using the `[social_warfare buttons="facebook, pinterest, totals"]` shortcode, we get a buttons panel with Facebook, Pinterest, and the Total Shares icon (for example). 

**How to Test**

1. In Social Warfare -> Display -> Share Counts, set 'Total Counts' to ON and save changes. 
2. In a post, add the shortcode `[social_warfare]` to the content. Save the change. 
3. View the post. Where you entered the shortcode, you should see a regular buttons panel with the total shares.
4. Turn the Total Counts OFF, save changes. 
5. View the same post you edited in step 2 (without making any changes). There should now be *no total shares on the same buttons panel*. 
6. Now edit the shortcode to use the 'buttons' attribute. Add two networks, as well as the 'totals' keyword. The resulting shortcode might look like: `[social_warfare buttons='totals, facebook, twitter']`. Save the changes.
7. Even with Total Counts OFF, you *should* see total shares in the shortcode buttons panel. 
8. Now remove the 'totals' from your shortcode so only two networks remain. Save the changes. 
9. View the buttons panel one more time. It should only have the two networks you have specified. 

If one of the above does not happen, please let us know as a comment to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

When using the `[social_warfare]` shortcode exactly like that, we expect it to produce a set of buttons exactly as they would appear above or below the content. 

This means if the admin has opted in for total shares, the total shares are displayed. 

Right now, the total shares are not displayed when printing buttons with the shortcode.

**Comment by ckmahoney** [comment]
This issue has been annotated and is ready for testing.

**Comment by Nicholas-Cardot** [comment]
Buttons_Panel line 998

**Comment by DustinWStout** [comment]
Working for me.

**Comment by hblomgren** [comment]
I manage to get a weird error. When chosing "total counts" to "off" my shortcode still outputs the "total shares: 0" in my case. Only way of getting it to now display the "total shares" is by using [social_warfare buttons='facebook, twitter']

**Comment by ckmahoney** [comment]
I have replicated what @hblomgren describes: 
In step 5, turning Total Counts OFF still displays the totals in the shortcode panel.

**Comment by Nicholas-Cardot** [comment]
Lookin into this now.

**Comment by Nicholas-Cardot** [comment]
This should now be fixed.
