### ISSUE TITLE
Pinterest description disappears when certain emojis are used

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#631]
## Notes for testers

**What we expect**
You can use emojis in the Pinterest description and save it with no problems. 

**How to Test**

1. Create a new post. In the metabox Social Warfare, give it a Pinterest Description. Include many  emojis of different kind. You can find plenty at [emojipedia](https://emojipedia.org/). Save the post.
2. Browse around the admin, and then return to the post editor for the post you created. The Pinterest Description should be the exact same as you saved it.

If any of the steps do not go as described, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes
See ticket #215256

If a user adds an emoji to his/her Pinterest description, the text area clears itself on save. This applies only to some emojis and not all of them, apparently, based on the ticket above. Since WP core now supports emojis, as do most social networks, we should look into this further and make sure we're able to handle emojis when they're added to the custom options fields.

**Comment by ckmahoney** [comment]
I am not able to replicate this issue.

The emoji I tried, 😉, is the same winking face the ticket opener said broke the textarea. 
However, I was able to enter this emoji many times as the only character in the Pinterest Description box, save it, and Pin it with this as the description. 

It could be that they were on a slightly buggier version of Social Warfare where the Pinterest description did not get saved in the post editor, and perhaps when it started working it was after they updated the plugin?

**Comment by Nicholas-Cardot** [comment]
Agreed. We've also recently done work on some of the encoding functionality so that may have fixed it as well.

**Comment by meymigrou** [comment]
I've used many different emojis and descriptions and I don't have any problems. The description (including the emojis) are all saved.

What I've used:

♡ White Heart Suit
🤷 Person Shrugging
❤ Red Heart
🥰 Smiling Face With 3 Hearts
😂 Face With Tears of Joy
😍 Smiling Face With Heart-Eyes
🔥 Fire
😊 Smiling Face With Smiling Eyes
🤔 Thinking Face

**Comment by ckmahoney** [comment]
🙌🙌🙌
