### ISSUE TITLE
Ensure the social_warfare() function is working as needed.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#637]
First, let's see if we can replicate this issue:
1. Add the social_warfare() function to a theme on a local site, most likely on a single.php file.
2. Check if it is outputting buttons, if not, let's step through it and figure out what's wrong.

**Comment by ckmahoney** [comment]
Commit 19c9e0f referenced this issue.

**Comment by Nicholas-Cardot** [comment]
The functions.php file was not being included, therefore this function did not exist. This is now fixed and will be available on the testing branch momentarily.
