### ISSUE TITLE
Pro meta keys persist when downgrading to core only

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#649]
When Pro is removed, post meta such as `swp_post_location` stays behind, which prevents the user from returning to the global settings despite losing the Pro features.

For example, if someone overrides the global "below the content" setting for a particular post or page, then removes Pro later, the custom options are gone but that individual setting remains. Changing the global settings (the only option left with core only) has no effect since the custom options aren't available.

We need to make sure this data is being wiped when Pro is removed, but we also need to differentiate between "I'm removing Pro to reinstall" and "I'm removing Pro because I don't plan to use it anymore." This could be a checkbox in the advanced settings to remove all data when Pro is removed (off by default of course) or a button to "scrub Pro settings" or whatever, but we need to get this resolved because it's causing issues for people who downgrade.

**Comment by Nicholas-Cardot** [comment]
The best solution for this is to come up with some sort of a controller class that finds and manages these types of options much the same way that we did with the SWP_User_Options class.

**Comment by ckmahoney** [comment]
Yes, I agree with @Nicholas-Cardot regarding finding a mechanism to filter the options. 

For SWP_User_Options, we are filtering based on global options. 

We should likewise have a filter for Post_Options. 

Here is an example of two Pro post_meta which are searched in Core, which should instead use some kind of hook: 
https://github.com/warfare-plugins/social-warfare/blob/development-3.4/lib/buttons-panel/SWP_Buttons_Panel_Loader.php#L212-L213

Though I don't have strong leads on a direction to go with that.
