### ISSUE TITLE
Fix Total Shares showing "0" on admin posts list

### ISSUE THREAD

**Issue by coreyzev** [warfare-plugins/social-warfare#650]
## Notes for testers

**What we expect**
When viewing your posts in admin, you should see the share count data accurately reflected in the "Social Shares" column. 

**How to Test**
1. Go to your Posts. 

2. Look at the Social Shares column. If any of them have 0, view that post on the front end. 
  2b. For the post showing 0 shares, if there *are* actually shares displayed on the front end, that is a problem you should tell us about. 

If there are no posts showing 0 shares, it should be good. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

Investigate why admin posts list is showing 0 count, and methods to fix this. 

example: 
![image](https://user-images.githubusercontent.com/2052536/45832445-e588cc80-bccf-11e8-9557-4ecc455d3df8.png)

Relevant tickets: 219789,

**Comment by DustinWStout** [comment]
Works for me.

**Comment by iHelpers** [comment]
Mine are all showing 10x more than the actual share amount:

![screen shot 2018-11-08 at 8 27 20 am](https://user-images.githubusercontent.com/39499655/48212463-81c66b80-e330-11e8-9aa1-61af2711833b.jpg)
![screen shot 2018-11-08 at 8 28 16 am](https://user-images.githubusercontent.com/39499655/48212464-81c66b80-e330-11e8-8de1-bfed61d86edf.jpg)

**Comment by ckmahoney** [comment]
Thanks @iHelpers. I just patched it and will post the updated zip soon.

**Comment by nutsandbolts** [comment]
Via a ticket today, I realized this also happens if the total counts are turned off in the settings. Need to check to see whether that's the case with 3.4.0 when testing.

**Comment by ckmahoney** [comment]
Thanks @nutsandbolts .

Right now I don't see anything that should affect total counts being displayed, if the total count metadata exists:
https://github.com/warfare-plugins/social-warfare/blob/master/lib/admin/SWP_Column.php#L75-L84

It may be that if total counts off, we never update the post meta to have a value.

**Comment by ckmahoney** [comment]
We could just hide this column entirely if total counts are off. What do you think @Nicholas-Cardot and @nutsandbolts ?

**Comment by nutsandbolts** [comment]
I know we already discussed but just voicing my NO here as well since people do want counts, whether or not they want to display them.

**Comment by Nicholas-Cardot** [comment]
Yes, this should be fully resolved by the added code on SWP_Post_Cache->get_allowable_age() method.

See below:
```
		/**
		 * Don't fetch share counts very often if share counts are disabled both
		 * as totals and on the buttons. We will only fetch once in a while so
		 * that we can cache the data and use it for things like the popular
		 * posts calculations and the admin posts column.
		 *
		 */
		$network_shares = SWP_Utility::get_option( 'network_shares' );
		$total_shares   = SWP_Utility::get_option( 'total_shares' );
		if( false == ( $network_shares || $total_shares ) ) {
			return 24;
		}
```
Now if all counts are disabled, it will still check for counts at least once per day.
