### ISSUE TITLE
In some instances the network objects are not being instantiated.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#655]
The underlying issue seems to be that there are no SWP_Social_Network objects being instantiated and added to the global $swp_social_networks array. This is causing no buttons to show up in the admin panel and is causing additional PHP errors throughout various posts and pages.

![2018-09-28_153351](https://user-images.githubusercontent.com/16140467/46232299-56fdf600-c334-11e8-8a59-56cd07e8a056.jpg)

Here are some of the errors that seem to be associated with this issue:

This is the error on the frontend. However, I think this is a symptom and not the actual problem.
```mod_fcgid: stderr: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/somewebsite.com/httpdocs/wp-content/plugins/social-warfare/lib/frontend-output/SWP_Buttons_Panel.php on line 940```

These are the errors on the admin options page:
```
Warning    reset() expects parameter 1 to be array, null given    1    
-
do_action('toplevel_page_social-warfare')
wp-admin/admin.php:224
SWP_Options_Page->render_HTML()
wp-includes/class-wp-hook.php:286
SWP_Options_Page->create_tabs()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page.php:289
SWP_Options_Page_Tab->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page.php:799
SWP_Options_Page_Section->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Tab.php:154
SWP_Options_Page_Section->render_options()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Section.php:187
SWP_Option_Icons->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Section.php:209
SWP_Option_Icons->render_inactive_icons()
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:270
reset()
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:190
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:190

```
And...
```
array_diff(): Argument #2 is not an array    1    
-
do_action('toplevel_page_social-warfare')
wp-admin/admin.php:224
SWP_Options_Page->render_HTML()
wp-includes/class-wp-hook.php:286
SWP_Options_Page->create_tabs()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page.php:289
SWP_Options_Page_Tab->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page.php:799
SWP_Options_Page_Section->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Tab.php:154
SWP_Options_Page_Section->render_options()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Section.php:187
SWP_Option_Icons->render_HTML()
wp-content/plugins/social-warfare/lib/options/SWP_Options_Page_Section.php:209
SWP_Option_Icons->render_inactive_icons()
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:270
array_diff()
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:203
wp-content/plugins/social-warfare/lib/options/SWP_Option_Icons.php:203
```

**Comment by productiveparks** [comment]
I am with wiersites.com and we had this issue and it turns out that it was code in our custom theme causing the problem. The following legacy code, when removed, cured this problem:
******************************************
$swp_user_options = get_option('socialWarfareOptions');
$domain = site_url();

// Check if the premium code matches the domain, if not, make it match and save it back to the database
if ($swp_user_options['premiumCode'] != md5(md5($domain))):
    $swp_user_options['premiumCode'] = md5(md5($domain));
    update_option('socialWarfareOptions', $swp_user_options);
endif;

**Comment by Nicholas-Cardot** [comment]
Yup. That makes perfect sense. That code would definitely cause some issues on 3.0.0+. Thanks for letting us know!

**Comment by Nicholas-Cardot** [comment]
This was happening because of conflicting code in the functions.php which was specifically targeting a variable that we use and modifying it in a way that made it not work right.
