### ISSUE TITLE
Disable Bitly links when the user has turned the feature off. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#657]
## Notes for testers

**What we expect**
If you were previously using Bitly with Social Warfare and now decide to no longer use shortlinks, turning Bitly OFF should force our buttons to use the normal permalinks instead of shortlinks, as well as prevent any new bit.ly links from being created. 

**How to Test**
1. If not already enabled, turn Bitly ON in Social Warfare -> Advanced -> Bitly Link Shortening. You will need to authorize Social Warfare to use your Bitly access token. 

2. Create a new post. Publish it, then visit it on the front end. The destination link on any of the network share buttons should be a shortlink. 

3. Turn Bitly Link Shortening OFF.

4. Create a new post. Publish it, then visit it on the front end. The destination link on any of the buttons should not be a shortlink, but should be a permalink to that post. 

5. Visit to the post you created in step 2. The buttons should no longer be using shortlinks, but the same kind of permalink you saw in step 4. 

If something did not go as described above, please let us know as a comment to this issue. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

TicketID 224422

Right now, if a user has at some point enabled Bitly links, we still use those links for the share URL even if they later disable the Bitly feature. 

We need to add a conditional that checks for this option before trying to fetch the `local_bitly_url`.

**Comment by ckmahoney** [comment]
Also: We need to delete the Bitly API key if this is switched off, or if we get a failed Bitly response because they disabled the integration.

The reason being, we've had a few customers who are confused that the button says "Connected" when they have disconnected Bitly from SW in their bitly.com settings.

**Comment by scottwyden** [comment]
This was something that came up for me, so thank you for working on this!
