### ISSUE TITLE
Mobile buttons do not place themselves correctly. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#659]
## Notes for testers

**What we expect**
The mobile buttons should behave exactly as you tell them in the Social Warfare options page.

**How to Test**

1. Go to Social Warfare -> Styles -> Floating Share Buttons. Set Floating Share Buttons to ON. Set mobile floating buttons to "top". Save changes.
2. Visit a post on mobile. Scroll down and the buttons should show up at the top of the page. 
3. Change the mobile floating buttons to "bottom". Save changes.
4. Visit a post again, and they should be on the bottom of the page. 
5. Change the mobile floating buttons to "off". Save changes.
6. Visit a post one more time, and this time there should be no SW buttons floating around.

If any of these do not go as planned, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes

Namely, setting the floating buttons are taking the exact same position as the static buttons, including left/right (which are not valid mobile floating positions). 

This may have to do with the recent changes to the SWP_Buttons_Panel file becoming two individual files, one for static buttons and one for floating buttons.

**Comment by Nicholas-Cardot** [comment]
I'm pretty sure that I fixed this in Fezzik when I rebuilt the Buttons_Panel classes. Pull that into your local and give it a quick test to confirm.

**Comment by ckmahoney** [comment]
The problem persists, even on my current state of 3.4.0.

**Comment by ckmahoney** [comment]
Commit c839193aebb65d27869aea716453e790f09082c6 references this issue.

**Comment by ckmahoney** [comment]
Various commits across mobile button issues appear to have resolved this but.

**Comment by ckmahoney** [comment]
When mobile buttons are OFF, there is still whitespace at the top of the screen where they would have been.
