### ISSUE TITLE
Popular Posts Widget defaulting to wrong post type

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#660]
## Notes for testers

**What we expect**
In the Popular Posts widget, you can select which post type to display, save it, and have that post type still be selected the next time you visit the widget. 

**How to Test**
Go to your widgets. Find the Popular Posts widget, and find the drop down for "What post type would you like to display?"

Change the value to something that is not the last item in the list. 

Save it, browse a couple pages, and then re-visit the widgets screen. 

You should see the same post type selected. 

If something did not go as described above, please let us know as a comment to this issue. 

Once you have finished testing, please give this comment a thumbs up. 

### end notes
In the popular posts widget, the new dropdown for “what post type would you like to display?” defaults to the last one in the list every time it’s saved. so if you choose posts and save, then change something else and save, it’s changing to a random (often not applicable) post type.

**Comment by DustinWStout** [comment]
Works for me.
