### ISSUE TITLE
Pinterest Description is not being fetched from post_meta. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#662]
IREF 227204

When using a SW hover "Save" button, the custom pin description gets sent with the Pin and is fine. 

However, recently using the Pinterest button, the custom pin description is not being fetched and is instead just blank.

**Comment by ckmahoney** [comment]
We can make much better use of Pro_Pinterest::get_pinterest_description. 

https://github.com/warfare-plugins/social-warfare-pro/blob/development-3.4/lib/social-networks/SWP_Pro_Pinterest.php#L221

Right now this static method is only used in the `pinterest_image` shortcode callback. 
We should also use this method any time a pinterest description needs to be fetched. 

The method currently has one required parameter `$id`. I believe this is a Post or Page id, but the method currently also uses it as an attachment id. 

We should consider letting there be three arguments: $post_id, $image_id (or $attachment_id), and $fallback_description. 

At least one ID must be provided, and $fallback_description can be optional. 

The logic for the method should reflect something like this. This one method should encapsulate all possible conditions that affect fetching a Pinterest description: 
```
1. Check if we should (A) Use the post description or (B) Use an image-specific description. 
  A) Use $post_id to fetch 'swp_pinterest_description'
  B) Use $image_id to fetch 'swp_pinterest_description' from the image 

2) If no result from 1, then check global settings for pin description source.  Use $image_id to create the description from the source. 

3) If no result from 2, use $post->post_title.
```

**Comment by Nicholas-Cardot** [comment]
The method is not used at all in generating the share link for the Pinterest button in the panel. That method is used for creating the hidden Pinterest image that is generated for use by browser extensions like the official Pinterest browser extension or Tailwind, etc.

All functionality for the actual button itself is inside the core Pinterest class. This is why the Pro_Pinterest class should probably be renamed and moved outside the /networks/ folder. That folder, for all other files, is exclusively used to house classes that pertain to the buttons in the panel. That class has absolutely nothing to do with the button in the panel. It is solely used for Pinterest functionality that is 100% outside of the buttons panel.

**Comment by ckmahoney** [comment]
I was just replying to a support ticket explaining that Pinterest seems to be currently experimenting with their API. It summarized the situation pretty well, so I'll copy the message here: 

We have recently found out that Pinterest is experimenting with the way the let people Pin using the API (like a Pinterest button).

Our plugin, Social Warfare, lets the admin specify a Pinterest description. We then deliver that description to Pinterst in the form of a link. So when you press the Pinterest button, the info in the link is what tells the popup what to include for an image and a description. For example, this is a link (from another site with a similar issue) that specifies the desscription and image to use:

pinterest.com/pin/create/button/?url=https://www.leanhealthyandwise.com/best-weighted-blankets-for-adults-kids-with-anxiety/&media=https%3A%2F%2Fleanhealthyandwise-cuseptyltd.netdna-ssl.com%2Fwp-content%2Fuploads%2F2017%2F11%2Fbest-weighted-blankets-for-adults-kids-anxiety-1.jpg&description=Check+out+the+amazing+weighted+blankets+that+can+be+safely+used+by+kids+and+adults+with+anxiety+and+sleep+problems.+Often+called+sensory+quilts+or+gravity+blankets%2C+they+will+calm%2C+relax+and+help+to+resolve+insomnia%2C+hyperactivity+and+sensory+processing+issues.+Fantastic+sleep+remedy.+%23weightedblanket+%23gravityblanket+%23weightedblanketforadults+%23weightedblanketforkids+%23weightedblanketanxiety+%23anxiety+%23anxietyrelief+%23adhd+%23insomniaremedies+%23sensoryblankets+%23sensoryquilt+via+%40leanhealthywise

But you'll notice that if you click "Save", the description that actually gets pinned is very different from the description in the popup box.
This is entirely in Pinterest's hands; we gave them everything we could, and they decided to do something else.

**Comment by ckmahoney** [comment]
Clicking the same link 

pinterest.com/pin/create/button/?url=https://www.leanhealthyandwise.com/best-weighted-blankets-for-adults-kids-with-anxiety/&media=https%3A%2F%2Fleanhealthyandwise-cuseptyltd.netdna-ssl.com%2Fwp-content%2Fuploads%2F2017%2F11%2Fbest-weighted-blankets-for-adults-kids-anxiety-1.jpg&description=Check+out+the+amazing+weighted+blankets+that+can+be+safely+used+by+kids+and+adults+with+anxiety+and+sleep+problems.+Often+called+sensory+quilts+or+gravity+blankets%2C+they+will+calm%2C+relax+and+help+to+resolve+insomnia%2C+hyperactivity+and+sensory+processing+issues.+Fantastic+sleep+remedy.+%23weightedblanket+%23gravityblanket+%23weightedblanketforadults+%23weightedblanketforkids+%23weightedblanketanxiety+%23anxiety+%23anxietyrelief+%23adhd+%23insomniaremedies+%23sensoryblankets+%23sensoryquilt+via+%40leanhealthywise

Now produces the expected Pinterest description that we passed in the URL. 
Notice we made no change to the URL, which supports the notion that Pinterest makes changes to their API without regard to the existing parameters.
