### ISSUE TITLE
Fix the $title in Flipboard shares. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#667]
## Notes for testers

**What we expect**
When sharing via Flipboard, the post title should appear as  the title in the popup dialogue. 

**How to Test**

1. In Social Warfare -> Display -> Social Networks, make sure Flipboard is in your Active networks. Save changes if necessary.
2. Create a new post. Give it the title "Sweet Flipboard Kombucha" and any content for the content. Save the post.
3. View the post, and click the Flipboard button. The popup dialogue should have the title "Sweet Flipboard Kombucha" exactly like that displayed. 

If something does not go as described above, please let us know in the comments. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes
Currently the query parameter `title` is hardcoded as `title=Tools%20-%20Flipboard`, which means it always displays "Tools Flipboard" when sharing using our button. 

https://github.com/warfare-plugins/social-warfare-pro/blob/master/lib/social-networks/SWP_Flipboard.php#L43
We need to let that be a variable instead, and let it use the Post Title as a default value.

**Comment by Nicholas-Cardot** [comment]
Good catch. That should be a quick and easy fix. :-)
