### ISSUE TITLE
Do not print a browser extension pin image if Browser Extensions is OFF.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#669]
## Notes for testers

**What we expect**
An extra pinterest image is not inserted after turning Browser Extensions OFF.

**How to Test**

1. In Social Warfare -> Advanced -> Advanced Pinterest Settings, change Pinterest Image for Browser Extensions to ON.  Set the location to "bottom", and save it.
2. Set Pinterest Image for Browser Extension to OFF, and save it.
3. Create a new post. Give it a Pinterest image. Save the post. 
4. View the new post. The chosen Pinterest image should not be at the bottom of the post content.

If something does not go as described above, please let us know in the comments. 
Once you have finished testing, please give this comment a thumbs up. 

### end notes

In Social Warfare -> Advanced -> Advanced Pinterest Settings, 

Replication:
1. Set Pinterest Image for Browser Extensions to ON, set the location to top, and save it.
2. Set Pinterest Image for Browser Extension to OFF, and save it.
3. View a post with a defined pinterest image. There will be a pin image at the top of the post because of step 1.

**Comment by DustinWStout** [comment]
Can't seem to get Pin Image for Browser Extensions to work ON... so, yea... I guess that means the OFF switch will work just fine. 😂

**Comment by DustinWStout** [comment]
This is working! 

(Deleted my previous comment about it not working... I had a page-level setting wrong.)
