### ISSUE TITLE
Hidden Pinterest image is not being printed to the source code. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#671]
## Notes for testers

**What we expect**
You can set a Pinterest image for a post, and that image will be the pinned image no matter which Pinterest/Save button they press on a page.

**How to Test**

1. In Social Warfare -> Advanced -> Advanced Pinterest Settings, turn Pinterest Image for Browser Extensions ON. Set Pinterest Image Location to 'top'. Save changes. 
2. Create a new post. Give it a pinterest image. 
3. In the metabox Social Warfare set, the Pinterest Image Location to 'bottom'. 
4. Give the post some content, publish, and view it. It should have an image at the bottom, below the content but before any share buttons. 
5. Edit the post. Set the image location to 'hidden'. Update post. 
6. View the post on the front end. There should not be a pinterest image displayed. In the source code, you should find the text `swp-pinterest-image` (on an Image element). 

If any of the steps do not go as described, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes
IREF 235200 & others

Yesterday I noticed the top and bottom Pinterest Image works fine. However, as customers have pointed out, the hidden pin does not appear at all. 

Bring it back!

**Comment by Nicholas-Cardot** [comment]
I just tested this in the refactored version in 3.4.0 and it is outputting just fine according to how it's supposed to work.

**Comment by ckmahoney** [comment]
I'm not able to replicate it not working. It is fine for me for top, bottom, and hidden images. 

Note that the CSS selector for hidden images is `.swp_hidden_pin_image`. 

Can you please DM me logins to your test site? @DustinWStout

**Comment by DustinWStout** [comment]
@ckmahoney sorry about that... thought I updated this but must have been on another issue. This was a misconfiguration on my part. All good now.

**Comment by ckmahoney** [comment]
Currently, I am not able to get a hidden Pinterest image printed to the source code. 
Visible pinterest images display as expected.

**Comment by Nicholas-Cardot** [comment]
What are your settins? Because this is working properly for me. 

Pinterest Image for Browser Extension "On"
Pinterest Imae location "hidden"

The post has a Pinterest image, rigght?

**Comment by ckmahoney** [comment]
When you did that, did you confirm that it is printed in the source? You can look for <img.swp-pinterest-image>

**Comment by ckmahoney** [comment]
You are right, it is not an image of class 'swp-pinterest-image', but is actually 'swp_hidden_pin_image'. 

I just added the class 'swp_hidden_pin_image' as well, just so we can have a common classname among all of our Pinterest images.

**Comment by meymigrou** [comment]
I'm testing with WordPress 5.0-RC1-43944 running Twenty Nineteen theme. While everything looks good, I can't find the "swp-pinterest-image" on the source code of the post.
