### ISSUE TITLE
Menu Button

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#672]
It is not always good to display floating share buttons. For example 1) mobile browsers have such small screen real estate that floating buttons get in the way of the content, 2) some advertisers place ads in the website footer that are covered by floating buttons set to display at the bottom of the screen, and 3) sites that use sticky menus have their menus covered by floating social buttons when the buttons are set to display at the screen top.

A solution would be to place a share button into the site's menu. This button would display a popup modal or sub menu list of networks when clicked. This share button placement could be selectable for view at different breakpoints e.g. desktop, tablet, mobile.

Could this be added to Social Warfare 3.4 ?

**Comment by ckmahoney** [comment]
Hello @VR51,

We have outlined in the repo's readme the process for creating issues. Please follow the directions here before opening any future issues. 

https://github.com/warfare-plugins/social-warfare#guidelines-for-submitting-issues-to-this-github-issue-tracker

Thank you,
Cortland Mahoney 
Warfare Plugins Development
