### ISSUE TITLE
Make the settings page and icons accessible for screen Readers. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#674]
IREF 241907

Users viewing our buttons with a screen reader are presented with 'f', 'b', 'c', etc.  rather than network names. 

In the options page, the icons can not be drag & dropped because of how screen readers operate. 

Links provided in the ticket:
webaccess.berkeley.edu/resources/tips/web-accessibility
webaccess.berkeley.edu/ask-pecan/what-is-a-screen-reader

**Comment by SquanchyMe** [comment]
See additional info/notes on internal ticket# 241907
