### ISSUE TITLE
Accented characters issue for Twitter share

### ISSUE THREAD

**Issue by APEWAW** [warfare-plugins/social-warfare#675]
Hello, 

The accented characters (French) bug in the sharing text for Twitter, as you can see on the attached screenshot. For example, it displays "%c3%a9" instead of "é". 

Thanks for your help!

![capture d ecran 2018-11-28 a 17 42 12](https://user-images.githubusercontent.com/17066439/49167156-17a05580-f335-11e8-9417-a10abc70ebb1.png)

**Comment by ckmahoney** [comment]
Hi @APEWAW , 

We pushed an update about three minutes ago that fixes this problem. Please update both core and pro to version 3.4.0.

Thank you,
Cortland Mahoney

**Comment by APEWAW** [comment]
Hello, 

The update to version 3.4.0 just crashed my WP...

Thanks for your help
