### ISSUE TITLE
Frame Buster feature needs to be updated.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#682]
# Notes for testers

If you use Sniply, Aggregagage, Bloglovin', or some other framing service, you are eligible to fully test this issue. Otherwise you can partially test it.

1. In Social Warfare > Advanced, turn Frame Buster ON and Save Changes. 
2. Visit a post and view the source code for the page. (You should be able to right click and select 'View Page Source'). 
3. Search for the keyword `parentIsEvil`. If the text exists, partial testing is complete. 
4. Go to your framing service and frame the content of the post that has a confirmed `parentIsEvil`. View the framed content using the service. If our `parentIsEvil` function is working, it should redirect you back to your real blog from the framed content. 
#
original issue

IREF 254752

This customer purchased SW specifically for the frame buster feature and has found that it does not work. 

Customer's site: 
https://turbigo-gourmandises.fr/

iFraming site:
https://www.hellocoton.fr/to/2J5go#https://turbigo-gourmandises.fr/samossas-de-saumon-frais-marine/

**Comment by nutsandbolts** [comment]
Another customer has mentioned http://www.aggregage.com/ as another one our frame buster isn't currently stopping.

**Comment by nutsandbolts** [comment]
And Sniply.

**Comment by nutsandbolts** [comment]
Bloglovin'

**Comment by ckmahoney** [comment]
This issue has been annotated and is ready for testing.
