### ISSUE TITLE
Update LinkedIn API to v2. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#684]
"In addition to the changes listed below, all developers need to migrate to Version 2.0 of our APIs and OAuth 2.0 by March 1."

https://engineering.linkedin.com/blog/2018/12/developer-program-updates

Fortunately we are planning an update before March 1st.

**Comment by ckmahoney** [comment]
It looks like with LinkedIn's new share API (being forced on March 1st) requires oAuth tokens to share an article to LinkedIn for the user. 
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin/consumer/context#creating-a-share-on-linkedin

This is not the path we want to take, because we want our customer's visitors to share to their own page, not to share to the customer's page. 

They do still have an option for using a share link (similar to how we have it currently set up), but the new option will require loading LinkedIn's third party JS. 
https://engineering.linkedin.com/blog/2018/12/developer-program-updates

**Comment by ckmahoney** [comment]
No edits were made to the LinkedIn API. 
The state of SW + LinkedIn then is to hope that LinkedIn still offers URL based sharing after March 31st.

**Comment by Nicholas-Cardot** [comment]
The URL based sharing remained in-tact and these API changes had no bearing on the way that our plugin passes them information. As such, this is no longer a valid issue.
