### ISSUE TITLE
Update type check in `calculate_network_shares()`

### ISSUE THREAD

**Issue by Manhattan809** [warfare-plugins/social-warfare#689]
# Notes for testers
This was not an issue we could replicate, therefore we can not provide instructions on how to test.

Please keep an eye out for errors in Query Monitor as you test. If an error comes from the file SWP_Post_Cache, then it is related to this issue. 
#
original issue

IREF 261980

social-warfare/lib/utilities/SWP_Post_Cache.php on line 782

One of these things on L782 is not a number:
`$share_counts['total_shares']`
$count

**Comment by ckmahoney** [comment]
Annotated and ready for testing.
