### ISSUE TITLE
Follow Widget Todos

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#690]
SWFW Functionality:
- [x] counts not showing for pinterest
- [ ] ~~counts not showing for reddit~~
    - Reddit does not offer a follow count API. We can use the Karma instead if you want.
- [x] counts not showing for tumblr
- [x] counts not showing for vimeo
- [ ] Regenerate application keys and secrets. 

SWFW back-end:
- [x] ~~after saving the widget the icons disappear~~
- [x] ~~when the icons have a color background they're too big (no padding in the box)~~
- [x] background color on icons is buggy--can't tell when that behavior is actually supposed to activate and doesn't work 99.9999999999% of the time... should probably just eliminate it altogether and leave the icons static no matter what state the widget is in
- [x] change icons from SVG to sw-icon-font. 

SWFW front-end:
- [x] `.swfw-button` default padding should be `padding: 20px;` instead of `padding: 20px 10px`
- [x] remove the following attributes from `.swfw_block_button .swfw-cta-button` - `height`, `width`, `margin-right`
- [x]  change top/bottom padding on `.swfw_block_button .swfw-cta-button` to 5px (instead of 0) and add `font-size: 14px;`
- [x] add the following attributes to `.swfw_block_button .swfw-cta-button a div` - `font-size: 14px; font-weight: bold;`
- [ ] the `color` attribute on all `.swfw_block_button .swfw-cta-button a div` should vary based on the background-color for the social network
- [x] change following attributes on `.swfw_buttons_button` - `border-radius: 4px; padding: 5px 15px;`
- [x] change border radius on square buttons to 4px
- [x] add the following attribute to `.swfw_square_button .swfw-cta` - `font-size: 12px;`
- [x] change all instances of #fefefe to #fff 
- [x] Snapchat buttons need black (#000) text/icon color
- [x] snapchat button should just say "follow" instead of "follow me"
- [x] not enough padding at the top of the Square style
- [x] leaf & pills styles still doesn't have enough padding (too thin)
- [x] eliminate text-decoration: underline on follow buttons
  - Where do you see this happening?
- [x] instagram and vimeo icons not showing
- [x] shift style is too sharp (should be rounded corners just like the flat/fresh style)
- [x] buttons overlapping widgets below it
- [x] icons are black instead of white
- [x] box style has no icons and is a column instead of filling out a row (or multiple rows when they don’t fit a single line)
- [x] block/leaf/shift styles don’t have enough padding (too thin)
- [x] vimeo outline color needs to change to #069bd1
- [x] icons are too large in block/leaf/shift/buttons styles and need to be a maximum of 24px tall

**Comment by ckmahoney** [comment]
Last updated: Tue Feb 05 2018 4:34pm EST
[social-follow-widget-0.0.97b.zip](https://github.com/warfare-plugins/social-warfare/files/2833978/social-follow-widget-0.0.97b.zip)

Last updated: Tue Feb 05 2018 4:34pm EST
[social-warfare-dev-3.5.zip](https://github.com/warfare-plugins/social-warfare/files/2833979/social-warfare-dev-3.5.zip)

Last updated: Tue Feb 05 2018 4:34pm EST
[social-warfare-pro-dev-3.5.zip](https://github.com/warfare-plugins/social-warfare/files/2833980/social-warfare-pro-dev-3.5.zip)

**Comment by DustinWStout** [comment]
Updated.

**Comment by ckmahoney** [comment]
Instagram and Vimeo icons show, you just need the most recent copy of Core 3.5.
Also can we please have Snapchat, Flickr, and Ello icons added to the icon font?

**Comment by Nicholas-Cardot** [comment]
This should be migrated to the follow widget repository.
