### ISSUE TITLE
3.5.x Hot Bugfixes

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#694]
The following is the list of known issues in 3.5.0 which are being released in soft updates and will ultimately be released in 3.5.2 later this week.

**Unreleased bug statuses:**
- [ ] [ready for testing] Updated addon registration to register/unregister without error.
- [ ] [ready for testing] Pinterest pins pulling title, not Alt Text when specified
- [ ]  [could not replicate] Share recovery broken:
Post cache output= 
https://seimeffects.com/lumist/?swp_cache=rebuild&swp_debug=post_cache
https://seimeffects.com/lumist/?swp_debug=get_user_options (does not match cache output)
- [x] [ready for testing] The CTT adds an '@' even if there is no handle. 
- [ ]  [ready for testing] Pinterest Custom Description adds 'Via @' even if there is no handle
- [x]  [soft updated] Several Open Graph tag properties are misconfigured.
- [x] [soft updated] Twitter cards are not priting correctly.
- [ ] [ready for testing] Icon font loading improperly

**Fixed and released in a soft update:**

**3.5.2 RELEASE ESTIMATE: TBD**

**Fixed and released in 3.5.1:**
- [x] rendered Pinterest Description exceeds 500 characters.
- [x] Buttons shortcode error on blogroll pages. 
- [x] Total shares count is off.
- [x] PHP warning thrown in SWP_Addon.php 
- [x] PHP warning thrown when pinterest_username not filled out.
- [x] Custom color CSS not being output.
- [x] Side buttons not showing/hiding on scroll.
- [x] _Notice: Undefined property: SWP_Pro_Header_Output::$open_graph_data in /www/upserve/wp-content/plugins/social-warfare-pro/lib/frontend-output/SWP_Pro_Header_Output.php on line 69_
- [x] _Notice: Undefined property: SWP_Pro_Header_Output::$twitter_card_data in /www/upserve/wp-content/plugins/social-warfare-pro/lib/frontend-output/SWP_Pro_Header_Output.php on line 70_

**Comment by ckmahoney** [comment]
Soft update has been pushed for the following items: 
- [x] PHP warning thrown when pinterest_username not filled out.
- [x] _Notice: Undefined property: SWP_Pro_Header_Output::$open_graph_data in /www/upserve/wp-content/plugins/social-warfare-pro/lib/frontend-output/SWP_Pro_Header_Output.php on line 69_
- [x] _Notice: Undefined property: SWP_Pro_Header_Output::$twitter_card_data in /www/upserve/wp-content/plugins/social-warfare-pro/lib/frontend-output/SWP_Pro_Header_Output.php on line 70_

**Comment by iHelpers** [comment]
@Nicholas-Cardot

**Comment by ckmahoney** [comment]
This has been pushed in a soft update
- [x] Total shares count is off.

**Comment by SquanchyMe** [comment]
Just added
Not passing Pinterest descriptions & hashtags
The CTT adds an '@' even if there is no handle.

**Comment by SquanchyMe** [comment]
Removed 'Not passing Pinterest descriptions & hashtags' per our discussion

**Comment by SquanchyMe** [comment]
added Share recovery broken

**Comment by SquanchyMe** [comment]
added: Pinterest pins pulling title, not Alt Text when specified

**Comment by SquanchyMe** [comment]
**"Pinterest pins pulling title, not Alt Text when specified"**
When i add an Alt Text description to an image, using the Social Warfare Pinit button, i DO get the Alt-Text for the image, but if i enter no Alt-Text, i get "undefined" as the description, which is likely not acceptable.

When using the Chrome Pinterest extension Pinit button, i get the page-title, no matter what

**Comment by SquanchyMe** [comment]
**The CTT adds an '@' even if there is no handle**
Working as expected

**Comment by SquanchyMe** [comment]
**Pinterest Custom Description adds 'Via @' even if there is no handle**
_NOT resolved._. 
still seeing 'Via @' in posts with custom Pinterest descriptions and no handle set in Social identities.

**Comment by SquanchyMe** [comment]
Pinterest pins pulling title, not Alt Text when specified
NOT resolved..
Getting either the title, or "pin" for images with ALT text

**Comment by SquanchyMe** [comment]
**Pinterest Custom Description adds 'Via @' even if there is no handle**
Working as expected

**Comment by SquanchyMe** [comment]
**Pinterest Custom Description adds 'Via @' even if there is no handle**
Not resolved.. still a lonely 'via @' when no pinterest handle is in Social Identity

**Comment by SquanchyMe** [comment]
**Pinterest pins pulling title, not Alt Text when specified**
all i'm getting is "pin"
![pin](https://user-images.githubusercontent.com/39499655/54385964-1df0de00-4655-11e9-8bf3-4bd20325fd81.jpg)

**Comment by SquanchyMe** [comment]
**Updated addon registration to register/unregister without error**
register/unregister/re-register works as expected
Register with invalid license works as expected
_Registering with an IN-USE key returns "invalid" instead of "IN USE"_
