### ISSUE TITLE
Make API requests to urls with and without trailing slashes. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#695]
Some social networks, such as Pinterest, consider a URL with a trailing slash to be a different URL than the same without the slash. When it comes to counting shares, this is obviously no good because we need either URL to report the same number of shares. 

One way around this would be to make sure we are always fetching counts for both types of URL: With and without the trailing slash.

This would be the place to start
https://github.com/warfare-plugins/social-warfare/blob/d3f9eb50effe4b17e0b829c9057e277777666530/lib/utilities/SWP_Post_Cache.php#L441

And might involve something like this 
```
foreach( $links as $url ) {
        $base_url = $swp_social_networks[$network]->get_api_link( $url );
	$base_url = trim( $base_url, '/' );
	api_urls[$current_request][$network][] = $base_url;
	api_urls[$current_request][$network][] = $base_url . '/';
}
```

**Comment by Nicholas-Cardot** [comment]
This has now been implemented for Pinterest share count requests. I've also built in the functionality for adding this to other social networks by simply adding their key to a $eligible_networks array. Right now, however, there seems to be no need for adding it to other networks.
