### ISSUE TITLE
Missing Class SWP_Pro_Pinterest -- A Simple Fix

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#697]
Activation of Social Warfare Pro fails in some instances. PHP throws a fatal error fit due to the deferred loading of the class SWP_Pro_Pinterest. This could be related to the missing Pinterest username issue resolved in a soft-fix.

A quick solution is to check for the class before it's loaded. This doesn't seem to interfere negatively with the plugin's features after activation has successfully completed.

**File**

social-warfare-pro/lib/Social_Warfare_Pro.php

**Line**

240

**Existing Code**

```
public function instantiate_deferred_classes() {
	new SWP_Pro_Options_Page();
	new SWP_Pro_Pinterest();
}
```

**Fixed Code**

```
public function instantiate_deferred_classes() {
	new SWP_Pro_Options_Page();
    	if (class_exists('SWP_Pro_Pinterest')) {
		new SWP_Pro_Pinterest();
        }
}
```

On another note, should G+ be removed now?

**Comment by ckmahoney** [comment]
Hi @VR51,

We limit ticket creation to warfare plugins staff. Please view our guidelines for support. 

Further, please do not use the code in the snippet above. If your copy of Social Warfare Pro is missing the SWP_Pro_Pinterest class for whatever reason, adding the `class_exists` conditional might prevent errors from being thrown, but it will not restore missing Pinterest features. Not sure how that error is being thrown; please make sure you are downloading directly from https://warfareplugins.com when you get new copies of Pro, or update directly from in the dashboard.

**Comment by ckmahoney** [comment]
The guidelines are here @VR51 
https://github.com/warfare-plugins/social-warfare#guidelines-for-submitting-issues-to-this-github-issue-tracker
