### ISSUE TITLE
Pinterest share adding \ after special characters 

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#698]
V3.5.19 / V3.5.2
When Alt-Text for an image has an apostrophe our double-quote, for example "this is isn't good text", when sharing via a floating Pinit button, " \ " is being appended resulting in "This isn\'t good text"

**Comment by SquanchyMe** [comment]
Seeing this with " as well as '

**Comment by Nicholas-Cardot** [comment]
This should now be resolved.
