### ISSUE TITLE
Dashboard nav display

### ISSUE THREAD

**Issue by jarrodwhitley** [warfare-plugins/social-warfare#699]
<img width="336" alt="Social Warfare ‹ Boomer Benefits — WordPress 2019-03-19 11-54-14" src="https://user-images.githubusercontent.com/11711674/54626280-e14f2900-4a3e-11e9-98d5-1b98643a5823.png">

This is merely an aesthetic concern, but it looks bad. The nav does not extend all the way across the screen.

I managed to fix it with:
```
.sw-grid.sw-col-940.sw-top-menu {
    width: 100%;
    padding-right: 244px;
    box-sizing: border-box;
}
```
![screencast 2019-03-19 12-12-10](https://user-images.githubusercontent.com/11711674/54627003-67b83a80-4a40-11e9-9f41-9c660baeda16.gif)

**Comment by ckmahoney** [comment]
Hello @jarrodwhitley ,

It is rare that we have somebody both open an issue _and_ have a good patch ready to suggest! Thanks for submitting the snippet, and I'll bring it up with our team to see if we can include it for a future release.
