### ISSUE TITLE
Add a feature for automatically posting newly published articles to social networks

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#7]
Some users want the ability to connect their social accounts to the plugin and have new articles automatically posted when they are published.

**If this a feature you are interested in, please comment below expressing your support.**

**Comment by lisaleague** [comment]
If there are a lot of requests for this, provide it as an add on extension. This would keep the core plugin light, and avoid redundant features for those that already use another plugin for this.

**Comment by Nicholas-Cardot** [comment]
@lisaleague That's a great idea. And it's for that same reason that this is a pretty low priority in my opinion. There are quite a few great plugins that allow for this functionality already.

**Comment by nwilson99** [comment]
I would be interested in this.
