### ISSUE TITLE
`array` sometimes prints to the font end. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#704]
IRE 283206, 282601, 284834

This is what it looks like. 
![Screenshot two](https://warfareplugins.com/wp-content/uploads/awesome-support/ticket_284834/Capture-d%E2%80%99%C3%A9cran-2019-03-27-%C3%A0-09.06.57.png)

![Screenshot one](https://warfareplugins.com/wp-content/uploads/awesome-support/ticket_282601/Capture-d%E2%80%99e%CC%81cran-2019-03-24-a%CC%80-00.33.45.png)

**Comment by ckmahoney** [comment]
The problem only happens when Pro is active.

**Comment by ckmahoney** [comment]
The bug seems to have resolved itself on both of the linked sites above. Here is a screenshot to compare the second of the two links. 

![Screen Shot 2019-04-01 at 6 35 39 PM](https://user-images.githubusercontent.com/26120849/55363990-fd29e480-54ac-11e9-8058-24320c6984af.png)

**Comment by Nicholas-Cardot** [comment]
This should now be resolved.
