### ISSUE TITLE
Static panels and floating buttons do not display on page as expected. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#705]
IREF 283008, 283004, ~~283908~~

There are no instances of `.swp_social_panel` at all on some pages, even though the settings dictate both floating and static panels should exist. 

affected URL 
http://www.travelherstory.com/accommodations/syha-scotland-charity/

**Comment by ckmahoney** [comment]
Or, invisible panels with no buttons occupy space above/below the content.

**Comment by Nicholas-Cardot** [comment]
This is mostly resolved and only seems to happen in very, very rare fringe cases now with workarounds available.
