### ISSUE TITLE
Facebook shares should not be updated if share counts are not displayed

### ISSUE THREAD

**Issue by wichtounet** [warfare-plugins/social-warfare#707]
Hi, 

On my website, I have disabled the share counts and total share counts. However, SWP still try to update Facebook share counts. This results in two requests, one to admin-ajax and one to Facebook graph API. There is no point in updating the share counts if they are not displayed.  

This line: 
https://github.com/warfare-plugins/social-warfare/blob/10b371c63a2bcc8d306210945872d03d9160e638/lib/social-networks/SWP_Facebook.php#L46

Should only be done if share counts are enabled. For now, I have simply removed this line and everything is working as expected. 

Would it be possible to disable share updates entirely when share counts are disabled?

Thanks

**Comment by Nicholas-Cardot** [comment]
Yes, this is actually a great idea. Thanks for that.

**Comment by wichtounet** [comment]
This seems to be fixed with 417b3b25481dbed9c72d7817588160debdfe200b
