### ISSUE TITLE
Empty <p> added after buttons panel. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#708]
The empty `<p>` actually looks like a browser's attempt to render an invalid second `<!DOCTYPE><html>` tag. 

No lead on the cause yet, and it only seems to happen on above the content buttons (even if there are below the content buttons on the page as well). 

It could be that, since our buttons prepend themselves to the_content, there is a particular theme that embeds an entirely new HTML document for the content. Then our buttons panel unknowingly interrupts the structure. 

view-source:https://dhbriefs.com/benefit-digital-health-revolution/
![digitalbreifs](https://user-images.githubusercontent.com/26120849/55361225-8c7eca00-54a4-11e9-888e-f4d88144cb6b.png)

**Comment by ckmahoney** [comment]
IREF 281931

**Comment by ckmahoney** [comment]
IREF 281117 reports this only happens when "Add data-pin-description to images that do not have one" is ON.

**Comment by wichtounet** [comment]
I have this issue on the standard version of Social Warfare not in the Pro. Since none of the functions changed by the two commits are present in the standard version, I do not know what to do.

**Comment by wichtounet** [comment]
And this happens to me regardless if I have any button on the page. I have set everything to manual placement and if I remove social_warfare() function calls, it still happens.
