### ISSUE TITLE
Pin-it is applying display: table; which is blowing out image.

### ISSUE THREAD

**Issue by chrisaram** [warfare-plugins/social-warfare#711]
The Social Warfare's pin-it code is applying a container div with display: table; which causes its contents to "spill out" over the max-width: 100%; selector which is otherwise respected if using a display: block; for example.

This occurs even when pinning is disabled within the plugin settings.

Please see attached screenshot.
![Social-Warfare-pin-it-blowing-out-image-max-width](https://user-images.githubusercontent.com/621411/56669421-1d4d5d80-667f-11e9-869a-9be6eedefb1e.png)

**Comment by ckmahoney** [comment]
Good afternoon @chrisaram 

Thanks for reaching out. This is the first I have heard of this issue and I have not seen a ticket in the development box referring to this issue yet. This could mean that you haven't opened it yet, or that it has not reached development yet. 

If you have not already, please open a ticket as indicated by our [issue guidelines](https://github.com/warfare-plugins/social-warfare#guidelines-for-submitting-issues-to-this-github-issue-tracker).

If a ticket is already open, you can re-open this issue with a link to the ticket. Only yourself and Warfare Plugins administrators will be able to view the contents of the ticket. 

All the best,
Cortland Mahoney
