### ISSUE TITLE
CTT blank if quotes are included

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#712]
see internal ticket 295714

**Comment by ckmahoney** [comment]
I have been able to replicate this. Quotations in either the display text or the tweet text will make that field entirely blank.

**Comment by ckmahoney** [comment]
Actually I think the customer right be right when she said 'I guess you can't use "quotes" inside'. 

It is a conflict with how Gutenberg stores data now compared to how we processed it with the classic editor. 
Typically we would expect to see the CTT stored as post meta which we can easily read and parse with PHP. 
Gutenberg instead embeds the data into the content and converts quotations to entities. I tried slashing/escaping them both before and after storage and neither worked. 
If we can not get an escaped value into the shortcode before the callback function is reached, all of the shortcode `$atts` are corrupted.

**Comment by Nicholas-Cardot** [comment]
I don't believe that we have ever supported quotation marks in the CTT's. Especially when it was a standalone shortcode within the post content. All attributes use quotations marks and hence any included would break it.
