### ISSUE TITLE
[New] Add Support for OpenShareCount as a Source for Twitter Share Counts

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#713]
More reports every day of Twitcount being unreliable and it appears that OpenShareCount is stable again.

**Comment by SquanchyMe** [comment]
Twitcount appears to be down/not working again, for the last few days.

**Comment by SquanchyMe** [comment]
More reports of very slow count updates and 1 report of "sorry, try later" (for several days) when trying to sign-up..

**Comment by Nicholas-Cardot** [comment]
This has now been added to the plugin and is ready for testing. :-)

**Comment by Nicholas-Cardot** [comment]
### 🔎 Testing Guidance 🧪

1. Go to the admin options page for Social Warfare.
2. Navigate to the "Social Identity" tab and scroll down to the "Tweet Count Registration" section.
3. Activate tweet counts.
4. Select OpenShareCount as the source.
5. Ensure that you are properly registered with the OpenShareCount service. 
6. Check to see if our plugin is pulling in the share counts being reported by their service. 

Report back in the comments below whether it worked properly or not. Report on what you encounter.
