### ISSUE TITLE
License key and Pro settings disappear on deactivation. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#716]
A number of customers have reported that, if Pro is deactivated for a little bit and then later re-activated, they have to re-enter the Pro license key and re-enter the Pro settings.

**Comment by SquanchyMe** [comment]
I have seen a few reports of this, but I have not yet been able to re-produce it.

**Comment by Nicholas-Cardot** [comment]
Closing for now. Will reopen if we get further reports or leads on this.
