### ISSUE TITLE
Button display control at page level

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#72]
Having the ability to modify exactly which buttons show up on pages. Through shortcode it could look something like:

[social_warfare buttons="twitter facebook google_plus"]

This would display ONLY Twitter, Facebook and Google+ buttons. 

OR

[social_warfare buttons="all"]

This would display all buttons available. 

Might also be good to add into the Social Warfare Custom Options box inside post/page editor.

**Comment by Nicholas-Cardot** [comment]
This is a duplicate.
