### ISSUE TITLE
[Final Troubleshooting] Add Social Follow Buttons

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#720]
**Bugs in 4.0**:

## Button Styles
- [x]  `.swp_modern .swp_share_link, .swp_dark .swp_share_link` CSS needs to change to `height:61px!important;`

### function
- [ ]  connection buttons seemed to be “connected” but when clicking “disconnect [network]” it led to a weird page on the network that didn’t have any indication of disconnectability, and when I returned to the SW settings page it had refreshed and I was back on the Display tab. When I navigated to the display tab, that network which I had clicked had the “Login with [network]” button now.
- [ ]  when I used “login with Pinterest” it seemed to work fine except that when I returned to the social identity tab, immediately after approving the connection the button still said “login with Pinterest” as if I hadn’t connected it successfully
- [ ]  login with Tumblr goes to a page that says “Could not connect to Tumblr. Refresh the page and try again later.”
- [ ]  instagram widget displaying how many people the user is following rather than how many people are following the user
- [x]  medium widget needs to add an `@` before the username in the medium URL (ex. medium.com/@dustinwstout)

### style (settings page)
- [x]  remove `width:200` from `.swp-authorization-button`
- [x]  change `line-height:15px;` to `line-height:1;` for `.swp-authorization-button`
- [x]  add rule `a.swp-button.swp-authorization-button { padding: 15px;}`
- [x]  add rule `a.swp-button.swp-authorization-button:active, a.swp-button.swp-authorization-button:focus, a.swp-button.swp-authorization-button:hover {color: #fff;outline: none;box-shadow: none;}`
- [x]  add `margin-top: 4px;` to `.swp-authorization-button i.sw`
- [x]  widget CSS (back-end AND front-end) is all off…

### style (front-end)
- [x] change `.swfw-follow-button.swfw_pill_button, .swfw_pill_button.swfw_block_button, .swfw_pill_button.swfw_buttons_button, .swfw_pill_button.swfw_square_button { padding: 20px; }` to `padding: 10px;`
- [x] change `.swfw-follow-button.swfw_leaf_button .swfw-cta-button a div, .swfw-follow-button.swfw_pill_button .swfw-cta-button a div, .swfw-follow-button.swfw_shift_button .swfw-cta-button a div, .swfw_block_button .swfw-cta-button a div, .swfw_leaf_button.swfw_buttons_button .swfw-cta-button a div, .swfw_leaf_button.swfw_square_button .swfw-cta-button a div, .swfw_pill_button.swfw_buttons_button .swfw-cta-button a div, .swfw_pill_button.swfw_square_button .swfw-cta-button a div, .swfw_shift_button.swfw_buttons_button .swfw-cta-button a div, .swfw_shift_button.swfw_square_button .swfw-cta-button a div { padding: 0 15px; }` to `padding: 5px;`
- [x] square styling needs work on the CTAs. currently they're way off center, outside the square they belong to.

**Comment by Nicholas-Cardot** [comment]
Okay, all the style items are finished from the checklist.
