### ISSUE TITLE
Doctype and line breaks at beginning of the_content()

### ISSUE THREAD

**Issue by r-obeen** [warfare-plugins/social-warfare#721]
Hello,
After installing Social Warfare 3.6.1 (I was on 3.6.0 before) I have an issue at the beginning of every post description (using `the_content()`). I have this being printed before the content :
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"><br />
<html><body><br />
```

I have caught that Social Warfare was responsible for that. Deactivating the plugin was resolving the conflict and when I rollback to V3.6.0, everything is fine again.

Can you guys investigate on that ? I will rollback to V3.6.0 meanwhile. Thanks

**Comment by Nicholas-Cardot** [comment]
This should already be fixed in our development-4.0 branch. As such, I'm closing this as invalid. Feel free to download the core and pro 4.0 versions from here on GitHub to test them out.

**Comment by r-obeen** [comment]
Woa, thanks for the lightning quick response. V4.0 did resolve the issue.

**Comment by Nicholas-Cardot** [comment]
You're welcome. Happy to help. We're also adding a "Follow Widget" to version 4.0. So feel free to play around with that and give us any feedback you might have. :-)
