### ISSUE TITLE
Clarify input syntax for entering custom colors

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#722]
When entering any custom colors (Styles|Custom Color) either the color should work with or without adding the "#" before the hex code - ie; either #ced3dc or ced3dc should work - OR, a notice should be shown specifying that the "#" must be included as part of the code.  Currently custom colors will not work without # included ..

**Comment by Nicholas-Cardot** [comment]
Okay, this should now be fixed in version 4.0.0.
