### ISSUE TITLE
[JS Conflict] Custom Social Warfare Options Gone, or only partially displaying

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#732]
In the last 10 days we've seen a sharp increase in reports of this issue - either no Social Warfare custom options showing, or parts, such as the custom image, custom pinterest image, etc, are not displaying.
First one checked has a memory limit of 512mb.

**Comment by SquanchyMe** [comment]
This appears to have begun with the WP 5.3 update.
One customer reported it "was a theme problem" and he was able to fix it.  I am awaiting more details on what/how it was resolved.

**Comment by SquanchyMe** [comment]
This is what the theme developer told the customer:
_If they have jQuery in the backend called via “$”, with the latest WP update it must be called via “jQuery”_

**Comment by SquanchyMe** [comment]
Another customer reports that when Yoast SEO is disabled, the Custom Option fields display correctly.

**Comment by Nicholas-Cardot** [comment]
I've made some adjustments to the JS in the meta box files that may fix this. As such, let's get the 4.0 version off the dev branch sent to the customers who are experiencing this and see if it takes care of it.

**Comment by SquanchyMe** [comment]
I believe this has been resolved in one of the recent patches; no new reports in over 60 days.
