### ISSUE TITLE
[GH 736] Custom Pinterest Description Not Included on Pins

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#736]
When pinning a page the Pinterest Custom Description entered in the Social Warfare Custom Options for the page is not reflected on the pin.
If a custom description is entered for the image in the image gallery, that description is also ignored.
See internal ticket #347484 for a good explanation, including a customer-created video demonstrating the issue

**Comment by Nicholas-Cardot** [comment]
I don't know of any potential solution to this issue. As far as I can tell, it's broken at their end and our plugin is outputting the code properly as it should. I'm going to close this for now until I can see some way to make any kind of progress on this.
