### ISSUE TITLE
WhatsApp icon not displaying on mobile consistently

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#74]
Some users are experiencing inconsistent display of the WhatsApp button on mobile.

**Comment by Nicholas-Cardot** [comment]
This seems to be caused by certain caching plugins. If a page is cached with the desktop version (without WhatsApp button) then that version of the page is then also being delivered on mobile.

**Comment by DustinWStout** [comment]
Some users are also now seeing WhatsApp button appear on desktop (iref.2618).
