### ISSUE TITLE
[New] Add additional shortcodes into the plugin.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#749]
- [x]  Add a shortcode for $network_shares (e.g. twitter_shares) to display the number of shares for a post for any given social network.
- [x] Add a shortcode for sitewide_$network_shares (e.g. sitewide_twitter_shares) to display the number of shares for any given social network across the entire site.

### Testing Guidance: 
Simply place one or two shortcodes from each category above into a blog post and report back the results.

**Comment by Nicholas-Cardot** [comment]
### Testing Guidance: 
Simply place one or two shortcodes from each category above into a blog post and report back the results.

**Comment by SquanchyMe** [comment]
using `[facebook_shares], [sitewide_facebook_shares] `
and
`[pinterest_shares] [sitewide_pinterest_shares]` in a block, on the same post appeared to return the correct values for Facebook and Pinterest
