### ISSUE TITLE
Fatal Error: Call to undefined function get_the_permalink()

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#75]
For those who may not be up-to-date on their WordPress version, this error can occur. This function was introduced in WordPress version 3.9.

**Comment by Nicholas-Cardot** [comment]
I may dismiss this issue as invalid. WordPress 3.9 has been available for almost 2 years. It's simply not feasible to provide support for versions of WordPress that are that old.

**Comment by Nicholas-Cardot** [comment]
The site in question fixed this error by simply updating to a version of WordPress that is 3.9 or newer. I'm closing this issue as invalid.
