### ISSUE TITLE
[New] Add a "Powered by Social Warfare" opt-in.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#750]
We could add small slogans that mention things like:
"Social Features Proudly Powered by Social Warfare"
"Social Features by Social Warfare"
"Proudly Using Social Warfare"

These would be opt-in only, and we would include a field for users to input their affiliate link so that the slogan/promotion would be of benefit to the user.

**Comment by SquanchyMe** [comment]
Confirmed that the option was there and was OFF by default;
I'm seeing the Powered By and logo on the "More" share sheet, and it goes away when the option is turned off.
I am not seeing anything in the site footer..

**Comment by Nicholas-Cardot** [comment]
> Confirmed that the option was there and was OFF by default;
> I'm seeing the Powered By and logo on the "More" share sheet, and it goes away when the option is turned off.
> I am not seeing anything in the site footer..

@SquanchyMe  Yeah, I wasn't really sure how to get it added to the footer just yet. I'll be looking into it more though to see if I can come up with a good solution for it.
