### ISSUE TITLE
[New] Multiple Pin Image Overlay Interface

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#751]
This would give users an on/off option to activate "Multiple Pinterest Images" that would allow them to have several (no limit?) custom Pinterest images uploaded.

If active, clicking on the Pinterest share button (in the share bar) would activate this full-page overlay:

![Pinterest overlay](https://user-images.githubusercontent.com/2152604/75394747-afc51b80-58a5-11ea-882f-9aefaf18491a.png)

Unique pin button below each image could be URL encoded just like the current Pin button?

**Comment by Nicholas-Cardot** [comment]
Dustin, do we need this to be an on/off toggle, or do we just want to auto-detect, auto-activate this feature whenever more than one Pinterest image is uploaded into the field?

When one image is present, it behaves as it already does. When two images are present, we automatically display the overlay pictured above.

**Comment by DustinWStout** [comment]
@Nicholas-Cardot good call... make it automatic.

**Comment by Nicholas-Cardot** [comment]
This is now ready for testing.

**Comment by Nicholas-Cardot** [comment]
Dustin, I'll need your help cleaning up the CSS so that it looks good on different screen sizes and with different image sizes in the mix.
