### ISSUE TITLE
Remove Google+ button from Styles settings menu

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#752]
It is bugging me. 😂

**Comment by Nicholas-Cardot** [comment]
Is this specifically talking about the button in the preview panel or is there a reference to Google plus somewhere else as well?

**Comment by SquanchyMe** [comment]
In the post editor, in the Social Warfare Custom Options, the descriptions for OG Title and OG Description both still reference Google+

**Comment by Nicholas-Cardot** [comment]
@SquanchyMe Okay, good catch. I've just updated those now as well.

**Comment by SquanchyMe** [comment]
Looks good now. its as if G+ was all just a bad dream...
