### ISSUE TITLE
button emphasis hides share counts

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#756]
When button emphasis is active, if the first two buttons have shares and should be showing them, they don't. 

Setting is active on the beta site.

**Comment by Nicholas-Cardot** [comment]
This isn't a bug. If there isn't enough space for all of the buttons to display properly inside the parent container, it begins to hide assets (share counts) of the widest buttons first until it is able to display everything properly. This is controlled by the flexbox properties of CSS and is perfectly normal behavior. If you remove a button (hence needing less space) or have a wider content area (hence having more space) then it can display all buttons in their entirely. As the space gets smaller, things get hidden.

**Comment by DustinWStout** [comment]
Got it. My bad. Should've caught that.

**Comment by DustinWStout** [comment]
actually,  looking at it again, that doesn't seem right... Take a look at this screenshot:

<img width="706" alt="Screen Shot 2020-03-24 at 12 01 53 PM" src="https://user-images.githubusercontent.com/2152604/77466305-50382e00-6dc7-11ea-8d91-faaeb3e11784.png">
