### ISSUE TITLE
Review/Confirm Tweetcount Setup Section

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#760]
Social Warfare ->Social Identity-> Tweetcount Registration reads:
Step 1: Click Here to VisitTwitcount.com
Step 2: Follow the prompts, blah blah

But there is no mention of what to do if Opensharecount.com is chosen - and when Opensharecount is selected as the provider the page always says that Step 1 is to go to TwitCount.com

This is very confusing and I believe, not fully accurate enough to help/walk someone through the process if they want to use OpenshareCount.

**Comment by Nicholas-Cardot** [comment]
This is now ammended and pushed in a soft update.
