### ISSUE TITLE
Add WP-Admin banner to suggest clearing all caches after updating

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#762]
Cached CSS is a huge issue after upgrading - not only does it generate a fairly _huge_ customer support load, it can be very alarming to the customer.

 If feasible, add a WP-Admin area warning banner that appears after updating Social Warfare (core only?) suggesting that all caches be cleared to prevent incorrect display of sharing-buttons..
If the warning was worded in a way that fully explains what will happen and that their caches will probably automatically clear within a few hours, if the customer ignores the suggestion or does not know how to clear their caches, at least they know what is going on (not sure how many words can be squeezed into the warning)

**Comment by Nicholas-Cardot** [comment]
This has now been added.
