### ISSUE TITLE
Facebook counts not updating

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#766]
_Creating this to track and collect more info/sites experiencing this issue_

When using Core, Facebook share counts are not updating - the YellowBox API info shows nothing returned - no error, just blank/nothing returned OR the "application limit reached" - 

When using Pro (authenticated), the API returns nothing/no data only re-scraping the page gets a new share-count from the API.

**Since tracking, i can see that 99.9% of these reports are coming from France, or .FR  sites

**Comment by SquanchyMe** [comment]
Some returning the known API response:
```
error": {
      "message": "(#4) Application request limit reached",
      "type": "OAuthException"
```

**Comment by SquanchyMe** [comment]
Since tracking, i can see that 99.9% of these reports are coming from France, or .FR  sites

**Comment by SquanchyMe** [comment]
When using Pro (authenticated), the API returns nothing/no data only re-scraping the page gets a new share-count from the API.

**Comment by SquanchyMe** [comment]
4/16 Dev with updated JS share-count method for unauthenticated count-updating is updating counts, but not reflecting the count in the total-shares field.

**Comment by Nicholas-Cardot** [comment]
This should now be fully resolved.
