### ISSUE TITLE
Update Cache-clearing warning to be more clear

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#786]
Many users do not have a cache and do not know what a cache is, and open tickets asking how to clear their cache.
Update to clear-cache warning after updates with something to the effect of "_**IF you have installed a caching plugin**_...."   and "**_consult your caching plugin documentation for more information about how to clear the cache_**"

**Comment by Nicholas-Cardot** [comment]
This is now complete.
