### ISSUE TITLE
Hover Pin Opt-Out does not opt-out the hover pin

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#791]
Enabling "Hover Pin Opt Out" for an image in the media library does not prevent the hover pin from appearing on that image. See internal #387864

**Comment by andbalashov** [comment]
@SquanchyMe  It seems that we no longer have this functionality. Therefore, we can proceed to close this issue and consider removing the corresponding blog article: [Options Page Display Tab Image Hover Pin Button](https://warfareplugins.com/support/options-page-display-tab-image-hover-pin-button/).
