### ISSUE TITLE
Shortcodes render as links instead of buttons in AMP

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#792]
When using shortcodes and AMP is enabled, the buttons render as text-links. Per a customer, no buttons or text-links should be displayed at all on AMP pages.
![shortcode](https://user-images.githubusercontent.com/39499655/90799677-6a1f6380-e2c8-11ea-954b-7fa1d866529f.jpg)

**_Note: "no buttons or text-links should be displayed at all on AMP pages" should be confirmed as part of the AMP specifications before changing anything_**

**Comment by andbalashov** [comment]
@SquanchyMe Could you please provide a ticket number or additional details? I'm currently unable to reproduce the issue. Thank you!
