### ISSUE TITLE
PHP message: PHP Deprecated: strpos(): Non-string needles will be interpreted as strings

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#799]
Using Version 4.1 Master, getting this in the logs: 
`PHP message: PHP Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /wp-content/plugins/social-warfare-pro/lib/frontend-output/SWP_Pro_Header_Output.php on line 683`

**Comment by SteveWiserSites** [comment]
This issue was fixed in https://github.com/warfare-plugins/social-warfare-pro/commit/ab06620f842a03cab619fb0a93135d8bbd11488c
The strpos call in the parse_hex_color method was removed by Nicholas on Jul 23, 2020.

**Comment by SteveWiserSites** [comment]
This issue was fixed in warfare-plugins/social-warfare-pro@ab06620
