### ISSUE TITLE
Consider/Investigate "button cache bypass" advanced option

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#812]
Investigate/consider adding an advanced feature named something like "button cache bypass". 
This ON/OFF option would force all Social Warfare buttons to load the same as when using the `?swp_cache=rebuild`  URL parameter when enabled.

The button description should include a warning that this option should only be used for troubleshooting and that leaving the option enabled may reduce page-load times, etc.

**Comment by Nicholas-Cardot** [comment]
Unfortunately there is no known way to accomplish anything like this. :-(
