### ISSUE TITLE
amp_is_available was called incorrectly

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#825]
See internal # 427316
With debug enabled, getting:
`Notice: amp_is_available was called incorrectly. `amp_is_available()` (or `amp_is_request()`, formerly `is_amp_endpoint()`) was called too early and so it will not work properly. WordPress is currently doing the `wp_loaded` hook. Calling this function before the `wp` action means it will not have access to `WP_Query` and the queried object to determine if it is an AMP response, thus neither the `amp_skip_post()` filter nor the AMP enabled toggle will be considered. It appears the plugin with slug `social-warfare` is responsible; please contact the author. Please see Debugging in WordPress for more information. (This message was added in version 2.0.0.) in /wp-includes/functions.php on line 5313`

**Comment by andbalashov** [comment]
@SquanchyMe The issue has been resolved and the fix will be included in the upcoming release (4.4.7).
