### ISSUE TITLE
“block_categories is deprecated” PHP error

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#833]
PHP error when the WP post/page editor while the page is loading, when WP_DEBUG is enabled. See internal # 444585

Deprecated: block_categories is deprecated since version 5.8.0! Use
block_categories_all instead. in
[website_url]/httpdocs/wp-includes/functions.php on line 5586

Deprecated: block_categories is deprecated since version 5.8.0! Use
block_categories_all instead. in
[website_url]/httpdocs/wp-includes/functions.php on line 5586

**Comment by amyhall-wisersites** [comment]
@SquanchyMe fixed and commit done on https://github.com/goqflash/social-warfare
