### ISSUE TITLE
Support for Google Analytics 4

### ISSUE THREAD

**Issue by yogeshbeniwal** [warfare-plugins/social-warfare#838]
Add feature to support button click tracking using GA 4.

**Comment by yogeshbeniwal** [comment]
@SquanchyMe Does closing this issue here means its tracked internally for development?

**Comment by SquanchyMe** [comment]
please submit all feature requests, bugs, etc through the Social Warfare Support Desk here: 
https://warfareplugins.com/submit-ticket/
Only after being vetted and reviewed internally will the issue be opened here for tracking.
