### ISSUE TITLE
Deprecated: Required parameter $alt follows optional parameter $size

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#846]
Debug message showing when debug is enabled:
Deprecated: Required parameter $alt follows optional parameter $size in /.../plugins/social-warfare-pro/lib/social-networks/SWP_Pro_Pinterest.php on line 358

See internal # 463166  if more info needed.

**Comment by andbalashov** [comment]
@SquanchyMe The issue has been resolved and the fix will be included in the upcoming release (4.4.7).
