### ISSUE TITLE
PHP8 Error: Undefined array key "HTTPUSERAGENT"

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#847]
After updating to PHP8 this error is occurring:
`Undefined array key "HTTPUSERAGENT" in /wp-content/plugins/social-warfare/lib/utilities/SWP_CURL.php on line 49`

See internal #466115

**Comment by andbalashov** [comment]
@SquanchyMe We don't have 49 lines in this file. We have only 44 and I don't see anything that could cause this error. Probably @Nicholas-Cardot  already fixed that.
