### ISSUE TITLE
Possible Cross-Site Request Forgery

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#855]
Customer reporting their WAF is indicating "_WordPress Social Warfare plugin <= 4.3.0 – Cross-Site Request Forgery vulnerability found in version(s) <= 4.3.0_"
See internal #473774 for more info

**Comment by SquanchyMe** [comment]
2nd report:
_cPanel/WHM generated a notification this AM that the plugin has security issues in its last published version. 
WordPress Social Warfare plugin <= 4.3.0 – Missing Authorization vulnerability
press Social Warfare plugin <= 4.3.0 – Cross-Site Request Forgery vulnerability_

**Comment by Nicholas-Cardot** [comment]
This is resolved in the following two commits:

fdf0723298e5d6219df666ca0d31e18d02672457
c655ca7be597a7ea6fd31a81fba1decb42d490fa
