### ISSUE TITLE
Conflict with Simmer recipe plugin

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#93]
I'm working on a theme for a client using the Simmer recipe plugin: https://wordpress.org/plugins/simmer/ as well as an add-on to make the recipe CPT private (so the recipes are only accessible when added to a post with a shortcode): https://wordpress.org/plugins/simmer-private/

SW is kind of freaking out on posts that have a recipe. The sharing icons don't show up at all, even when the post is published, but I get some random unlinked share text in the recipe description. Screenshot: https://cloudup.com/clgrU2_W0lk

I know this isn't necessarily your problem, but Simmer is becoming increasingly popular for recipes - this is the second time a client requested it specifically. I had to use a different social sharing plugin on the first project because SW didn't work correctly. Any chance you could take a look and see if there is a workaround? The client really wants to use SW (especially for Pinterest images) but won't budge on the recipe plugin.

If I need to set up a test site with the conflicting plugins and provide access, I'm happy to do so. This issue persists even with a default WP theme activated and no other plugins.

I talked to one of the Simmer devs who said “Sounds like Social Warfare is missing a check to make sure it only displays once on a single post view in the main loop.”

The embed is technically a post within a post, so I think that’s why SW is freaking out.

**Comment by Nicholas-Cardot** [comment]
Can you install that plugin on our beta/dev site and then setup a post so that I can dig into it a bit, @nutsandbolts ?

**Comment by nutsandbolts** [comment]
No buttons at all when a CPT is embedded in a post. It's published on the beta site as "A Post with Simmer Recipe Embed"

**Comment by Nicholas-Cardot** [comment]
This now fixed and will be rolled out in version 2.1.4
