### ISSUE TITLE
 Add custom UTM-tagged short links to Click-to-Tweets

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#96]
From a customer, _"We'd love the option to be able to add our own UTM-tagged short links to our Click-to-Tweets so we can track results from those separately from general Social Warfare click results."_

**Comment by Nicholas-Cardot** [comment]
I'm not going to be able to modify all the UTM codes. 

Is there just one in particular that I can modify to make this work?
Or does this need to be a shortcode parameter for the one that needs changed?

**Comment by DustinWStout** [comment]
I think we should just add an extra UTM parameter-- `?utm_content=clicktotweet`

We could also consider adding this to the standard button shares also-- `?utm_content=sharebutton`

**Comment by Nicholas-Cardot** [comment]
In an effort to clean up the workflow here on GitHub, we're moving all accepted Feature Requests (including this one) to our internal roadmap so that we can primarily use this space to track bugs, glitches, and plugin & theme conflicts that are occurring with existing features of the plugin. 

So although I'm closing this issue, I'm not dismissing it. I'm simply separating Bugs from Feature Requests by migrating feature requests over to where I'm tracking our roadmap. 

Sometime in the next week or so, we'll have a page up on our website where everyone will be able to publicly view the items (including this one) that we plan to either add to the core plugin or to build out as addons to the plugin. I'll make sure the link to that page is made available at that time.
